module slaarnaaz
use dsp
use slaarnaat
use slaarnabg
use slaarnabp
use store
use slaarnaag, only : czero,zi
use slaarnabt, only : ddot_alt,zdotu_alt,multi_ddot_s,multi_zdotu_s
use slaarnaca,     only : is_ae
implicit none
private
public gauss_per_cusp_orb_eval
integer xyzzyaaaa1,xyzzyaaab1,xyzzyaaac1
real(dp) xyzzyaaad1(3)
contains
subroutine gauss_per_cusp_orb_eval(rvec,jspin,norb,orbmask,norbc,corbm&
&ask,val,fsd,orbval,orbgrad,orblap)
implicit none
integer,intent(in) :: jspin,norb,norbc
real(dp),intent(in) :: rvec(3)
real(dp),intent(inout) :: orbval(norb,real1_complex2),orbgrad(3,norb,r&
&eal1_complex2),orblap(norb,real1_complex2)
logical,intent(in) :: val,fsd,orbmask(norb),corbmask(norbc)
integer xyzzyaaaa2
real(dp) xyzzyaaab2,xyzzyaaac2,xyzzyaaad2,xyzzyaaae2,xyzzyaaaf2,xyzzya&
&aag2,xyzzyaaah2
select case (periodicity)
case(3)
xyzzyaaad1=anint(matmul(rvec,painv))
new_origin=matmul(xyzzyaaad1,pamat)
case(2)
xyzzyaaad1(1:2)=anint(matmul(rvec(1:2),painv(1:2,1:2)))
new_origin(1:2)=matmul(xyzzyaaad1(1:2),pamat(1:2,1:2))
new_origin(3)=0.d0
case(1)
xyzzyaaad1(1)=anint(rvec(1)*painv(1,1))
new_origin(1)=xyzzyaaad1(1)*pamat(1,1)
new_origin(2:3)=0.d0
end select
new_origin_to_rvec=rvec-new_origin
xyzzyaaab2=new_origin(1)
xyzzyaaac2=new_origin(2)
xyzzyaaad2=new_origin(3)
do xyzzyaaaa2=1,num_real_k
xyzzyaaae2=kvec(1,xyzzyaaaa2)
xyzzyaaaf2=kvec(2,xyzzyaaaa2)
xyzzyaaag2=kvec(3,xyzzyaaaa2)
xyzzyaaah2=xyzzyaaae2*xyzzyaaab2+xyzzyaaaf2*xyzzyaaac2+xyzzyaaag2*xyzz&
&yaaad2
coskdotg_shift(xyzzyaaaa2)=cos(xyzzyaaah2)
enddo
do xyzzyaaaa2=num_real_k_plus_1,num_k
xyzzyaaae2=kvec(1,xyzzyaaaa2)
xyzzyaaaf2=kvec(2,xyzzyaaaa2)
xyzzyaaag2=kvec(3,xyzzyaaaa2)
xyzzyaaah2=xyzzyaaae2*xyzzyaaab2+xyzzyaaaf2*xyzzyaaac2+xyzzyaaag2*xyzz&
&yaaad2
expikdotg_shift(xyzzyaaaa2)=exp(xyzzyaaah2*zi)
enddo
xyzzyaaaa1=which_ssingle(jspin,spin_dep_gs)
xyzzyaaab1=which_ssingle(jspin,spin_dep_in)
xyzzyaaac1=which_ssingle(jspin,spin_dep_full)
if(.not.fsd)then
call xyzzyaaae1(jspin,norb,orbmask,norbc,corbmask,orbval)
elseif(.not.val)then
call xyzzyaaaf1(jspin,norb,orbmask,norbc,corbmask,orbgrad,orblap)
else
call xyzzyaaag1(jspin,norb,orbmask,norbc,corbmask,orbval,orbgrad,orbla&
&p)
endif
if(complex_wf)then
if(val)orbval(:,2)=0.d0
if(fsd)then
orbgrad(:,:,2)=0.d0
orblap(:,2)=0.d0
endif
endif
end subroutine gauss_per_cusp_orb_eval
subroutine xyzzyaaae1(jspin,norb,orbmask,norbc,corbmask,orbval)
implicit none
integer,intent(in) :: jspin,norb,norbc
real(dp),intent(inout) :: orbval(norb,real1_complex2)
logical,intent(in) :: orbmask(norb),corbmask(norbc)
integer xyzzyaaaa3,xyzzyaaab3,xyzzyaaac3,xyzzyaaad3,xyzzyaaae3,xyzzyaa&
&af3,xyzzyaaag3,xyzzyaaah3,xyzzyaaai3,xyzzyaaaj3,xyzzyaaak3,xyzzyaaal3&
&,xyzzyaaam3,xyzzyaaan3,xyzzyaaao3,xyzzyaaap3,xyzzyaaaq3,xyzzyaaar3,xy&
&zzyaaas3,xyzzyaaat3,xyzzyaaau3,xyzzyaaav3,xyzzyaaaw3(num_ao),xyzzyaaa&
&x3,xyzzyaaay3
real(dp) xyzzyaaaz3,xyzzyaaba3,xyzzyaabb3,xyzzyaabc3,xyzzyaabd3,xyzzya&
&abe3,xyzzyaabf3,xyzzyaabg3,xyzzyaabh3,xyzzyaabi3,xyzzyaabj3,xyzzyaabk&
&3,xyzzyaabl3(7),xyzzyaabm3,xyzzyaabn3(3),xyzzyaabo3(3),xyzzyaabp3(3),&
&xyzzyaabq3(3),xyzzyaabr3,xyzzyaabs3,xyzzyaabt3,xyzzyaabu3,xyzzyaabv3,&
&xyzzyaabw3,xyzzyaabx3,xyzzyaaby3,xyzzyaabz3,xyzzyaaca3,xyzzyaacb3,xyz&
&zyaacc3
logical xyzzyaacd3,xyzzyaace3(num_shells),xyzzyaacf3,xyzzyaacg3,xyzzya&
&ach3(nemaxc),xyzzyaaci3(nemaxc)
complex(dp) xyzzyaacj3
xyzzyaaaa3=0
rbf=0.d0
rbf_s=0.d0
exp_poly0=0.d0
xyzzyaaci3=.false.
xyzzyaace3=.false.
if(complex_states)then
cbf(:,:)=czero
cbf_s(:,:)=czero
endif
xyzzyaacg3=.true.
xyzzyaach3(:)=.false.
do xyzzyaaab3=1,num_cell
do xyzzyaaac3=1,num_real_k
phase(xyzzyaaac3)=coskdotg(xyzzyaaac3,xyzzyaaab3)*coskdotg_shift(xyzzy&
&aaac3)
enddo
do xyzzyaaac3=num_real_k_plus_1,num_k
cphase(xyzzyaaac3)=expikdotg(xyzzyaaac3,xyzzyaaab3)*expikdotg_shift(xy&
&zzyaaac3)
enddo
do xyzzyaaae3=1,num_centres_in_cell(xyzzyaaab3)
xyzzyaaau3=which_ion(xyzzyaaae3,xyzzyaaab3)
xyzzyaabo3(1)=xpos_in_cell(xyzzyaaae3,xyzzyaaab3)
xyzzyaabo3(2)=ypos_in_cell(xyzzyaaae3,xyzzyaaab3)
xyzzyaabo3(3)=zpos_in_cell(xyzzyaaae3,xyzzyaaab3)
xyzzyaaaz3=new_origin_to_rvec(1)-xyzzyaabo3(1)
xyzzyaaba3=new_origin_to_rvec(2)-xyzzyaabo3(2)
xyzzyaabb3=new_origin_to_rvec(3)-xyzzyaabo3(3)
xyzzyaabc3=xyzzyaaaz3*xyzzyaaaz3
xyzzyaabd3=xyzzyaaba3*xyzzyaaba3
xyzzyaabe3=xyzzyaabb3*xyzzyaabb3
xyzzyaabh3=xyzzyaabc3+xyzzyaabd3+xyzzyaabe3
if(complex_states)then
select case(ndim)
case(1)
xyzzyaabp3(1)=xyzzyaabo3(1)+new_origin(1)
xyzzyaaad1(1)=xyzzyaabp3(1)*ainv(1,1)+1.d-5
xyzzyaabq3(1)=real(floor(xyzzyaaad1(1)),dp)
xyzzyaabn3(1)=xyzzyaabq3(1)*amat(1,1)
xyzzyaaad1(1)=xyzzyaabp3(1)-xyzzyaabn3(1)
xyzzyaabq3(1)=xyzzyaaad1(1)*painv(1,1)+1.d-5
nnn(1)=floor(xyzzyaabq3(1))
case(2)
xyzzyaabp3(1:2)=xyzzyaabo3(1:2)+new_origin(1:2)
xyzzyaaad1(1:2)=matmul(xyzzyaabp3(1:2),ainv(1:2,1:2))+1.d-5
xyzzyaabq3(1:2)=real(floor(xyzzyaaad1(1:2)),dp)
xyzzyaabn3(1:2)=matmul(xyzzyaabq3(1:2),amat(1:2,1:2))
xyzzyaaad1(1:2)=xyzzyaabp3(1:2)-xyzzyaabn3(1:2)
xyzzyaabq3(1:2)=matmul(xyzzyaaad1(1:2),painv(1:2,1:2))+1.d-5
nnn(1:2)=floor(xyzzyaabq3(1:2))
case(3)
xyzzyaabp3=xyzzyaabo3+new_origin
xyzzyaaad1=matmul(xyzzyaabp3,ainv)+1.d-5
xyzzyaabq3=real(floor(xyzzyaaad1),dp)
xyzzyaabn3=matmul(xyzzyaabq3,amat)
xyzzyaaad1=xyzzyaabp3-xyzzyaabn3
xyzzyaabq3=matmul(xyzzyaaad1,painv)+1.d-5
nnn=floor(xyzzyaabq3)
end select
xyzzyaaau3=nbasis_to_nitot(nnn(1),nnn(2),nnn(3),xyzzyaaau3)
endif
if(is_ae(xyzzyaaau3))then
xyzzyaacf3=xyzzyaabh3<rcusp_sq_max(xyzzyaaau3,xyzzyaaac1)
xyzzyaach3(1:nuc_nele(jspin))=xyzzyaabh3<rcusp_sq(1:nuc_nele(jspin),xy&
&zzyaaau3,xyzzyaaac1)
do xyzzyaaat3=1,nuc_nele(jspin)
if(xyzzyaach3(xyzzyaaat3))xyzzyaaci3(xyzzyaaat3)=.true.
enddo
else
xyzzyaacf3=.false.
endif
xyzzyaaaf3=num_shells_on_centre(xyzzyaaae3,xyzzyaaab3)
do xyzzyaaah3=1,xyzzyaaaf3
xyzzyaaaa3=xyzzyaaaa3+1
xyzzyaaai3=shell_sequence_number(xyzzyaaaa3)
xyzzyaabj3=min_exponent(xyzzyaaai3)
xyzzyaabi3=xyzzyaabj3*xyzzyaabh3
if(xyzzyaabi3>screening_tolerance)cycle
xyzzyaaaj3=shell_am(xyzzyaaai3)
xyzzyaaak3=numao_in_shell(xyzzyaaai3)
xyzzyaabl3(1:xyzzyaaak3)=0.d0
xyzzyaaan3=primitive(xyzzyaaai3)
xyzzyaaao3=primitive(xyzzyaaai3+1)-1
xyzzyaacd3=.false.
do xyzzyaaap3=xyzzyaaan3,xyzzyaaao3
xyzzyaabj3=exponent(xyzzyaaap3)
xyzzyaabi3=xyzzyaabj3*xyzzyaabh3
if(xyzzyaabi3>30.d0)cycle
xyzzyaacd3=.true.
xyzzyaace3(xyzzyaaai3)=.true.
xyzzyaabk3=exp(-xyzzyaabi3)
xyzzyaabi3=c_prim(xyzzyaaap3)*xyzzyaabk3
select case (xyzzyaaaj3)
case(1)
xyzzyaabl3(1)=xyzzyaabl3(1)+xyzzyaabi3
case(2)
xyzzyaabl3(1)=xyzzyaabl3(1)+xyzzyaabi3
xyzzyaabi3=c_prim2(xyzzyaaap3)*xyzzyaabk3
xyzzyaabl3(2)=xyzzyaabl3(2)+xyzzyaabi3*xyzzyaaaz3
xyzzyaabl3(3)=xyzzyaabl3(3)+xyzzyaabi3*xyzzyaaba3
xyzzyaabl3(4)=xyzzyaabl3(4)+xyzzyaabi3*xyzzyaabb3
case(3)
xyzzyaabl3(1)=xyzzyaabl3(1)+xyzzyaabi3*xyzzyaaaz3
xyzzyaabl3(2)=xyzzyaabl3(2)+xyzzyaabi3*xyzzyaaba3
xyzzyaabl3(3)=xyzzyaabl3(3)+xyzzyaabi3*xyzzyaabb3
case(4)
xyzzyaabl3(1)=xyzzyaabl3(1)+xyzzyaabi3*(3.d0*xyzzyaabe3-xyzzyaabh3)
xyzzyaabl3(2)=xyzzyaabl3(2)+xyzzyaabi3*xyzzyaaaz3*xyzzyaabb3
xyzzyaabl3(3)=xyzzyaabl3(3)+xyzzyaabi3*xyzzyaaba3*xyzzyaabb3
xyzzyaabl3(4)=xyzzyaabl3(4)+xyzzyaabi3*(xyzzyaabc3-xyzzyaabd3)
xyzzyaabl3(5)=xyzzyaabl3(5)+xyzzyaabi3*xyzzyaaaz3*xyzzyaaba3
case(5)
xyzzyaabr3=xyzzyaabc3*xyzzyaaaz3
xyzzyaabs3=xyzzyaabd3*xyzzyaaba3
xyzzyaabt3=xyzzyaabe3*xyzzyaabb3
xyzzyaabu3=xyzzyaaaz3*xyzzyaaba3
xyzzyaabv3=xyzzyaaaz3*xyzzyaabb3
xyzzyaabw3=xyzzyaaba3*xyzzyaabb3
xyzzyaabx3=xyzzyaabu3*xyzzyaaaz3
xyzzyaaby3=xyzzyaabu3*xyzzyaaba3
xyzzyaabz3=xyzzyaabv3*xyzzyaaaz3
xyzzyaaca3=xyzzyaabv3*xyzzyaabb3
xyzzyaacb3=xyzzyaabw3*xyzzyaaba3
xyzzyaacc3=xyzzyaabw3*xyzzyaabb3
xyzzyaabl3(1)=xyzzyaabl3(1)+xyzzyaabi3*(xyzzyaabt3-1.5d0*(xyzzyaabz3+x&
&yzzyaacb3))
xyzzyaabl3(2)=xyzzyaabl3(2)+xyzzyaabi3*(6.d0*xyzzyaaca3-1.5d0*(xyzzyaa&
&br3+xyzzyaaby3))
xyzzyaabl3(3)=xyzzyaabl3(3)+xyzzyaabi3*(6.d0*xyzzyaacc3-1.5d0*(xyzzyaa&
&bx3+xyzzyaabs3))
xyzzyaabl3(4)=xyzzyaabl3(4)+xyzzyaabi3*15.d0*(xyzzyaabz3-xyzzyaacb3)
xyzzyaabl3(5)=xyzzyaabl3(5)+xyzzyaabi3*30.d0*xyzzyaabu3*xyzzyaabb3
xyzzyaabl3(6)=xyzzyaabl3(6)+xyzzyaabi3*(15.d0*xyzzyaabr3-45.d0*xyzzyaa&
&by3)
xyzzyaabl3(7)=xyzzyaabl3(7)+xyzzyaabi3*(45.d0*xyzzyaabx3-15.d0*xyzzyaa&
&bs3)
end select
enddo
if(xyzzyaacd3)then
xyzzyaaal3=first_ao(xyzzyaaai3)
xyzzyaaam3=xyzzyaaal3+xyzzyaaak3-1
if(.not.xyzzyaacf3.or.xyzzyaaaj3>2)then
do xyzzyaaac3=1,num_real_k
rbf(xyzzyaaal3:xyzzyaaam3,xyzzyaaac3)=rbf(xyzzyaaal3:xyzzyaaam3,xyzzya&
&aac3)+xyzzyaabl3(1:xyzzyaaak3)*phase(xyzzyaaac3)
enddo
do xyzzyaaac3=num_real_k_plus_1,num_k
cbf(xyzzyaaal3:xyzzyaaam3,xyzzyaaac3)=cbf(xyzzyaaal3:xyzzyaaam3,xyzzya&
&aac3)+cmplx(xyzzyaabl3(1:xyzzyaaak3),0.d0,kind=dp)*cphase(xyzzyaaac3)
enddo
else
xyzzyaaat3=0
do xyzzyaaac3=1,num_real_k
rbf(xyzzyaaal3:xyzzyaaam3,xyzzyaaac3)=rbf(xyzzyaaal3:xyzzyaaam3,xyzzya&
&aac3)+xyzzyaabl3(1:xyzzyaaak3)*phase(xyzzyaaac3)
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
xyzzyaaat3=xyzzyaaat3+1
if(xyzzyaach3(xyzzyaaat3))then
rbf_s(xyzzyaaal3,xyzzyaaat3)=rbf_s(xyzzyaaal3,xyzzyaaat3)+xyzzyaabl3(1&
&)*phase(xyzzyaaac3)
endif
enddo
enddo
do xyzzyaaac3=num_real_k_plus_1,num_k
cbf(xyzzyaaal3:xyzzyaaam3,xyzzyaaac3)=cbf(xyzzyaaal3:xyzzyaaam3,xyzzya&
&aac3)+cmplx(xyzzyaabl3(1:xyzzyaaak3),0.d0,kind=dp)*cphase(xyzzyaaac3)
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
xyzzyaaat3=xyzzyaaat3+1
xyzzyaacj3=cmplx(xyzzyaabl3(1),0.d0,kind=dp)*cphase(xyzzyaaac3)
if(xyzzyaach3(xyzzyaaat3))then
cbf_s(xyzzyaaal3,xyzzyaaat3)=cbf_s(xyzzyaaal3,xyzzyaaat3)+xyzzyaacj3
endif
xyzzyaaat3=xyzzyaaat3+1
if(xyzzyaach3(xyzzyaaat3))then
cbf_s(xyzzyaaal3,xyzzyaaat3)=cbf_s(xyzzyaaal3,xyzzyaaat3)+xyzzyaacj3
endif
enddo
enddo
endif
endif
enddo
if(xyzzyaacf3)then
xyzzyaaat3=0
xyzzyaabf3=sqrt(xyzzyaabh3)
do xyzzyaaac3=1,num_real_k
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
xyzzyaaat3=xyzzyaaat3+1
if(xyzzyaach3(xyzzyaaat3))then
xyzzyaabm3=acusp(1,xyzzyaaat3,xyzzyaaau3,xyzzyaaac1)
xyzzyaabg3=1.d0
do xyzzyaaad3=2,5
xyzzyaabg3=xyzzyaabg3*xyzzyaabf3
xyzzyaabm3=xyzzyaabm3+acusp(xyzzyaaad3,xyzzyaaat3,xyzzyaaau3,xyzzyaaac&
&1)*xyzzyaabg3
enddo
if(complex_states)then
exp_poly0(xyzzyaaat3)=exp_poly0(xyzzyaaat3)+exp(xyzzyaabm3)*disign(xyz&
&zyaaat3,xyzzyaaau3,xyzzyaaac1)+pshift(xyzzyaaat3,xyzzyaaau3,xyzzyaaac&
&1)
else
exp_poly0(xyzzyaaat3)=exp_poly0(xyzzyaaat3)+exp(xyzzyaabm3)*disign(xyz&
&zyaaat3,xyzzyaaau3,xyzzyaaac1) *phase(xyzzyaaac3)+pshift(xyzzyaaat3,x&
&yzzyaaau3,xyzzyaaac1)
endif
endif
enddo
enddo
do xyzzyaaac3=num_real_k_plus_1,num_k
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
do xyzzyaaag3=0,1
xyzzyaaat3=xyzzyaaat3+1
if(xyzzyaach3(xyzzyaaat3))then
xyzzyaabm3=0.d0
xyzzyaabm3=acusp(1,xyzzyaaat3,xyzzyaaau3,xyzzyaaac1)
xyzzyaabg3=1.d0
do xyzzyaaad3=2,5
xyzzyaabg3=xyzzyaabg3*xyzzyaabf3
xyzzyaabm3=xyzzyaabm3+acusp(xyzzyaaad3,xyzzyaaat3,xyzzyaaau3,xyzzyaaac&
&1)*xyzzyaabg3
enddo
exp_poly0(xyzzyaaat3)=exp_poly0(xyzzyaaat3)+exp(xyzzyaabm3)*disign(xyz&
&zyaaat3,xyzzyaaau3,xyzzyaaac1) +pshift(xyzzyaaat3,xyzzyaaau3,xyzzyaaa&
&c1)
endif
enddo
enddo
enddo
xyzzyaacg3=.false.
endif
enddo
enddo
if(.not.xyzzyaacg3)then
exp_poly0(1:nuc_nele(jspin))=exp_poly0(1:nuc_nele(jspin))*one_over_rno&
&rm
endif
xyzzyaaar3=0
xyzzyaaas3=0
xyzzyaaax3=gauss_offset(jspin)
xyzzyaaay3=gauss_offsetc(jspin)
if(xyzzyaacg3)then
xyzzyaaav3=0
do xyzzyaaai3=1,num_shells
if(.not.xyzzyaace3(xyzzyaaai3))cycle
xyzzyaaal3=first_ao(xyzzyaaai3)-1
do xyzzyaaat3=1,numao_in_shell(xyzzyaaai3)
xyzzyaaav3=xyzzyaaav3+1
xyzzyaaaw3(xyzzyaaav3)=xyzzyaaal3+xyzzyaaat3
enddo
enddo
do xyzzyaaac3=1,num_real_k
xyzzyaaaf3=nband(xyzzyaaac3,xyzzyaaaa1)
orb1(xyzzyaaar3+1:xyzzyaaar3+xyzzyaaaf3)=multi_ddot_s(xyzzyaaaf3,xyzzy&
&aaav3,xyzzyaaaw3,corbmask(xyzzyaaas3+xyzzyaaay3),rck(:,:,xyzzyaaac3,x&
&yzzyaaab1),maxb*num_ao,maxb,rbf(1,xyzzyaaac3),1.d0)
xyzzyaaar3=xyzzyaaar3+xyzzyaaaf3
xyzzyaaas3=xyzzyaaas3+xyzzyaaaf3
enddo
if(complex_states)then
do xyzzyaaac3=num_real_k_plus_1,num_k
xyzzyaaaf3=nband(xyzzyaaac3,xyzzyaaaa1)
corb1(1:xyzzyaaaf3)=multi_zdotu_s(xyzzyaaaf3,xyzzyaaav3,xyzzyaaaw3,cor&
&bmask(xyzzyaaas3+xyzzyaaay3),cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_&
&ao,maxb,cbf(1,xyzzyaaac3),1.d0)
do xyzzyaaat3=1,xyzzyaaaf3
xyzzyaaar3=xyzzyaaar3+1
xyzzyaaas3=xyzzyaaas3+1
if(.not.corbmask(xyzzyaaas3+xyzzyaaay3-1))cycle
orb1(xyzzyaaar3)=2.d0*real(corb1(xyzzyaaat3),dp)
if(xyzzyaaar3+1<=nuc_nele(jspin))then
xyzzyaaar3=xyzzyaaar3+1
orb1(xyzzyaaar3)=2.d0*aimag(corb1(xyzzyaaat3))
endif
enddo
enddo
endif
else
do xyzzyaaac3=1,num_real_k
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
xyzzyaaar3=xyzzyaaar3+1
xyzzyaaas3=xyzzyaaas3+1
if(.not.corbmask(xyzzyaaas3+xyzzyaaay3-1))cycle
if(xyzzyaaci3(xyzzyaaar3))then
rbf_s(1:num_ao,xyzzyaaar3)=rbf(1:num_ao,xyzzyaaac3)-rbf_s(1:num_ao,xyz&
&zyaaar3)
orb1(xyzzyaaar3)=ddot_alt(num_ao,rck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaaq3,maxb,rbf_s(1,xyzzyaaar3))
orb1(xyzzyaaar3)=orb1(xyzzyaaar3)+exp_poly0(xyzzyaaar3)
else
orb1(xyzzyaaar3)=ddot_alt(num_ao,rck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaaq3,maxb,rbf(1,xyzzyaaac3))
endif
enddo
enddo
if(complex_states)then
do xyzzyaaac3=num_real_k_plus_1,num_k
do xyzzyaaaq3=1,nband(xyzzyaaac3,xyzzyaaaa1)
corb1(1)=czero
xyzzyaaar3=xyzzyaaar3+1
xyzzyaaas3=xyzzyaaas3+1
if(.not.corbmask(xyzzyaaas3+xyzzyaaay3-1))cycle
if(xyzzyaaci3(xyzzyaaar3).and.xyzzyaaci3(xyzzyaaar3+1))then
cbf_s(1:num_ao,xyzzyaaar3)=cbf(1:num_ao,xyzzyaaac3)-cbf_s(1:num_ao,xyz&
&zyaaar3)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaaq3,maxb,cbf_s(1,xyzzyaaar3))
orb1(xyzzyaaar3)=2.d0*real(corb1(1),dp)+exp_poly0(xyzzyaaar3)
if(xyzzyaaar3+1<=nuc_nele(jspin))then
xyzzyaaar3=xyzzyaaar3+1
orb1(xyzzyaaar3)=2.d0*aimag(corb1(1))+exp_poly0(xyzzyaaar3)
endif
else
if(xyzzyaaci3(xyzzyaaar3))then
cbf_s(1:num_ao,xyzzyaaar3)=cbf(1:num_ao,xyzzyaaac3)-cbf_s(1:num_ao,xyz&
&zyaaar3)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaaq3,maxb,cbf_s(1,xyzzyaaar3))
orb1(xyzzyaaar3)=2.d0*real(corb1(1),dp)+exp_poly0(xyzzyaaar3)
else
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaaq3,maxb,cbf(1,xyzzyaaac3))
orb1(xyzzyaaar3)=2.d0*real(corb1(1),dp)
endif
corb1(1)=czero
if(xyzzyaaar3+1<=nuc_nele(jspin))then
xyzzyaaar3=xyzzyaaar3+1
if(xyzzyaaci3(xyzzyaaar3))then
cbf_s(1:num_ao,xyzzyaaar3)=cbf(1:num_ao,xyzzyaaac3)-cbf_s(1:num_ao,xyz&
&zyaaar3)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaaq3,maxb,cbf_s(1,xyzzyaaar3))
orb1(xyzzyaaar3)=2.d0*aimag(corb1(1))+exp_poly0(xyzzyaaar3)
else
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaac3,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaaq3,maxb,cbf(1,xyzzyaaac3))
orb1(xyzzyaaar3)=2.d0*aimag(corb1(1))
endif
endif
endif
enddo
enddo
endif
endif
orbval(xyzzyaaax3:xyzzyaaar3+xyzzyaaax3-1,1)=orb1(1:xyzzyaaar3)*rnorm
if(excite)then
do xyzzyaaat3=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaat3))cycle
xyzzyaaac3=virtual_k(xyzzyaaat3,jspin)
if(xyzzyaaac3<=num_real_k)then
psi(xyzzyaaat3)=sum(rbf(:,xyzzyaaac3)*rck_ex(:,full2vrt(xyzzyaaat3,jsp&
&in),jspin))
else
psi(xyzzyaaat3)=2.d0*sum(real(cbf(:,xyzzyaaac3)*cck_ex(:,full2vrt(xyzz&
&yaaat3,jspin),jspin),dp))
endif
enddo
do xyzzyaaat3=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaat3))cycle
orbval(gauss_gs_norb+xyzzyaaat3,1)=psi(xyzzyaaat3)
enddo
endif
end subroutine xyzzyaaae1
subroutine xyzzyaaaf1(jspin,norb,orbmask,norbc,corbmask,orbgrad,orblap&
&)
implicit none
integer,intent(in) :: jspin,norb,norbc
real(dp),intent(inout) :: orbgrad(3,norb,real1_complex2),orblap(norb,r&
&eal1_complex2)
logical,intent(in) :: orbmask(norb),corbmask(norbc)
integer xyzzyaaaa4,xyzzyaaab4,xyzzyaaac4,xyzzyaaad4,xyzzyaaae4,xyzzyaa&
&af4,xyzzyaaag4,xyzzyaaah4,xyzzyaaai4,xyzzyaaaj4,xyzzyaaak4,xyzzyaaal4&
&,xyzzyaaam4,xyzzyaaan4,xyzzyaaao4,xyzzyaaap4,xyzzyaaaq4,xyzzyaaar4,xy&
&zzyaaas4,xyzzyaaat4,xyzzyaaau4,xyzzyaaav4,xyzzyaaaw4,xyzzyaaax4,xyzzy&
&aaay4(num_ao)
real(dp) xyzzyaaaz4,xyzzyaaba4,xyzzyaabb4,xyzzyaabc4,xyzzyaabd4,xyzzya&
&abe4,xyzzyaabf4,xyzzyaabg4,xyzzyaabh4,xyzzyaabi4,xyzzyaabj4,xyzzyaabk&
&4,xyzzyaabl4,xyzzyaabm4,xyzzyaabn4,xyzzyaabo4,xyzzyaabp4,xyzzyaabq4,x&
&yzzyaabr4,xyzzyaabs4,xyzzyaabt4,xyzzyaabu4,xyzzyaabv4,xyzzyaabw4,xyzz&
&yaabx4,xyzzyaaby4,xyzzyaabz4,xyzzyaaca4,xyzzyaacb4,xyzzyaacc4,xyzzyaa&
&cd4,xyzzyaace4,xyzzyaacf4,xyzzyaacg4,xyzzyaach4,xyzzyaaci4,xyzzyaacj4&
&,xyzzyaack4,xyzzyaacl4,xyzzyaacm4(7),xyzzyaacn4(21),xyzzyaaco4(7),xyz&
&zyaacp4(21),xyzzyaacq4(3),xyzzyaacr4(3),xyzzyaacs4(3),xyzzyaact4(3),x&
&yzzyaacu4,xyzzyaacv4,xyzzyaacw4,xyzzyaacx4,xyzzyaacy4,xyzzyaacz4,xyzz&
&yaada4,xyzzyaadb4,xyzzyaadc4,xyzzyaadd4,xyzzyaade4,xyzzyaadf4,xyzzyaa&
&dg4,xyzzyaadh4,xyzzyaadi4,xyzzyaadj4,xyzzyaadk4,xyzzyaadl4,xyzzyaadm4&
&,xyzzyaadn4,xyzzyaado4,xyzzyaadp4,xyzzyaadq4,xyzzyaadr4,xyzzyaads4
logical xyzzyaadt4,xyzzyaadu4,xyzzyaadv4(nemaxc),xyzzyaadw4(nemaxc),xy&
&zzyaadx4,xyzzyaady4(num_shells)
complex(dp) xyzzyaadz4,xyzzyaaea4
xyzzyaaar4=0
rblap=0.d0
rbgra1=0.d0
rbgra2=0.d0
rbgra3=0.d0
rblap_s=0.d0
rbgra1_s=0.d0
rbgra2_s=0.d0
rbgra3_s=0.d0
exp_poly1=0.d0
exp_poly2=0.d0
exp_poly3=0.d0
exp_poly4=0.d0
xyzzyaadv4=.false.
xyzzyaadw4=.false.
xyzzyaadu4=.true.
xyzzyaady4=.false.
if(complex_states)then
cblap=czero
cbgra1=czero
cbgra2=czero
cbgra3=czero
cblap_s=czero
cbgra1_s=czero
cbgra2_s=czero
cbgra3_s=czero
endif
do xyzzyaaaa4=1,num_cell
do xyzzyaaab4=1,num_real_k
phase(xyzzyaaab4)=coskdotg(xyzzyaaab4,xyzzyaaaa4)*coskdotg_shift(xyzzy&
&aaab4)
enddo
do xyzzyaaab4=num_real_k_plus_1,num_k
cphase(xyzzyaaab4)=expikdotg(xyzzyaaab4,xyzzyaaaa4)*expikdotg_shift(xy&
&zzyaaab4)
enddo
do xyzzyaaaq4=1,num_centres_in_cell(xyzzyaaaa4)
xyzzyaaaw4=which_ion(xyzzyaaaq4,xyzzyaaaa4)
xyzzyaacq4(1)=xpos_in_cell(xyzzyaaaq4,xyzzyaaaa4)
xyzzyaacq4(2)=ypos_in_cell(xyzzyaaaq4,xyzzyaaaa4)
xyzzyaacq4(3)=zpos_in_cell(xyzzyaaaq4,xyzzyaaaa4)
xyzzyaaba4=new_origin_to_rvec(1)-xyzzyaacq4(1)
xyzzyaabb4=new_origin_to_rvec(2)-xyzzyaacq4(2)
xyzzyaabc4=new_origin_to_rvec(3)-xyzzyaacq4(3)
xyzzyaabd4=xyzzyaaba4*xyzzyaaba4
xyzzyaabe4=xyzzyaabb4*xyzzyaabb4
xyzzyaabf4=xyzzyaabc4*xyzzyaabc4
xyzzyaaaz4=xyzzyaabd4+xyzzyaabe4+xyzzyaabf4
if(complex_states)then
select case(ndim)
case(1)
xyzzyaacr4(1)=xyzzyaacq4(1)+new_origin(1)
xyzzyaaad1(1)=xyzzyaacr4(1)*ainv(1,1)+1.d-5
xyzzyaact4(1)=real(floor(xyzzyaaad1(1)),dp)
xyzzyaacs4(1)=xyzzyaact4(1)*amat(1,1)
xyzzyaaad1(1)=xyzzyaacr4(1)-xyzzyaacs4(1)
xyzzyaact4(1)=xyzzyaaad1(1)*painv(1,1)+1.d-5
nnn(1)=floor(xyzzyaact4(1))
case(2)
xyzzyaacr4(1:2)=xyzzyaacq4(1:2)+new_origin(1:2)
xyzzyaaad1(1:2)=matmul(xyzzyaacr4(1:2),ainv(1:2,1:2))+1.d-5
xyzzyaact4(1:2)=real(floor(xyzzyaaad1(1:2)),dp)
xyzzyaacs4(1:2)=matmul(xyzzyaact4(1:2),amat(1:2,1:2))
xyzzyaaad1(1:2)=xyzzyaacr4(1:2)-xyzzyaacs4(1:2)
xyzzyaact4(1:2)=matmul(xyzzyaaad1(1:2),painv(1:2,1:2))+1.d-5
nnn(1:2)=floor(xyzzyaact4(1:2))
case(3)
xyzzyaacr4=xyzzyaacq4+new_origin
xyzzyaaad1=matmul(xyzzyaacr4,ainv)+1.d-5
xyzzyaact4=real(floor(xyzzyaaad1),dp)
xyzzyaacs4=matmul(xyzzyaact4,amat)
xyzzyaaad1=xyzzyaacr4-xyzzyaacs4
xyzzyaact4=matmul(xyzzyaaad1,painv)+1.d-5
nnn=floor(xyzzyaact4)
end select
xyzzyaaaw4=nbasis_to_nitot(nnn(1),nnn(2),nnn(3),xyzzyaaaw4)
endif
if(is_ae(xyzzyaaaw4))then
xyzzyaadt4=xyzzyaaaz4<rcusp_sq_max(xyzzyaaaw4,xyzzyaaac1)
xyzzyaadv4(1:nuc_nele(jspin))=xyzzyaaaz4<rcusp_sq(1:nuc_nele(jspin),xy&
&zzyaaaw4,xyzzyaaac1)
do xyzzyaaaj4=1,nuc_nele(jspin)
if(xyzzyaadv4(xyzzyaaaj4))xyzzyaadw4(xyzzyaaaj4)=.true.
enddo
else
xyzzyaadt4=.false.
endif
xyzzyaaav4=num_shells_on_centre(xyzzyaaaq4,xyzzyaaaa4)
do xyzzyaaac4=1,xyzzyaaav4
xyzzyaaar4=xyzzyaaar4+1
xyzzyaaap4=shell_sequence_number(xyzzyaaar4)
xyzzyaach4=min_exponent(xyzzyaaap4)
xyzzyaabp4=xyzzyaach4*xyzzyaaaz4
if(xyzzyaabp4>screening_tolerance)cycle
xyzzyaaad4=shell_am(xyzzyaaap4)
xyzzyaaae4=numao_in_shell(xyzzyaaap4)
xyzzyaaaf4=xyzzyaaae4*3
do xyzzyaaaj4=1,xyzzyaaae4
xyzzyaaco4(xyzzyaaaj4)=0.d0
enddo
do xyzzyaaaj4=1,xyzzyaaaf4
xyzzyaacp4(xyzzyaaaj4)=0.d0
enddo
xyzzyaaan4=primitive(xyzzyaaap4)
xyzzyaaao4=primitive(xyzzyaaap4+1)-1
xyzzyaadx4=.false.
do xyzzyaaam4=xyzzyaaan4,xyzzyaaao4
xyzzyaach4=exponent(xyzzyaaam4)
xyzzyaabp4=xyzzyaach4*xyzzyaaaz4
if(xyzzyaabp4>30.d0)cycle
xyzzyaadx4=.true.
xyzzyaady4(xyzzyaaap4)=.true.
xyzzyaaci4=exp(-xyzzyaabp4)
xyzzyaabl4=-xyzzyaach4-xyzzyaach4
select case (xyzzyaaad4)
case(1)
xyzzyaacj4=c_prim(xyzzyaaam4)*xyzzyaaci4*xyzzyaabl4
xyzzyaacn4(1)=xyzzyaaba4*xyzzyaacj4
xyzzyaacn4(2)=xyzzyaabb4*xyzzyaacj4
xyzzyaacn4(3)=xyzzyaabc4*xyzzyaacj4
xyzzyaabp4=3.d0+xyzzyaabl4*xyzzyaaaz4
xyzzyaacm4(1)=xyzzyaabp4*xyzzyaacj4
case(2)
xyzzyaacn4(1)=xyzzyaabl4*xyzzyaaba4
xyzzyaacn4(2)=xyzzyaabl4*xyzzyaabb4
xyzzyaacn4(3)=xyzzyaabl4*xyzzyaabc4
xyzzyaacn4(4)=1.d0+xyzzyaacn4(1)*xyzzyaaba4
xyzzyaacn4(5)=xyzzyaacn4(1)*xyzzyaabb4
xyzzyaacn4(6)=xyzzyaacn4(1)*xyzzyaabc4
xyzzyaacn4(8)=1.d0+xyzzyaacn4(2)*xyzzyaabb4
xyzzyaacn4(9)=xyzzyaacn4(2)*xyzzyaabc4
xyzzyaacn4(7)=xyzzyaacn4(5)
xyzzyaacn4(10)=xyzzyaacn4(6)
xyzzyaacn4(11)=xyzzyaacn4(9)
xyzzyaacn4(12)=1.d0+xyzzyaacn4(3)*xyzzyaabc4
xyzzyaacj4=c_prim(xyzzyaaam4)*xyzzyaaci4
xyzzyaack4=c_prim2(xyzzyaaam4)*xyzzyaaci4
xyzzyaacn4(1:3)=xyzzyaacn4(1:3)*xyzzyaacj4
xyzzyaacn4(4:12)=xyzzyaacn4(4:12)*xyzzyaack4
xyzzyaabp4=3.d0+xyzzyaabl4*xyzzyaaaz4
xyzzyaabq4=xyzzyaabl4*xyzzyaabp4
xyzzyaabr4=(xyzzyaabq4+2.d0*xyzzyaabl4)*xyzzyaack4
xyzzyaacm4(1)=xyzzyaabq4*xyzzyaacj4
xyzzyaacm4(2)=xyzzyaabr4*xyzzyaaba4
xyzzyaacm4(3)=xyzzyaabr4*xyzzyaabb4
xyzzyaacm4(4)=xyzzyaabr4*xyzzyaabc4
case(3)
xyzzyaabm4=xyzzyaabl4*xyzzyaaba4
xyzzyaabn4=xyzzyaabl4*xyzzyaabb4
xyzzyaabo4=xyzzyaabl4*xyzzyaabc4
xyzzyaabs4=xyzzyaabl4*(5+xyzzyaabl4*xyzzyaaaz4)
xyzzyaacn4(1)=1.d0+xyzzyaabm4*xyzzyaaba4
xyzzyaacn4(2)=xyzzyaabm4*xyzzyaabb4
xyzzyaacn4(3)=xyzzyaabm4*xyzzyaabc4
xyzzyaacn4(5)=1.d0+xyzzyaabn4*xyzzyaabb4
xyzzyaacn4(6)=xyzzyaabn4*xyzzyaabc4
xyzzyaacn4(9)=1.d0+xyzzyaabo4*xyzzyaabc4
xyzzyaacn4(4)=xyzzyaacn4(2)
xyzzyaacn4(7)=xyzzyaacn4(3)
xyzzyaacn4(8)=xyzzyaacn4(6)
xyzzyaacm4(1)=xyzzyaabs4*xyzzyaaba4
xyzzyaacm4(2)=xyzzyaabs4*xyzzyaabb4
xyzzyaacm4(3)=xyzzyaabs4*xyzzyaabc4
xyzzyaack4=c_prim(xyzzyaaam4)*xyzzyaaci4
xyzzyaacn4(1:9)=xyzzyaacn4(1:9)*xyzzyaack4
xyzzyaacm4(1:3)=xyzzyaacm4(1:3)*xyzzyaack4
case(4)
xyzzyaabg4=xyzzyaaba4*xyzzyaabb4
xyzzyaabh4=xyzzyaabb4*xyzzyaabc4
xyzzyaabi4=xyzzyaaba4*xyzzyaabc4
xyzzyaabk4=xyzzyaabd4-xyzzyaabe4
xyzzyaabj4=3.d0*xyzzyaabf4-xyzzyaaaz4
xyzzyaabm4=xyzzyaabl4*xyzzyaaba4
xyzzyaabn4=xyzzyaabl4*xyzzyaabb4
xyzzyaabo4=xyzzyaabl4*xyzzyaabc4
xyzzyaabp4=1.d0+xyzzyaabm4*xyzzyaaba4
xyzzyaabq4=1.d0+xyzzyaabn4*xyzzyaabb4
xyzzyaabr4=1.d0+xyzzyaabo4*xyzzyaabc4
xyzzyaabs4=xyzzyaabl4*xyzzyaabj4-2.d0
xyzzyaabt4=xyzzyaabl4*xyzzyaabk4
xyzzyaacn4(1)=xyzzyaabs4*xyzzyaaba4
xyzzyaacn4(2)=xyzzyaabs4*xyzzyaabb4
xyzzyaacn4(3)=(xyzzyaabs4+6.d0)*xyzzyaabc4
xyzzyaacn4(4)=xyzzyaabp4*xyzzyaabc4
xyzzyaacn4(5)=xyzzyaabm4*xyzzyaabh4
xyzzyaacn4(6)=xyzzyaabr4*xyzzyaaba4
xyzzyaacn4(7)=xyzzyaacn4(5)
xyzzyaacn4(8)=xyzzyaabq4*xyzzyaabc4
xyzzyaacn4(9)=xyzzyaabr4*xyzzyaabb4
xyzzyaacn4(10)=(2.d0+xyzzyaabl4*xyzzyaabk4)*xyzzyaaba4
xyzzyaacn4(11)=(xyzzyaabt4-2.d0)*xyzzyaabb4
xyzzyaacn4(12)=xyzzyaabt4*xyzzyaabc4
xyzzyaacn4(13)=xyzzyaabp4*xyzzyaabb4
xyzzyaacn4(14)=xyzzyaabq4*xyzzyaaba4
xyzzyaacn4(15)=xyzzyaacn4(5)
xyzzyaacl4=c_prim(xyzzyaaam4)*xyzzyaaci4
xyzzyaacn4(1:15)=xyzzyaacn4(1:15)*xyzzyaacl4
xyzzyaabp4=7.d0+xyzzyaabl4*xyzzyaaaz4
xyzzyaabp4=xyzzyaabl4*xyzzyaabp4*xyzzyaacl4
xyzzyaacm4(1)=xyzzyaabp4*xyzzyaabj4
xyzzyaacm4(2)=xyzzyaabp4*xyzzyaabi4
xyzzyaacm4(3)=xyzzyaabp4*xyzzyaabh4
xyzzyaacm4(4)=xyzzyaabp4*xyzzyaabk4
xyzzyaacm4(5)=xyzzyaabp4*xyzzyaabg4
case(5)
xyzzyaabg4=xyzzyaaba4*xyzzyaabb4
xyzzyaabi4=xyzzyaaba4*xyzzyaabc4
xyzzyaabh4=xyzzyaabb4*xyzzyaabc4
xyzzyaadi4=xyzzyaabg4*xyzzyaabc4
xyzzyaadj4=xyzzyaabd4+xyzzyaabe4
xyzzyaadk4=xyzzyaabe4-xyzzyaabd4
xyzzyaadl4=2.d0*xyzzyaach4
xyzzyaadm4=3.d0*xyzzyaach4
xyzzyaadn4=xyzzyaadl4*xyzzyaabd4
xyzzyaado4=xyzzyaadl4*xyzzyaabe4
xyzzyaadp4=xyzzyaadl4*xyzzyaabf4
xyzzyaadq4=4.d0*xyzzyaabf4
xyzzyaacf4=2.d0*xyzzyaach4*xyzzyaaaz4-9.d0
xyzzyaadr4=3.d0*xyzzyaabd4
xyzzyaads4=3.d0*xyzzyaabe4
xyzzyaabr4=xyzzyaadr4+xyzzyaads4-(2.d0*xyzzyaabf4)
xyzzyaabq4=xyzzyaach4*xyzzyaabr4-3.d0
xyzzyaacn4(1)=xyzzyaabi4*xyzzyaabq4
xyzzyaacn4(2)=xyzzyaabh4*xyzzyaabq4
xyzzyaacm4(1)=(-xyzzyaach4)*xyzzyaabc4*xyzzyaabr4*xyzzyaacf4
xyzzyaabr4=6.d0*xyzzyaabf4
xyzzyaabs4=xyzzyaach4*xyzzyaabr4-3.d0
xyzzyaabt4=2.d0*xyzzyaadp4*xyzzyaabf4
xyzzyaacn4(3)=0.5d0*(xyzzyaabr4-xyzzyaabt4+xyzzyaadj4*xyzzyaabs4)
xyzzyaabu4=xyzzyaadn4*xyzzyaabd4-xyzzyaabe4+xyzzyaadq4
xyzzyaabv4=xyzzyaadl4*(xyzzyaabe4-xyzzyaadq4)-3
xyzzyaacn4(4)=1.5d0*(xyzzyaabu4+xyzzyaabd4*xyzzyaabv4)
xyzzyaabv4=xyzzyaadm4*(xyzzyaadj4-xyzzyaadq4)
xyzzyaacn4(5)=xyzzyaabg4*(xyzzyaabv4-3.d0)
xyzzyaacn4(6)=xyzzyaabi4*(xyzzyaabv4+12.d0)
xyzzyaacm4(2)=(-xyzzyaaba4)*xyzzyaabv4*xyzzyaacf4
xyzzyaacn4(7)=xyzzyaacn4(5)
xyzzyaacn4(9)=xyzzyaabh4*(xyzzyaabv4+12.d0)
xyzzyaabw4=xyzzyaado4*xyzzyaabe4+xyzzyaabd4*(xyzzyaado4-1.d0)
xyzzyaabx4=xyzzyaabe4*(3.d0+8.d0*xyzzyaach4*xyzzyaabf4)
xyzzyaacn4(8)=1.5d0*(xyzzyaabw4-xyzzyaabx4+xyzzyaadq4)
xyzzyaacm4(3)=(-xyzzyaabb4)*xyzzyaabv4*xyzzyaacf4
xyzzyaaby4=xyzzyaach4*xyzzyaadk4
xyzzyaacn4(10)=30.d0*xyzzyaabi4*(xyzzyaaby4+1.d0)
xyzzyaacn4(11)=30.d0*xyzzyaabh4*(xyzzyaaby4-1.d0)
xyzzyaacn4(12)=15.d0*xyzzyaadk4*(xyzzyaadp4-1.d0)
xyzzyaacm4(4)=-30.d0*xyzzyaabc4*xyzzyaaby4*xyzzyaacf4
xyzzyaacn4(13)=30.d0*(1.d0-xyzzyaadn4)*xyzzyaabh4
xyzzyaacn4(14)=30.d0*(1.d0-xyzzyaado4)*xyzzyaabi4
xyzzyaacn4(15)=30.d0*(1.d0-xyzzyaadp4)*xyzzyaabg4
xyzzyaacm4(5)=30.d0*xyzzyaadl4*xyzzyaadi4*xyzzyaacf4
xyzzyaabz4=xyzzyaadr4*(1+xyzzyaado4)
xyzzyaaca4=xyzzyaadn4*xyzzyaabd4+xyzzyaads4
xyzzyaacn4(16)=-15.d0*(xyzzyaaca4-xyzzyaabz4)
xyzzyaacb4=(-30.d0)*xyzzyaach4*(xyzzyaabd4-xyzzyaads4)
xyzzyaacn4(17)=xyzzyaabg4*(xyzzyaacb4-90.d0)
xyzzyaacn4(18)=xyzzyaabi4*xyzzyaacb4
xyzzyaacm4(6)=(-xyzzyaaba4)*xyzzyaacb4*xyzzyaacf4
xyzzyaacc4=30.d0*xyzzyaach4*(xyzzyaabe4-xyzzyaadr4)
xyzzyaacd4=xyzzyaabd4*(6.d0*xyzzyaach4*xyzzyaabe4-3.d0)
xyzzyaace4=xyzzyaabe4*(xyzzyaado4-3.d0)
xyzzyaacn4(19)=xyzzyaabg4*(90.d0+xyzzyaacc4)
xyzzyaacn4(20)=15.d0*(xyzzyaace4-xyzzyaacd4)
xyzzyaacn4(21)=xyzzyaabh4*xyzzyaacc4
xyzzyaacm4(7)=(-xyzzyaabb4)*xyzzyaacc4*xyzzyaacf4
xyzzyaacl4=c_prim(xyzzyaaam4)*xyzzyaaci4
do xyzzyaaaj4=1,21
xyzzyaacn4(xyzzyaaaj4)=xyzzyaacn4(xyzzyaaaj4)*xyzzyaacl4
enddo
do xyzzyaaaj4=1,7
xyzzyaacm4(xyzzyaaaj4)=xyzzyaacm4(xyzzyaaaj4)*xyzzyaacl4
enddo
end select
do xyzzyaaaj4=1,xyzzyaaae4
xyzzyaaco4(xyzzyaaaj4)=xyzzyaaco4(xyzzyaaaj4)+xyzzyaacm4(xyzzyaaaj4)
enddo
do xyzzyaaaj4=1,xyzzyaaaf4
xyzzyaacp4(xyzzyaaaj4)=xyzzyaacp4(xyzzyaaaj4)+xyzzyaacn4(xyzzyaaaj4)
enddo
enddo
if(xyzzyaadx4)then
xyzzyaaas4=first_ao(xyzzyaaap4)
xyzzyaaat4=xyzzyaaas4+xyzzyaaae4-1
if(.not.xyzzyaadt4.or.xyzzyaaad4>2)then
do xyzzyaaab4=1,num_real_k
rblap(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rblap(xyzzyaaas4:xyzzyaaat4,xy&
&zzyaaab4)+xyzzyaaco4(1:xyzzyaaae4)*phase(xyzzyaaab4)
rbgra1(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra1(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(1:xyzzyaaaf4:3)*phase(xyzzyaaab4)
rbgra2(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra2(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(2:xyzzyaaaf4:3)*phase(xyzzyaaab4)
rbgra3(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra3(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(3:xyzzyaaaf4:3)*phase(xyzzyaaab4)
enddo
do xyzzyaaab4=num_real_k_plus_1,num_k
xyzzyaaea4=cphase(xyzzyaaab4)
cblap(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cblap(xyzzyaaas4:xyzzyaaat4,xy&
&zzyaaab4)+cmplx(xyzzyaaco4(1:xyzzyaaae4),0.d0,kind=dp)*xyzzyaaea4
cbgra1(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra1(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(1:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaaea4
cbgra2(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra2(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(2:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaaea4
cbgra3(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra3(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(3:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaaea4
enddo
else
xyzzyaaaj4=0
do xyzzyaaab4=1,num_real_k
rblap(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rblap(xyzzyaaas4:xyzzyaaat4,xy&
&zzyaaab4)+xyzzyaaco4(1:xyzzyaaae4)*phase(xyzzyaaab4)
rbgra1(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra1(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(1:xyzzyaaaf4:3)*phase(xyzzyaaab4)
rbgra2(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra2(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(2:xyzzyaaaf4:3)*phase(xyzzyaaab4)
rbgra3(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=rbgra3(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+xyzzyaacp4(3:xyzzyaaaf4:3)*phase(xyzzyaaab4)
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
xyzzyaaaj4=xyzzyaaaj4+1
if(xyzzyaadv4(xyzzyaaaj4))then
rblap_s(xyzzyaaas4,xyzzyaaaj4)=rblap_s(xyzzyaaas4,xyzzyaaaj4)+xyzzyaac&
&o4(1)*phase(xyzzyaaab4)
rbgra1_s(xyzzyaaas4,xyzzyaaaj4)=rbgra1_s(xyzzyaaas4,xyzzyaaaj4)+xyzzya&
&acp4(1)*phase(xyzzyaaab4)
rbgra2_s(xyzzyaaas4,xyzzyaaaj4)=rbgra2_s(xyzzyaaas4,xyzzyaaaj4)+xyzzya&
&acp4(2)*phase(xyzzyaaab4)
rbgra3_s(xyzzyaaas4,xyzzyaaaj4)=rbgra3_s(xyzzyaaas4,xyzzyaaaj4)+xyzzya&
&acp4(3)*phase(xyzzyaaab4)
endif
enddo
enddo
do xyzzyaaab4=num_real_k_plus_1,num_k
xyzzyaadz4=cphase(xyzzyaaab4)
cblap(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cblap(xyzzyaaas4:xyzzyaaat4,xy&
&zzyaaab4)+cmplx(xyzzyaaco4(1:xyzzyaaae4),0.d0,kind=dp)*xyzzyaadz4
cbgra1(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra1(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(1:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaadz4
cbgra2(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra2(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(2:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaadz4
cbgra3(xyzzyaaas4:xyzzyaaat4,xyzzyaaab4)=cbgra3(xyzzyaaas4:xyzzyaaat4,&
&xyzzyaaab4)+cmplx(xyzzyaacp4(3:xyzzyaaaf4:3),0.d0,kind=dp)*xyzzyaadz4
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
xyzzyaaaj4=xyzzyaaaj4+1
if(xyzzyaadv4(xyzzyaaaj4))then
cblap_s(xyzzyaaas4,xyzzyaaaj4)=cblap_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(xy&
&zzyaaco4(1),0.d0,kind=dp)*xyzzyaadz4
cbgra1_s(xyzzyaaas4,xyzzyaaaj4)=cbgra1_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(1),0.d0,kind=dp)*xyzzyaadz4
cbgra2_s(xyzzyaaas4,xyzzyaaaj4)=cbgra2_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(2),0.d0,kind=dp)*xyzzyaadz4
cbgra3_s(xyzzyaaas4,xyzzyaaaj4)=cbgra3_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(3),0.d0,kind=dp)*xyzzyaadz4
endif
xyzzyaaaj4=xyzzyaaaj4+1
if(xyzzyaadv4(xyzzyaaaj4))then
cblap_s(xyzzyaaas4,xyzzyaaaj4)=cblap_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(xy&
&zzyaaco4(1),0.d0,kind=dp)*xyzzyaadz4
cbgra1_s(xyzzyaaas4,xyzzyaaaj4)=cbgra1_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(1),0.d0,kind=dp)*xyzzyaadz4
cbgra2_s(xyzzyaaas4,xyzzyaaaj4)=cbgra2_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(2),0.d0,kind=dp)*xyzzyaadz4
cbgra3_s(xyzzyaaas4,xyzzyaaaj4)=cbgra3_s(xyzzyaaas4,xyzzyaaaj4)+cmplx(&
&xyzzyaacp4(3),0.d0,kind=dp)*xyzzyaadz4
endif
enddo
enddo
endif
endif
enddo
if(xyzzyaadt4)then
xyzzyaaaj4=0
if(xyzzyaaaz4/=0.d0)then
xyzzyaacg4=sqrt(xyzzyaaaz4)
xyzzyaacu4=1.d0/xyzzyaacg4
xyzzyaacv4=2.d0*xyzzyaacu4
xyzzyaacw4=xyzzyaaba4*xyzzyaacu4
xyzzyaacx4=xyzzyaabb4*xyzzyaacu4
xyzzyaacy4=xyzzyaabc4*xyzzyaacu4
else
xyzzyaacg4=0.d0
xyzzyaacv4=2.d0
xyzzyaacw4=1.d0
xyzzyaacx4=1.d0
xyzzyaacy4=1.d0
endif
do xyzzyaaab4=1,num_real_k
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
xyzzyaaaj4=xyzzyaaaj4+1
if(xyzzyaadv4(xyzzyaaaj4))then
xyzzyaadd4=acusp(1,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaade4=acusp(2,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadf4=acusp(3,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadg4=acusp(4,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadh4=acusp(5,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaacz4=xyzzyaadd4+xyzzyaade4*xyzzyaacg4
xyzzyaada4=xyzzyaade4+2.d0*xyzzyaadf4*xyzzyaacg4
xyzzyaadb4=2.d0*xyzzyaadf4+6.d0*xyzzyaadg4*xyzzyaacg4
xyzzyaadc4=xyzzyaacg4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadf4*xyzzyaadc4
xyzzyaada4=xyzzyaada4+3.d0*xyzzyaadg4*xyzzyaadc4
xyzzyaadb4=xyzzyaadb4+12.d0*xyzzyaadh4*xyzzyaadc4
xyzzyaadc4=xyzzyaadc4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadg4*xyzzyaadc4
xyzzyaada4=xyzzyaada4+4.d0*xyzzyaadh4*xyzzyaadc4
xyzzyaadc4=xyzzyaadc4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadh4*xyzzyaadc4
if(complex_states)then
xyzzyaabp4=exp(xyzzyaacz4)*disign(xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
else
xyzzyaabp4=exp(xyzzyaacz4)*disign(xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)*ph&
&ase(xyzzyaaab4)
endif
xyzzyaabq4=xyzzyaabp4*xyzzyaada4
xyzzyaabr4=(xyzzyaacv4+xyzzyaada4)*xyzzyaada4+xyzzyaadb4
exp_poly1(xyzzyaaaj4)=exp_poly1(xyzzyaaaj4)+xyzzyaabp4*xyzzyaabr4
exp_poly2(xyzzyaaaj4)=exp_poly2(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacw4
exp_poly3(xyzzyaaaj4)=exp_poly3(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacx4
exp_poly4(xyzzyaaaj4)=exp_poly4(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacy4
endif
enddo
enddo
do xyzzyaaab4=num_real_k_plus_1,num_k
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
do xyzzyaaau4=0,1
xyzzyaaaj4=xyzzyaaaj4+1
if(xyzzyaaaj4>nemax)exit
if(xyzzyaadv4(xyzzyaaaj4))then
xyzzyaadd4=acusp(1,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaade4=acusp(2,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadf4=acusp(3,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadg4=acusp(4,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaadh4=acusp(5,xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaacz4=xyzzyaadd4+xyzzyaade4*xyzzyaacg4
xyzzyaada4=xyzzyaade4+2.d0*xyzzyaadf4*xyzzyaacg4
xyzzyaadb4=2.d0*xyzzyaadf4+6.d0*xyzzyaadg4*xyzzyaacg4
xyzzyaadc4=xyzzyaacg4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadf4*xyzzyaadc4
xyzzyaada4=xyzzyaada4+3.d0*xyzzyaadg4*xyzzyaadc4
xyzzyaadb4=xyzzyaadb4+12.d0*xyzzyaadh4*xyzzyaadc4
xyzzyaadc4=xyzzyaadc4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadg4*xyzzyaadc4
xyzzyaada4=xyzzyaada4+4.d0*xyzzyaadh4*xyzzyaadc4
xyzzyaadc4=xyzzyaadc4*xyzzyaacg4
xyzzyaacz4=xyzzyaacz4+xyzzyaadh4*xyzzyaadc4
xyzzyaabp4=exp(xyzzyaacz4)*disign(xyzzyaaaj4,xyzzyaaaw4,xyzzyaaac1)
xyzzyaabq4=xyzzyaabp4*xyzzyaada4
xyzzyaabr4=(xyzzyaacv4+xyzzyaada4)*xyzzyaada4+xyzzyaadb4
exp_poly1(xyzzyaaaj4)=exp_poly1(xyzzyaaaj4)+xyzzyaabp4*xyzzyaabr4
exp_poly2(xyzzyaaaj4)=exp_poly2(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacw4
exp_poly3(xyzzyaaaj4)=exp_poly3(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacx4
exp_poly4(xyzzyaaaj4)=exp_poly4(xyzzyaaaj4)+xyzzyaabq4*xyzzyaacy4
endif
enddo
enddo
enddo
xyzzyaadu4=.false.
endif
enddo
enddo
if(.not.xyzzyaadu4)then
exp_poly1(1:nuc_nele(jspin))=exp_poly1(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly2(1:nuc_nele(jspin))=exp_poly2(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly3(1:nuc_nele(jspin))=exp_poly3(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly4(1:nuc_nele(jspin))=exp_poly4(1:nuc_nele(jspin))*one_over_rno&
&rm
endif
xyzzyaaah4=0
xyzzyaaai4=0
xyzzyaaak4=gauss_offset(jspin)
xyzzyaaal4=gauss_offsetc(jspin)
if(xyzzyaadu4)then
xyzzyaaax4=0
do xyzzyaaap4=1,num_shells
if(.not.xyzzyaady4(xyzzyaaap4))cycle
xyzzyaaas4=first_ao(xyzzyaaap4)-1
do xyzzyaaaj4=1,numao_in_shell(xyzzyaaap4)
xyzzyaaax4=xyzzyaaax4+1
xyzzyaaay4(xyzzyaaax4)=xyzzyaaas4+xyzzyaaaj4
enddo
enddo
do xyzzyaaab4=1,num_real_k
xyzzyaaav4=nband(xyzzyaaab4,xyzzyaaaa1)
orb2(xyzzyaaah4+1:xyzzyaaah4+xyzzyaaav4)=multi_ddot_s(xyzzyaaav4,xyzzy&
&aaax4,xyzzyaaay4,corbmask(xyzzyaaai4+xyzzyaaal4),rck(:,:,xyzzyaaab4,x&
&yzzyaaab1),maxb*num_ao,maxb,rblap(1,xyzzyaaab4),1.d0)
orb3(xyzzyaaah4+1:xyzzyaaah4+xyzzyaaav4)=multi_ddot_s(xyzzyaaav4,xyzzy&
&aaax4,xyzzyaaay4,corbmask(xyzzyaaai4+xyzzyaaal4),rck(:,:,xyzzyaaab4,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra1(1,xyzzyaaab4),1.d0)
orb4(xyzzyaaah4+1:xyzzyaaah4+xyzzyaaav4)=multi_ddot_s(xyzzyaaav4,xyzzy&
&aaax4,xyzzyaaay4,corbmask(xyzzyaaai4+xyzzyaaal4),rck(:,:,xyzzyaaab4,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra2(1,xyzzyaaab4),1.d0)
orb5(xyzzyaaah4+1:xyzzyaaah4+xyzzyaaav4)=multi_ddot_s(xyzzyaaav4,xyzzy&
&aaax4,xyzzyaaay4,corbmask(xyzzyaaai4+xyzzyaaal4),rck(:,:,xyzzyaaab4,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra3(1,xyzzyaaab4),1.d0)
xyzzyaaah4=xyzzyaaah4+xyzzyaaav4
xyzzyaaai4=xyzzyaaai4+xyzzyaaav4
enddo
if(complex_states)then
do xyzzyaaab4=num_real_k_plus_1,num_k
xyzzyaaav4=nband(xyzzyaaab4,xyzzyaaaa1)
corb2(1:xyzzyaaav4)=multi_zdotu_s(xyzzyaaav4,xyzzyaaax4,xyzzyaaay4,cor&
&bmask(xyzzyaaai4+xyzzyaaal4),cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_&
&ao,maxb,cblap(1,xyzzyaaab4),1.d0)
corb3(1:xyzzyaaav4)=multi_zdotu_s(xyzzyaaav4,xyzzyaaax4,xyzzyaaay4,cor&
&bmask(xyzzyaaai4+xyzzyaaal4),cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra1(1,xyzzyaaab4),1.d0)
corb4(1:xyzzyaaav4)=multi_zdotu_s(xyzzyaaav4,xyzzyaaax4,xyzzyaaay4,cor&
&bmask(xyzzyaaai4+xyzzyaaal4),cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra2(1,xyzzyaaab4),1.d0)
corb5(1:xyzzyaaav4)=multi_zdotu_s(xyzzyaaav4,xyzzyaaax4,xyzzyaaay4,cor&
&bmask(xyzzyaaai4+xyzzyaaal4),cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra3(1,xyzzyaaab4),1.d0)
do xyzzyaaaj4=1,xyzzyaaav4
xyzzyaaah4=xyzzyaaah4+1
xyzzyaaai4=xyzzyaaai4+1
if(.not.corbmask(xyzzyaaai4+xyzzyaaal4-1))cycle
orb2(xyzzyaaah4)=2.d0*real(corb2(xyzzyaaaj4),dp)
orb3(xyzzyaaah4)=2.d0*real(corb3(xyzzyaaaj4),dp)
orb4(xyzzyaaah4)=2.d0*real(corb4(xyzzyaaaj4),dp)
orb5(xyzzyaaah4)=2.d0*real(corb5(xyzzyaaaj4),dp)
if(xyzzyaaah4+1<=nuc_nele(jspin))then
xyzzyaaah4=xyzzyaaah4+1
orb2(xyzzyaaah4)=2.d0*aimag(corb2(xyzzyaaaj4))
orb3(xyzzyaaah4)=2.d0*aimag(corb3(xyzzyaaaj4))
orb4(xyzzyaaah4)=2.d0*aimag(corb4(xyzzyaaaj4))
orb5(xyzzyaaah4)=2.d0*aimag(corb5(xyzzyaaaj4))
endif
enddo
enddo
endif
else
do xyzzyaaab4=1,num_real_k
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
xyzzyaaah4=xyzzyaaah4+1
xyzzyaaai4=xyzzyaaai4+1
if(.not.corbmask(xyzzyaaai4+xyzzyaaal4-1))cycle
if(xyzzyaadw4(xyzzyaaah4))then
rblap_s(1:num_ao,xyzzyaaah4)=rblap(1:num_ao,xyzzyaaab4)-rblap_s(1:num_&
&ao,xyzzyaaah4)
rbgra1_s(1:num_ao,xyzzyaaah4)=rbgra1(1:num_ao,xyzzyaaab4)-rbgra1_s(1:n&
&um_ao,xyzzyaaah4)
rbgra2_s(1:num_ao,xyzzyaaah4)=rbgra2(1:num_ao,xyzzyaaab4)-rbgra2_s(1:n&
&um_ao,xyzzyaaah4)
rbgra3_s(1:num_ao,xyzzyaaah4)=rbgra3(1:num_ao,xyzzyaaab4)-rbgra3_s(1:n&
&um_ao,xyzzyaaah4)
orb2(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rblap_s(1,xyzzyaaah4))
orb3(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra1_s(1,xyzzyaaah4))
orb4(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra2_s(1,xyzzyaaah4))
orb5(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra3_s(1,xyzzyaaah4))
orb2(xyzzyaaah4)=orb2(xyzzyaaah4)+exp_poly1(xyzzyaaah4)
orb3(xyzzyaaah4)=orb3(xyzzyaaah4)+exp_poly2(xyzzyaaah4)
orb4(xyzzyaaah4)=orb4(xyzzyaaah4)+exp_poly3(xyzzyaaah4)
orb5(xyzzyaaah4)=orb5(xyzzyaaah4)+exp_poly4(xyzzyaaah4)
else
orb2(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rblap(1,xyzzyaaab4))
orb3(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra1(1,xyzzyaaab4))
orb4(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra2(1,xyzzyaaab4))
orb5(xyzzyaaah4)=ddot_alt(num_ao,rck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag4,maxb,rbgra3(1,xyzzyaaab4))
endif
enddo
enddo
if(complex_states)then
do xyzzyaaab4=num_real_k_plus_1,num_k
do xyzzyaaag4=1,nband(xyzzyaaab4,xyzzyaaaa1)
corb2(1)=czero
corb3(1)=czero
corb4(1)=czero
corb5(1)=czero
xyzzyaaah4=xyzzyaaah4+1
xyzzyaaai4=xyzzyaaai4+1
if(.not.corbmask(xyzzyaaai4+xyzzyaaal4-1))cycle
if(xyzzyaadw4(xyzzyaaah4).and.xyzzyaadw4(xyzzyaaah4+1))then
cblap_s(1:num_ao,xyzzyaaah4)=cblap(1:num_ao,xyzzyaaab4)-cblap_s(1:num_&
&ao,xyzzyaaah4)
cbgra1_s(1:num_ao,xyzzyaaah4)=cbgra1(1:num_ao,xyzzyaaab4)-cbgra1_s(1:n&
&um_ao,xyzzyaaah4)
cbgra2_s(1:num_ao,xyzzyaaah4)=cbgra2(1:num_ao,xyzzyaaab4)-cbgra2_s(1:n&
&um_ao,xyzzyaaah4)
cbgra3_s(1:num_ao,xyzzyaaah4)=cbgra3(1:num_ao,xyzzyaaab4)-cbgra3_s(1:n&
&um_ao,xyzzyaaah4)
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cblap_s(1,xyzzyaaah4))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra1_s(1,xyzzyaaah4))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra2_s(1,xyzzyaaah4))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra3_s(1,xyzzyaaah4))
orb2(xyzzyaaah4)=2.d0*real(corb2(1),dp)+exp_poly1(xyzzyaaah4)
orb3(xyzzyaaah4)=2.d0*real(corb3(1),dp)+exp_poly2(xyzzyaaah4)
orb4(xyzzyaaah4)=2.d0*real(corb4(1),dp)+exp_poly3(xyzzyaaah4)
orb5(xyzzyaaah4)=2.d0*real(corb5(1),dp)+exp_poly4(xyzzyaaah4)
if(xyzzyaaah4+1<=nuc_nele(jspin))then
xyzzyaaah4=xyzzyaaah4+1
orb2(xyzzyaaah4)=2.d0*aimag(corb2(1))+exp_poly1(xyzzyaaah4)
orb3(xyzzyaaah4)=2.d0*aimag(corb3(1))+exp_poly2(xyzzyaaah4)
orb4(xyzzyaaah4)=2.d0*aimag(corb4(1))+exp_poly3(xyzzyaaah4)
orb5(xyzzyaaah4)=2.d0*aimag(corb5(1))+exp_poly4(xyzzyaaah4)
endif
else
if(xyzzyaadw4(xyzzyaaah4))then
cblap_s(1:num_ao,xyzzyaaah4)=cblap(1:num_ao,xyzzyaaab4)-cblap_s(1:num_&
&ao,xyzzyaaah4)
cbgra1_s(1:num_ao,xyzzyaaah4)=cbgra1(1:num_ao,xyzzyaaab4)-cbgra1_s(1:n&
&um_ao,xyzzyaaah4)
cbgra2_s(1:num_ao,xyzzyaaah4)=cbgra2(1:num_ao,xyzzyaaab4)-cbgra2_s(1:n&
&um_ao,xyzzyaaah4)
cbgra3_s(1:num_ao,xyzzyaaah4)=cbgra3(1:num_ao,xyzzyaaab4)-cbgra3_s(1:n&
&um_ao,xyzzyaaah4)
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cblap_s(1,xyzzyaaah4))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra1_s(1,xyzzyaaah4))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra2_s(1,xyzzyaaah4))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra3_s(1,xyzzyaaah4))
orb2(xyzzyaaah4)=2.d0*real(corb2(1),dp)+exp_poly1(xyzzyaaah4)
orb3(xyzzyaaah4)=2.d0*real(corb3(1),dp)+exp_poly2(xyzzyaaah4)
orb4(xyzzyaaah4)=2.d0*real(corb4(1),dp)+exp_poly3(xyzzyaaah4)
orb5(xyzzyaaah4)=2.d0*real(corb5(1),dp)+exp_poly4(xyzzyaaah4)
else
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cblap(1,xyzzyaaab4))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra1(1,xyzzyaaab4))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra2(1,xyzzyaaab4))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra3(1,xyzzyaaab4))
orb2(xyzzyaaah4)=2.d0*real(corb2(1),dp)
orb3(xyzzyaaah4)=2.d0*real(corb3(1),dp)
orb4(xyzzyaaah4)=2.d0*real(corb4(1),dp)
orb5(xyzzyaaah4)=2.d0*real(corb5(1),dp)
endif
if(xyzzyaaah4+1<=nuc_nele(jspin))then
xyzzyaaah4=xyzzyaaah4+1
corb2(1)=czero
corb3(1)=czero
corb4(1)=czero
corb5(1)=czero
if(xyzzyaadw4(xyzzyaaah4))then
cblap_s(1:num_ao,xyzzyaaah4)=cblap(1:num_ao,xyzzyaaab4)-cblap_s(1:num_&
&ao,xyzzyaaah4)
cbgra1_s(1:num_ao,xyzzyaaah4)=cbgra1(1:num_ao,xyzzyaaab4)-cbgra1_s(1:n&
&um_ao,xyzzyaaah4)
cbgra2_s(1:num_ao,xyzzyaaah4)=cbgra2(1:num_ao,xyzzyaaab4)-cbgra2_s(1:n&
&um_ao,xyzzyaaah4)
cbgra3_s(1:num_ao,xyzzyaaah4)=cbgra3(1:num_ao,xyzzyaaab4)-cbgra3_s(1:n&
&um_ao,xyzzyaaah4)
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cblap_s(1,xyzzyaaah4))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra1_s(1,xyzzyaaah4))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra2_s(1,xyzzyaaah4))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra3_s(1,xyzzyaaah4))
orb2(xyzzyaaah4)=2.d0*aimag(corb2(1))+exp_poly1(xyzzyaaah4)
orb3(xyzzyaaah4)=2.d0*aimag(corb3(1))+exp_poly2(xyzzyaaah4)
orb4(xyzzyaaah4)=2.d0*aimag(corb4(1))+exp_poly3(xyzzyaaah4)
orb5(xyzzyaaah4)=2.d0*aimag(corb5(1))+exp_poly4(xyzzyaaah4)
else
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cblap(1,xyzzyaaab4))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra1(1,xyzzyaaab4))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra2(1,xyzzyaaab4))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab4,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag4,maxb,cbgra3(1,xyzzyaaab4))
orb2(xyzzyaaah4)=2.d0*aimag(corb2(1))
orb3(xyzzyaaah4)=2.d0*aimag(corb3(1))
orb4(xyzzyaaah4)=2.d0*aimag(corb4(1))
orb5(xyzzyaaah4)=2.d0*aimag(corb5(1))
endif
endif
endif
enddo
enddo
endif
endif
orblap(xyzzyaaak4:xyzzyaaah4+xyzzyaaak4-1,1)=orb2(1:xyzzyaaah4)*rnorm
orbgrad(1,xyzzyaaak4:xyzzyaaah4+xyzzyaaak4-1,1)=orb3(1:xyzzyaaah4)*rno&
&rm
orbgrad(2,xyzzyaaak4:xyzzyaaah4+xyzzyaaak4-1,1)=orb4(1:xyzzyaaah4)*rno&
&rm
orbgrad(3,xyzzyaaak4:xyzzyaaah4+xyzzyaaak4-1,1)=orb5(1:xyzzyaaah4)*rno&
&rm
if(excite)then
do xyzzyaaaj4=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaaj4))cycle
xyzzyaaab4=virtual_k(xyzzyaaaj4,jspin)
xyzzyaaav4=full2vrt(xyzzyaaaj4,jspin)
if(xyzzyaaab4<=num_real_k)then
flap(xyzzyaaaj4)=sum(rblap(:,xyzzyaaab4)*rck_ex(:,xyzzyaaav4,jspin))
fgra1(xyzzyaaaj4)=sum(rbgra1(:,xyzzyaaab4)*rck_ex(:,xyzzyaaav4,jspin))
fgra2(xyzzyaaaj4)=sum(rbgra2(:,xyzzyaaab4)*rck_ex(:,xyzzyaaav4,jspin))
fgra3(xyzzyaaaj4)=sum(rbgra3(:,xyzzyaaab4)*rck_ex(:,xyzzyaaav4,jspin))
else
flap(xyzzyaaaj4)=2.d0*sum(real(cblap(:,xyzzyaaab4)*cck_ex(:,xyzzyaaav4&
&,jspin),dp))
fgra1(xyzzyaaaj4)=2.d0*sum(real(cbgra1(:,xyzzyaaab4)*cck_ex(:,xyzzyaaa&
&v4,jspin),dp))
fgra2(xyzzyaaaj4)=2.d0*sum(real(cbgra2(:,xyzzyaaab4)*cck_ex(:,xyzzyaaa&
&v4,jspin),dp))
fgra3(xyzzyaaaj4)=2.d0*sum(real(cbgra3(:,xyzzyaaab4)*cck_ex(:,xyzzyaaa&
&v4,jspin),dp))
endif
enddo
do xyzzyaaaj4=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaaj4))cycle
orblap(gauss_gs_norb+xyzzyaaaj4,1)=flap(xyzzyaaaj4)
orbgrad(1,gauss_gs_norb+xyzzyaaaj4,1)=fgra1(xyzzyaaaj4)
orbgrad(2,gauss_gs_norb+xyzzyaaaj4,1)=fgra2(xyzzyaaaj4)
orbgrad(3,gauss_gs_norb+xyzzyaaaj4,1)=fgra3(xyzzyaaaj4)
enddo
endif
end subroutine xyzzyaaaf1
subroutine xyzzyaaag1(jspin,norb,orbmask,norbc,corbmask,orbval,orbgrad&
&,orblap)
implicit none
integer,intent(in) :: jspin,norb,norbc
logical,intent(in) :: orbmask(norb),corbmask(norbc)
real(dp),intent(inout) :: orbval(norb,real1_complex2),orbgrad(3,norb,r&
&eal1_complex2),orblap(norb,real1_complex2)
integer xyzzyaaaa5,xyzzyaaab5,xyzzyaaac5,xyzzyaaad5,xyzzyaaae5,xyzzyaa&
&af5,xyzzyaaag5,xyzzyaaah5,xyzzyaaai5,xyzzyaaaj5,xyzzyaaak5,xyzzyaaal5&
&,xyzzyaaam5,xyzzyaaan5,xyzzyaaao5,xyzzyaaap5,xyzzyaaaq5,xyzzyaaar5,xy&
&zzyaaas5,xyzzyaaat5,xyzzyaaau5,xyzzyaaav5,xyzzyaaaw5,xyzzyaaax5,xyzzy&
&aaay5(num_ao)
logical xyzzyaaaz5,xyzzyaaba5(num_shells)
real(dp) xyzzyaabb5,xyzzyaabc5,xyzzyaabd5,xyzzyaabe5,xyzzyaabf5,xyzzya&
&abg5,xyzzyaabh5,xyzzyaabi5,xyzzyaabj5,xyzzyaabk5,xyzzyaabl5,xyzzyaabm&
&5,xyzzyaabn5,xyzzyaabo5,xyzzyaabp5,xyzzyaabq5,xyzzyaabr5,xyzzyaabs5,x&
&yzzyaabt5,xyzzyaabu5,xyzzyaabv5,xyzzyaabw5,xyzzyaabx5,xyzzyaaby5,xyzz&
&yaabz5,xyzzyaaca5,xyzzyaacb5,xyzzyaacc5,xyzzyaacd5,xyzzyaace5,xyzzyaa&
&cf5,xyzzyaacg5,xyzzyaach5,xyzzyaaci5,xyzzyaacj5,xyzzyaack5,xyzzyaacl5&
&,xyzzyaacm5,xyzzyaacn5,xyzzyaaco5(7),xyzzyaacp5(7),xyzzyaacq5(21),xyz&
&zyaacr5(7),xyzzyaacs5(7),xyzzyaact5(21),xyzzyaacu5(3),xyzzyaacv5(3),x&
&yzzyaacw5(3),xyzzyaacx5(3),xyzzyaacy5,xyzzyaacz5,xyzzyaada5,xyzzyaadb&
&5,xyzzyaadc5,xyzzyaadd5,xyzzyaade5,xyzzyaadf5,xyzzyaadg5,xyzzyaadh5,x&
&yzzyaadi5,xyzzyaadj5,xyzzyaadk5,xyzzyaadl5,xyzzyaadm5,xyzzyaadn5,xyzz&
&yaado5,xyzzyaadp5,xyzzyaadq5,xyzzyaadr5,xyzzyaads5,xyzzyaadt5,xyzzyaa&
&du5,xyzzyaadv5,xyzzyaadw5,xyzzyaadx5,xyzzyaady5,xyzzyaadz5,xyzzyaaea5&
&,xyzzyaaeb5,xyzzyaaec5,xyzzyaaed5,xyzzyaaee5,xyzzyaaef5
logical xyzzyaaeg5,xyzzyaaeh5,xyzzyaaei5(nemax),xyzzyaaej5(nemax)
complex(dp) xyzzyaaek5,xyzzyaael5
xyzzyaaar5=0
rbf=0.d0
rblap=0.d0
rbgra1=0.d0
rbgra2=0.d0
rbgra3=0.d0
rbf_s=0.d0
rblap_s=0.d0
rbgra1_s=0.d0
rbgra2_s=0.d0
rbgra3_s=0.d0
exp_poly0=0.d0
exp_poly1=0.d0
exp_poly2=0.d0
exp_poly3=0.d0
exp_poly4=0.d0
xyzzyaaej5=.false.
xyzzyaaeh5=.true.
xyzzyaaei5(:)=.false.
xyzzyaaba5=.false.
if(complex_states)then
cbf=czero
cblap=czero
cbgra1=czero
cbgra2=czero
cbgra3=czero
cbf_s=czero
cblap_s=czero
cbgra1_s=czero
cbgra2_s=czero
cbgra3_s=czero
endif
do xyzzyaaaa5=1,num_cell
do xyzzyaaab5=1,num_real_k
phase(xyzzyaaab5)=coskdotg(xyzzyaaab5,xyzzyaaaa5)*coskdotg_shift(xyzzy&
&aaab5)
enddo
do xyzzyaaab5=num_real_k_plus_1,num_k
cphase(xyzzyaaab5)=expikdotg(xyzzyaaab5,xyzzyaaaa5)*expikdotg_shift(xy&
&zzyaaab5)
enddo
do xyzzyaaaq5=1,num_centres_in_cell(xyzzyaaaa5)
xyzzyaaaw5=which_ion(xyzzyaaaq5,xyzzyaaaa5)
xyzzyaacu5(1)=xpos_in_cell(xyzzyaaaq5,xyzzyaaaa5)
xyzzyaacu5(2)=ypos_in_cell(xyzzyaaaq5,xyzzyaaaa5)
xyzzyaacu5(3)=zpos_in_cell(xyzzyaaaq5,xyzzyaaaa5)
xyzzyaabc5=new_origin_to_rvec(1)-xyzzyaacu5(1)
xyzzyaabd5=new_origin_to_rvec(2)-xyzzyaacu5(2)
xyzzyaabe5=new_origin_to_rvec(3)-xyzzyaacu5(3)
xyzzyaabf5=xyzzyaabc5*xyzzyaabc5
xyzzyaabg5=xyzzyaabd5*xyzzyaabd5
xyzzyaabh5=xyzzyaabe5*xyzzyaabe5
xyzzyaabb5=xyzzyaabf5+xyzzyaabg5+xyzzyaabh5
if(complex_states)then
select case(ndim)
case(1)
xyzzyaacv5(1)=xyzzyaacu5(1)+new_origin(1)
xyzzyaaad1(1)=xyzzyaacv5(1)*ainv(1,1)+1.d-5
xyzzyaacx5(1)=real(floor(xyzzyaaad1(1)),dp)
xyzzyaacw5(1)=xyzzyaacx5(1)*amat(1,1)
xyzzyaaad1(1)=xyzzyaacv5(1)-xyzzyaacw5(1)
xyzzyaacx5(1)=xyzzyaaad1(1)*painv(1,1)+1.d-5
nnn(1)=floor(xyzzyaacx5(1))
case(2)
xyzzyaacv5(1:2)=xyzzyaacu5(1:2)+new_origin(1:2)
xyzzyaaad1(1:2)=matmul(xyzzyaacv5(1:2),ainv(1:2,1:2))+1.d-5
xyzzyaacx5(1:2)=real(floor(xyzzyaaad1(1:2)),dp)
xyzzyaacw5(1:2)=matmul(xyzzyaacx5(1:2),amat(1:2,1:2))
xyzzyaaad1(1:2)=xyzzyaacv5(1:2)-xyzzyaacw5(1:2)
xyzzyaacx5(1:2)=matmul(xyzzyaaad1(1:2),painv(1:2,1:2))+1.d-5
nnn(1:2)=floor(xyzzyaacx5(1:2))
case(3)
xyzzyaacv5=xyzzyaacu5+new_origin
xyzzyaaad1=matmul(xyzzyaacv5,ainv)+1.d-5
xyzzyaacx5=real(floor(xyzzyaaad1),dp)
xyzzyaacw5=matmul(xyzzyaacx5,amat)
xyzzyaaad1=xyzzyaacv5-xyzzyaacw5
xyzzyaacx5=matmul(xyzzyaaad1,painv)+1.d-5
nnn=floor(xyzzyaacx5)
end select
xyzzyaaaw5=nbasis_to_nitot(nnn(1),nnn(2),nnn(3),xyzzyaaaw5)
endif
if(is_ae(xyzzyaaaw5))then
xyzzyaaeg5=xyzzyaabb5<rcusp_sq_max(xyzzyaaaw5,xyzzyaaac1)
xyzzyaaei5(1:nuc_nele(jspin))=xyzzyaabb5<rcusp_sq(1:nuc_nele(jspin),xy&
&zzyaaaw5,xyzzyaaac1)
do xyzzyaaaj5=1,nuc_nele(jspin)
if(xyzzyaaei5(xyzzyaaaj5))xyzzyaaej5(xyzzyaaaj5)=.true.
enddo
else
xyzzyaaeg5=.false.
endif
xyzzyaaav5=num_shells_on_centre(xyzzyaaaq5,xyzzyaaaa5)
do xyzzyaaac5=1,xyzzyaaav5
xyzzyaaar5=xyzzyaaar5+1
xyzzyaaap5=shell_sequence_number(xyzzyaaar5)
xyzzyaacj5=min_exponent(xyzzyaaap5)
xyzzyaabr5=xyzzyaacj5*xyzzyaabb5
if(xyzzyaabr5>screening_tolerance)cycle
xyzzyaaad5=shell_am(xyzzyaaap5)
xyzzyaaae5=numao_in_shell(xyzzyaaap5)
xyzzyaaaf5=xyzzyaaae5*3
do xyzzyaaaj5=1,xyzzyaaae5
xyzzyaacr5(xyzzyaaaj5)=0.d0
enddo
do xyzzyaaaj5=1,xyzzyaaae5
xyzzyaacs5(xyzzyaaaj5)=0.d0
enddo
do xyzzyaaaj5=1,xyzzyaaaf5
xyzzyaact5(xyzzyaaaj5)=0.d0
enddo
xyzzyaaan5=primitive(xyzzyaaap5)
xyzzyaaao5=primitive(xyzzyaaap5+1)-1
xyzzyaaaz5=.false.
do xyzzyaaam5=xyzzyaaan5,xyzzyaaao5
xyzzyaacj5=exponent(xyzzyaaam5)
xyzzyaabr5=xyzzyaacj5*xyzzyaabb5
if(xyzzyaabr5>30.d0)cycle
xyzzyaaaz5=.true.
xyzzyaaba5(xyzzyaaap5)=.true.
xyzzyaack5=exp(-xyzzyaabr5)
xyzzyaabn5=-xyzzyaacj5-xyzzyaacj5
select case (xyzzyaaad5)
case(1)
xyzzyaaco5(1)=c_prim(xyzzyaaam5)*xyzzyaack5
xyzzyaacl5=xyzzyaaco5(1)*xyzzyaabn5
xyzzyaacq5(1)=xyzzyaabc5*xyzzyaacl5
xyzzyaacq5(2)=xyzzyaabd5*xyzzyaacl5
xyzzyaacq5(3)=xyzzyaabe5*xyzzyaacl5
xyzzyaabr5=3.d0+xyzzyaabn5*xyzzyaabb5
xyzzyaacp5(1)=xyzzyaabr5*xyzzyaacl5
case(2)
xyzzyaacl5=c_prim(xyzzyaaam5)*xyzzyaack5
xyzzyaacm5=c_prim2(xyzzyaaam5)*xyzzyaack5
xyzzyaaco5(1)=xyzzyaacl5
xyzzyaaco5(2)=xyzzyaacm5*xyzzyaabc5
xyzzyaaco5(3)=xyzzyaacm5*xyzzyaabd5
xyzzyaaco5(4)=xyzzyaacm5*xyzzyaabe5
xyzzyaacq5(1)=xyzzyaabn5*xyzzyaabc5
xyzzyaacq5(2)=xyzzyaabn5*xyzzyaabd5
xyzzyaacq5(3)=xyzzyaabn5*xyzzyaabe5
xyzzyaacq5(4)=1.d0+xyzzyaacq5(1)*xyzzyaabc5
xyzzyaacq5(5)=xyzzyaacq5(1)*xyzzyaabd5
xyzzyaacq5(6)=xyzzyaacq5(1)*xyzzyaabe5
xyzzyaacq5(8)=1.d0+xyzzyaacq5(2)*xyzzyaabd5
xyzzyaacq5(9)=xyzzyaacq5(2)*xyzzyaabe5
xyzzyaacq5(7)=xyzzyaacq5(5)
xyzzyaacq5(10)=xyzzyaacq5(6)
xyzzyaacq5(11)=xyzzyaacq5(9)
xyzzyaacq5(12)=1.d0+xyzzyaacq5(3)*xyzzyaabe5
xyzzyaacq5(1:3)=xyzzyaacq5(1:3)*xyzzyaacl5
xyzzyaacq5(4:12)=xyzzyaacq5(4:12)*xyzzyaacm5
xyzzyaabr5=3.d0+xyzzyaabn5*xyzzyaabb5
xyzzyaabs5=xyzzyaabn5*xyzzyaabr5
xyzzyaabt5=(xyzzyaabs5+2.d0*xyzzyaabn5)*xyzzyaacm5
xyzzyaacp5(1)=xyzzyaabs5*xyzzyaacl5
xyzzyaacp5(2)=xyzzyaabt5*xyzzyaabc5
xyzzyaacp5(3)=xyzzyaabt5*xyzzyaabd5
xyzzyaacp5(4)=xyzzyaabt5*xyzzyaabe5
case(3)
xyzzyaacm5=c_prim(xyzzyaaam5)*xyzzyaack5
xyzzyaaco5(1)=xyzzyaacm5*xyzzyaabc5
xyzzyaaco5(2)=xyzzyaacm5*xyzzyaabd5
xyzzyaaco5(3)=xyzzyaacm5*xyzzyaabe5
xyzzyaabo5=xyzzyaabn5*xyzzyaabc5
xyzzyaabp5=xyzzyaabn5*xyzzyaabd5
xyzzyaabq5=xyzzyaabn5*xyzzyaabe5
xyzzyaabu5=xyzzyaabn5*(5+xyzzyaabn5*xyzzyaabb5)
xyzzyaacq5(1)=1.d0+xyzzyaabo5*xyzzyaabc5
xyzzyaacq5(2)=xyzzyaabo5*xyzzyaabd5
xyzzyaacq5(3)=xyzzyaabo5*xyzzyaabe5
xyzzyaacq5(5)=1.d0+xyzzyaabp5*xyzzyaabd5
xyzzyaacq5(6)=xyzzyaabp5*xyzzyaabe5
xyzzyaacq5(9)=1.d0+xyzzyaabq5*xyzzyaabe5
xyzzyaacq5(4)=xyzzyaacq5(2)
xyzzyaacq5(7)=xyzzyaacq5(3)
xyzzyaacq5(8)=xyzzyaacq5(6)
xyzzyaacp5(1)=xyzzyaabu5*xyzzyaabc5
xyzzyaacp5(2)=xyzzyaabu5*xyzzyaabd5
xyzzyaacp5(3)=xyzzyaabu5*xyzzyaabe5
do xyzzyaaaj5=1,9
xyzzyaacq5(xyzzyaaaj5)=xyzzyaacq5(xyzzyaaaj5)*xyzzyaacm5
enddo
do xyzzyaaaj5=1,3
xyzzyaacp5(xyzzyaaaj5)=xyzzyaacp5(xyzzyaaaj5)*xyzzyaacm5
enddo
case(4)
xyzzyaabi5=xyzzyaabc5*xyzzyaabd5
xyzzyaabj5=xyzzyaabd5*xyzzyaabe5
xyzzyaabk5=xyzzyaabc5*xyzzyaabe5
xyzzyaabm5=xyzzyaabf5-xyzzyaabg5
xyzzyaabl5=3.d0*xyzzyaabh5-xyzzyaabb5
xyzzyaaco5(1)=xyzzyaabl5
xyzzyaaco5(2)=xyzzyaabk5
xyzzyaaco5(3)=xyzzyaabj5
xyzzyaaco5(4)=xyzzyaabm5
xyzzyaaco5(5)=xyzzyaabi5
xyzzyaabo5=xyzzyaabn5*xyzzyaabc5
xyzzyaabp5=xyzzyaabn5*xyzzyaabd5
xyzzyaabq5=xyzzyaabn5*xyzzyaabe5
xyzzyaabr5=1.d0+xyzzyaabo5*xyzzyaabc5
xyzzyaabs5=1.d0+xyzzyaabp5*xyzzyaabd5
xyzzyaabt5=1.d0+xyzzyaabq5*xyzzyaabe5
xyzzyaabu5=xyzzyaabn5*xyzzyaabl5-2.d0
xyzzyaabv5=xyzzyaabn5*xyzzyaabm5
xyzzyaacq5(1)=xyzzyaabu5*xyzzyaabc5
xyzzyaacq5(2)=xyzzyaabu5*xyzzyaabd5
xyzzyaacq5(3)=(xyzzyaabu5+6.d0)*xyzzyaabe5
xyzzyaacq5(4)=xyzzyaabr5*xyzzyaabe5
xyzzyaacq5(5)=xyzzyaabo5*xyzzyaabj5
xyzzyaacq5(6)=xyzzyaabt5*xyzzyaabc5
xyzzyaacq5(7)=xyzzyaacq5(5)
xyzzyaacq5(8)=xyzzyaabs5*xyzzyaabe5
xyzzyaacq5(9)=xyzzyaabt5*xyzzyaabd5
xyzzyaacq5(10)=(2.d0+xyzzyaabn5*xyzzyaabm5)*xyzzyaabc5
xyzzyaacq5(11)=(xyzzyaabv5-2.d0)*xyzzyaabd5
xyzzyaacq5(12)=xyzzyaabv5*xyzzyaabe5
xyzzyaacq5(13)=xyzzyaabr5*xyzzyaabd5
xyzzyaacq5(14)=xyzzyaabs5*xyzzyaabc5
xyzzyaacq5(15)=xyzzyaacq5(5)
xyzzyaacn5=c_prim(xyzzyaaam5)*xyzzyaack5
xyzzyaacq5(1:15)=xyzzyaacq5(1:15)*xyzzyaacn5
xyzzyaaco5(1:5)=xyzzyaaco5(1:5)*xyzzyaacn5
xyzzyaabr5=7.d0+xyzzyaabn5*xyzzyaabb5
xyzzyaabr5=xyzzyaabn5*xyzzyaabr5*xyzzyaacn5
xyzzyaacp5(1)=xyzzyaabr5*xyzzyaabl5
xyzzyaacp5(2)=xyzzyaabr5*xyzzyaabk5
xyzzyaacp5(3)=xyzzyaabr5*xyzzyaabj5
xyzzyaacp5(4)=xyzzyaabr5*xyzzyaabm5
xyzzyaacp5(5)=xyzzyaabr5*xyzzyaabi5
case(5)
xyzzyaadm5=xyzzyaabf5*xyzzyaabc5
xyzzyaadn5=xyzzyaabg5*xyzzyaabd5
xyzzyaado5=xyzzyaabh5*xyzzyaabe5
xyzzyaabi5=xyzzyaabc5*xyzzyaabd5
xyzzyaabk5=xyzzyaabc5*xyzzyaabe5
xyzzyaabj5=xyzzyaabd5*xyzzyaabe5
xyzzyaadp5=xyzzyaabi5*xyzzyaabc5
xyzzyaadq5=xyzzyaabi5*xyzzyaabd5
xyzzyaadr5=xyzzyaabk5*xyzzyaabc5
xyzzyaads5=xyzzyaabk5*xyzzyaabe5
xyzzyaadt5=xyzzyaabj5*xyzzyaabd5
xyzzyaadu5=xyzzyaabj5*xyzzyaabe5
xyzzyaadv5=xyzzyaabi5*xyzzyaabe5
xyzzyaadw5=xyzzyaabf5+xyzzyaabg5
xyzzyaadx5=xyzzyaabg5-xyzzyaabf5
xyzzyaady5=3.d0*xyzzyaabf5
xyzzyaadz5=3.d0*xyzzyaabg5
xyzzyaaea5=2.d0*xyzzyaacj5
xyzzyaaeb5=3.d0*xyzzyaacj5
xyzzyaaec5=xyzzyaaea5*xyzzyaabf5
xyzzyaaed5=xyzzyaaea5*xyzzyaabg5
xyzzyaaee5=xyzzyaaea5*xyzzyaabh5
xyzzyaaef5=4.d0*xyzzyaabh5
xyzzyaaco5(1)=xyzzyaado5-1.5d0*(xyzzyaadr5+xyzzyaadt5)
xyzzyaaco5(2)=6.d0*xyzzyaads5-1.5d0*(xyzzyaadm5+xyzzyaadq5)
xyzzyaaco5(3)=6.d0*xyzzyaadu5-1.5d0*(xyzzyaadp5+xyzzyaadn5)
xyzzyaaco5(4)=15.d0*(xyzzyaadr5-xyzzyaadt5)
xyzzyaaco5(5)=30.d0*xyzzyaadv5
xyzzyaaco5(6)=15.d0*xyzzyaadm5-45.d0*xyzzyaadq5
xyzzyaaco5(7)=45.d0*xyzzyaadp5-15.d0*xyzzyaadn5
xyzzyaacn5=c_prim(xyzzyaaam5)*xyzzyaack5
xyzzyaaco5(1:7)=xyzzyaaco5(1:7)*xyzzyaacn5
xyzzyaach5=xyzzyaaea5*(xyzzyaaea5*xyzzyaabb5-9.d0)
xyzzyaacp5(1:7)=xyzzyaaco5(1:7)*xyzzyaach5
xyzzyaabs5=xyzzyaady5+xyzzyaadz5-(2.d0*xyzzyaabh5)
xyzzyaabs5=xyzzyaacj5*xyzzyaabs5-3.d0
xyzzyaacq5(1)=xyzzyaabk5*xyzzyaabs5
xyzzyaacq5(2)=xyzzyaabj5*xyzzyaabs5
xyzzyaabt5=6.d0*xyzzyaabh5
xyzzyaabu5=xyzzyaacj5*xyzzyaabt5-3.d0
xyzzyaabv5=2.d0*xyzzyaaee5*xyzzyaabh5
xyzzyaacq5(3)=0.5d0*(xyzzyaabt5-xyzzyaabv5+xyzzyaadw5*xyzzyaabu5)
xyzzyaabw5=xyzzyaaec5*xyzzyaabf5-xyzzyaabg5+xyzzyaaef5
xyzzyaabx5=xyzzyaaea5*(xyzzyaabg5-xyzzyaaef5)-3
xyzzyaacq5(4)=1.5d0*(xyzzyaabw5+xyzzyaabf5*xyzzyaabx5)
xyzzyaabx5=xyzzyaaeb5*(xyzzyaadw5-xyzzyaaef5)
xyzzyaacq5(5)=xyzzyaabi5*(xyzzyaabx5-3.d0)
xyzzyaacq5(6)=xyzzyaabk5*(xyzzyaabx5+12.d0)
xyzzyaacq5(7)=xyzzyaacq5(5)
xyzzyaacq5(9)=xyzzyaabj5*(xyzzyaabx5+12.d0)
xyzzyaaby5=xyzzyaaed5*xyzzyaabg5+xyzzyaabf5*(xyzzyaaed5-1.d0)
xyzzyaabz5=xyzzyaabg5*(3.d0+8.d0*xyzzyaacj5*xyzzyaabh5)
xyzzyaacq5(8)=1.5d0*(xyzzyaaby5-xyzzyaabz5+xyzzyaaef5)
xyzzyaaca5=xyzzyaacj5*xyzzyaadx5
xyzzyaacq5(10)=30.d0*xyzzyaabk5*(xyzzyaaca5+1.d0)
xyzzyaacq5(11)=30.d0*xyzzyaabj5*(xyzzyaaca5-1.d0)
xyzzyaacq5(12)=15.d0*xyzzyaadx5*(xyzzyaaee5-1.d0)
xyzzyaacq5(13)=30.d0*(1.d0-xyzzyaaec5)*xyzzyaabj5
xyzzyaacq5(14)=30.d0*(1.d0-xyzzyaaed5)*xyzzyaabk5
xyzzyaacq5(15)=30.d0*(1.d0-xyzzyaaee5)*xyzzyaabi5
xyzzyaacb5=xyzzyaady5*(1+xyzzyaaed5)
xyzzyaacc5=xyzzyaaec5*xyzzyaabf5+xyzzyaadz5
xyzzyaacq5(16)=-15.d0*(xyzzyaacc5-xyzzyaacb5)
xyzzyaacd5=(-30.d0)*xyzzyaacj5*(xyzzyaabf5-xyzzyaadz5)
xyzzyaacq5(17)=xyzzyaabi5*(xyzzyaacd5-90.d0)
xyzzyaacq5(18)=xyzzyaabk5*xyzzyaacd5
xyzzyaace5=30.d0*xyzzyaacj5*(xyzzyaabg5-xyzzyaady5)
xyzzyaacf5=xyzzyaabf5*(6.d0*xyzzyaacj5*xyzzyaabg5-3.d0)
xyzzyaacg5=xyzzyaabg5*(xyzzyaaed5-3.d0)
xyzzyaacq5(19)=xyzzyaabi5*(90.d0+xyzzyaace5)
xyzzyaacq5(20)=15.d0*(xyzzyaacg5-xyzzyaacf5)
xyzzyaacq5(21)=xyzzyaabj5*xyzzyaace5
xyzzyaacq5(1:21)=xyzzyaacq5(1:21)*xyzzyaacn5
end select
do xyzzyaaaj5=1,xyzzyaaae5
xyzzyaacr5(xyzzyaaaj5)=xyzzyaacr5(xyzzyaaaj5)+xyzzyaaco5(xyzzyaaaj5)
enddo
do xyzzyaaaj5=1,xyzzyaaae5
xyzzyaacs5(xyzzyaaaj5)=xyzzyaacs5(xyzzyaaaj5)+xyzzyaacp5(xyzzyaaaj5)
enddo
do xyzzyaaaj5=1,xyzzyaaaf5
xyzzyaact5(xyzzyaaaj5)=xyzzyaact5(xyzzyaaaj5)+xyzzyaacq5(xyzzyaaaj5)
enddo
enddo
if(xyzzyaaaz5)then
xyzzyaaas5=first_ao(xyzzyaaap5)
xyzzyaaat5=xyzzyaaas5+xyzzyaaae5-1
if(.not.xyzzyaaeg5.or.xyzzyaaad5>2)then
do xyzzyaaab5=1,num_real_k
rbf(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbf(xyzzyaaas5:xyzzyaaat5,xyzzya&
&aab5)+xyzzyaacr5(1:xyzzyaaae5)*phase(xyzzyaaab5)
rblap(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rblap(xyzzyaaas5:xyzzyaaat5,xy&
&zzyaaab5)+xyzzyaacs5(1:xyzzyaaae5)*phase(xyzzyaaab5)
rbgra1(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra1(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(1:xyzzyaaaf5:3)*phase(xyzzyaaab5)
rbgra2(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra2(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(2:xyzzyaaaf5:3)*phase(xyzzyaaab5)
rbgra3(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra3(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(3:xyzzyaaaf5:3)*phase(xyzzyaaab5)
enddo
do xyzzyaaab5=num_real_k_plus_1,num_k
xyzzyaael5=cphase(xyzzyaaab5)
cbf(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbf(xyzzyaaas5:xyzzyaaat5,xyzzya&
&aab5)+cmplx(xyzzyaacr5(1:xyzzyaaae5),0.d0,kind=dp)*xyzzyaael5
cblap(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cblap(xyzzyaaas5:xyzzyaaat5,xy&
&zzyaaab5)+cmplx(xyzzyaacs5(1:xyzzyaaae5),0.d0,kind=dp)*xyzzyaael5
cbgra1(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra1(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(1:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaael5
cbgra2(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra2(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(2:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaael5
cbgra3(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra3(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(3:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaael5
enddo
else
xyzzyaaaj5=0
do xyzzyaaab5=1,num_real_k
rbf(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbf(xyzzyaaas5:xyzzyaaat5,xyzzya&
&aab5)+xyzzyaacr5(1:xyzzyaaae5)*phase(xyzzyaaab5)
rblap(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rblap(xyzzyaaas5:xyzzyaaat5,xy&
&zzyaaab5)+xyzzyaacs5(1:xyzzyaaae5)*phase(xyzzyaaab5)
rbgra1(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra1(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(1:xyzzyaaaf5:3)*phase(xyzzyaaab5)
rbgra2(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra2(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(2:xyzzyaaaf5:3)*phase(xyzzyaaab5)
rbgra3(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=rbgra3(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+xyzzyaact5(3:xyzzyaaaf5:3)*phase(xyzzyaaab5)
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
xyzzyaaaj5=xyzzyaaaj5+1
if(xyzzyaaei5(xyzzyaaaj5))then
rbf_s(xyzzyaaas5,xyzzyaaaj5)=rbf_s(xyzzyaaas5,xyzzyaaaj5)+xyzzyaacr5(1&
&)*phase(xyzzyaaab5)
rblap_s(xyzzyaaas5,xyzzyaaaj5)=rblap_s(xyzzyaaas5,xyzzyaaaj5)+xyzzyaac&
&s5(1)*phase(xyzzyaaab5)
rbgra1_s(xyzzyaaas5,xyzzyaaaj5)=rbgra1_s(xyzzyaaas5,xyzzyaaaj5)+xyzzya&
&act5(1)*phase(xyzzyaaab5)
rbgra2_s(xyzzyaaas5,xyzzyaaaj5)=rbgra2_s(xyzzyaaas5,xyzzyaaaj5)+xyzzya&
&act5(2)*phase(xyzzyaaab5)
rbgra3_s(xyzzyaaas5,xyzzyaaaj5)=rbgra3_s(xyzzyaaas5,xyzzyaaaj5)+xyzzya&
&act5(3)*phase(xyzzyaaab5)
endif
enddo
enddo
do xyzzyaaab5=num_real_k_plus_1,num_k
xyzzyaaek5=cphase(xyzzyaaab5)
cbf(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbf(xyzzyaaas5:xyzzyaaat5,xyzzya&
&aab5)+cmplx(xyzzyaacr5(1:xyzzyaaae5),0.d0,kind=dp)*xyzzyaaek5
cblap(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cblap(xyzzyaaas5:xyzzyaaat5,xy&
&zzyaaab5)+cmplx(xyzzyaacs5(1:xyzzyaaae5),0.d0,kind=dp)*xyzzyaaek5
cbgra1(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra1(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(1:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaaek5
cbgra2(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra2(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(2:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaaek5
cbgra3(xyzzyaaas5:xyzzyaaat5,xyzzyaaab5)=cbgra3(xyzzyaaas5:xyzzyaaat5,&
&xyzzyaaab5)+cmplx(xyzzyaact5(3:xyzzyaaaf5:3),0.d0,kind=dp)*xyzzyaaek5
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
xyzzyaaaj5=xyzzyaaaj5+1
if(xyzzyaaei5(xyzzyaaaj5))then
cbf_s(xyzzyaaas5,xyzzyaaaj5)=cbf_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(xyzzya&
&acr5(1),0.d0,kind=dp)*xyzzyaaek5
cblap_s(xyzzyaaas5,xyzzyaaaj5)=cblap_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(xy&
&zzyaacs5(1),0.d0,kind=dp)*xyzzyaaek5
cbgra1_s(xyzzyaaas5,xyzzyaaaj5)=cbgra1_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(1),0.d0,kind=dp)*xyzzyaaek5
cbgra2_s(xyzzyaaas5,xyzzyaaaj5)=cbgra2_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(2),0.d0,kind=dp)*xyzzyaaek5
cbgra3_s(xyzzyaaas5,xyzzyaaaj5)=cbgra3_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(3),0.d0,kind=dp)*xyzzyaaek5
endif
xyzzyaaaj5=xyzzyaaaj5+1
if(xyzzyaaei5(xyzzyaaaj5))then
cbf_s(xyzzyaaas5,xyzzyaaaj5)=cbf_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(xyzzya&
&acr5(1),0.d0,kind=dp)*xyzzyaaek5
cblap_s(xyzzyaaas5,xyzzyaaaj5)=cblap_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(xy&
&zzyaacs5(1),0.d0,kind=dp)*xyzzyaaek5
cbgra1_s(xyzzyaaas5,xyzzyaaaj5)=cbgra1_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(1),0.d0,kind=dp)*xyzzyaaek5
cbgra2_s(xyzzyaaas5,xyzzyaaaj5)=cbgra2_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(2),0.d0,kind=dp)*xyzzyaaek5
cbgra3_s(xyzzyaaas5,xyzzyaaaj5)=cbgra3_s(xyzzyaaas5,xyzzyaaaj5)+cmplx(&
&xyzzyaact5(3),0.d0,kind=dp)*xyzzyaaek5
endif
enddo
enddo
endif
endif
enddo
if(xyzzyaaeg5)then
xyzzyaaaj5=0
if(xyzzyaabb5/=0.d0)then
xyzzyaaci5=sqrt(xyzzyaabb5)
xyzzyaacy5=1.d0/xyzzyaaci5
xyzzyaacz5=2.d0*xyzzyaacy5
xyzzyaada5=xyzzyaabc5*xyzzyaacy5
xyzzyaadb5=xyzzyaabd5*xyzzyaacy5
xyzzyaadc5=xyzzyaabe5*xyzzyaacy5
else
xyzzyaaci5=0.d0
xyzzyaacz5=2.d0
xyzzyaada5=1.d0
xyzzyaadb5=1.d0
xyzzyaadc5=1.d0
endif
do xyzzyaaab5=1,num_real_k
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
xyzzyaaaj5=xyzzyaaaj5+1
if(xyzzyaaei5(xyzzyaaaj5))then
xyzzyaadh5=acusp(1,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadi5=acusp(2,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadj5=acusp(3,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadk5=acusp(4,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadl5=acusp(5,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadd5=xyzzyaadh5+xyzzyaadi5*xyzzyaaci5
xyzzyaade5=xyzzyaadi5+2.d0*xyzzyaadj5*xyzzyaaci5
xyzzyaadf5=2.d0*xyzzyaadj5+6.d0*xyzzyaadk5*xyzzyaaci5
xyzzyaadg5=xyzzyaaci5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadj5*xyzzyaadg5
xyzzyaade5=xyzzyaade5+3.d0*xyzzyaadk5*xyzzyaadg5
xyzzyaadf5=xyzzyaadf5+12.d0*xyzzyaadl5*xyzzyaadg5
xyzzyaadg5=xyzzyaadg5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadk5*xyzzyaadg5
xyzzyaade5=xyzzyaade5+4.d0*xyzzyaadl5*xyzzyaadg5
xyzzyaadg5=xyzzyaadg5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadl5*xyzzyaadg5
if(complex_states)then
xyzzyaabr5=exp(xyzzyaadd5)*disign(xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
else
xyzzyaabr5=exp(xyzzyaadd5)*disign(xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)*ph&
&ase(xyzzyaaab5)
endif
xyzzyaabs5=xyzzyaabr5*xyzzyaade5
xyzzyaabt5=(xyzzyaacz5+xyzzyaade5)*xyzzyaade5+xyzzyaadf5
exp_poly0(xyzzyaaaj5)=exp_poly0(xyzzyaaaj5)+xyzzyaabr5+pshift(xyzzyaaa&
&j5,xyzzyaaaw5,xyzzyaaac1)
exp_poly1(xyzzyaaaj5)=exp_poly1(xyzzyaaaj5)+xyzzyaabr5*xyzzyaabt5
exp_poly2(xyzzyaaaj5)=exp_poly2(xyzzyaaaj5)+xyzzyaabs5*xyzzyaada5
exp_poly3(xyzzyaaaj5)=exp_poly3(xyzzyaaaj5)+xyzzyaabs5*xyzzyaadb5
exp_poly4(xyzzyaaaj5)=exp_poly4(xyzzyaaaj5)+xyzzyaabs5*xyzzyaadc5
endif
enddo
enddo
do xyzzyaaab5=num_real_k_plus_1,num_k
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
do xyzzyaaau5=0,1
xyzzyaaaj5=xyzzyaaaj5+1
if(xyzzyaaaj5>nemax)exit
if(xyzzyaaei5(xyzzyaaaj5))then
xyzzyaadh5=acusp(1,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadi5=acusp(2,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadj5=acusp(3,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadk5=acusp(4,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadl5=acusp(5,xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaadd5=xyzzyaadh5+xyzzyaadi5*xyzzyaaci5
xyzzyaade5=xyzzyaadi5+2.d0*xyzzyaadj5*xyzzyaaci5
xyzzyaadf5=2.d0*xyzzyaadj5+6.d0*xyzzyaadk5*xyzzyaaci5
xyzzyaadg5=xyzzyaaci5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadj5*xyzzyaadg5
xyzzyaade5=xyzzyaade5+3.d0*xyzzyaadk5*xyzzyaadg5
xyzzyaadf5=xyzzyaadf5+12.d0*xyzzyaadl5*xyzzyaadg5
xyzzyaadg5=xyzzyaadg5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadk5*xyzzyaadg5
xyzzyaade5=xyzzyaade5+4.d0*xyzzyaadl5*xyzzyaadg5
xyzzyaadg5=xyzzyaadg5*xyzzyaaci5
xyzzyaadd5=xyzzyaadd5+xyzzyaadl5*xyzzyaadg5
xyzzyaabr5=exp(xyzzyaadd5)*disign(xyzzyaaaj5,xyzzyaaaw5,xyzzyaaac1)
xyzzyaabs5=xyzzyaabr5*xyzzyaade5
xyzzyaabt5=(xyzzyaacz5+xyzzyaade5)*xyzzyaade5+xyzzyaadf5
exp_poly0(xyzzyaaaj5)=exp_poly0(xyzzyaaaj5)+xyzzyaabr5+pshift(xyzzyaaa&
&j5,xyzzyaaaw5,xyzzyaaac1)
exp_poly1(xyzzyaaaj5)=exp_poly1(xyzzyaaaj5)+xyzzyaabr5*xyzzyaabt5
exp_poly2(xyzzyaaaj5)=exp_poly2(xyzzyaaaj5)+xyzzyaabs5*xyzzyaada5
exp_poly3(xyzzyaaaj5)=exp_poly3(xyzzyaaaj5)+xyzzyaabs5*xyzzyaadb5
exp_poly4(xyzzyaaaj5)=exp_poly4(xyzzyaaaj5)+xyzzyaabs5*xyzzyaadc5
endif
enddo
enddo
enddo
xyzzyaaeh5=.false.
endif
enddo
enddo
if(.not.xyzzyaaeh5)then
exp_poly0(1:nuc_nele(jspin))=exp_poly0(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly1(1:nuc_nele(jspin))=exp_poly1(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly2(1:nuc_nele(jspin))=exp_poly2(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly3(1:nuc_nele(jspin))=exp_poly3(1:nuc_nele(jspin))*one_over_rno&
&rm
exp_poly4(1:nuc_nele(jspin))=exp_poly4(1:nuc_nele(jspin))*one_over_rno&
&rm
endif
xyzzyaaah5=0
xyzzyaaai5=0
xyzzyaaak5=gauss_offset(jspin)
xyzzyaaal5=gauss_offsetc(jspin)
if(xyzzyaaeh5)then
xyzzyaaax5=0
do xyzzyaaap5=1,num_shells
if(.not.xyzzyaaba5(xyzzyaaap5))cycle
xyzzyaaas5=first_ao(xyzzyaaap5)-1
do xyzzyaaaj5=1,numao_in_shell(xyzzyaaap5)
xyzzyaaax5=xyzzyaaax5+1
xyzzyaaay5(xyzzyaaax5)=xyzzyaaas5+xyzzyaaaj5
enddo
enddo
do xyzzyaaab5=1,num_real_k
xyzzyaaav5=nband(xyzzyaaab5,xyzzyaaaa1)
orb1(xyzzyaaah5+1:xyzzyaaah5+xyzzyaaav5)=multi_ddot_s(xyzzyaaav5,xyzzy&
&aaax5,xyzzyaaay5,corbmask(xyzzyaaai5+xyzzyaaal5),rck(:,:,xyzzyaaab5,x&
&yzzyaaab1),maxb*num_ao,maxb,rbf(1,xyzzyaaab5),1.d0)
orb2(xyzzyaaah5+1:xyzzyaaah5+xyzzyaaav5)=multi_ddot_s(xyzzyaaav5,xyzzy&
&aaax5,xyzzyaaay5,corbmask(xyzzyaaai5+xyzzyaaal5),rck(:,:,xyzzyaaab5,x&
&yzzyaaab1),maxb*num_ao,maxb,rblap(1,xyzzyaaab5),1.d0)
orb3(xyzzyaaah5+1:xyzzyaaah5+xyzzyaaav5)=multi_ddot_s(xyzzyaaav5,xyzzy&
&aaax5,xyzzyaaay5,corbmask(xyzzyaaai5+xyzzyaaal5),rck(:,:,xyzzyaaab5,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra1(1,xyzzyaaab5),1.d0)
orb4(xyzzyaaah5+1:xyzzyaaah5+xyzzyaaav5)=multi_ddot_s(xyzzyaaav5,xyzzy&
&aaax5,xyzzyaaay5,corbmask(xyzzyaaai5+xyzzyaaal5),rck(:,:,xyzzyaaab5,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra2(1,xyzzyaaab5),1.d0)
orb5(xyzzyaaah5+1:xyzzyaaah5+xyzzyaaav5)=multi_ddot_s(xyzzyaaav5,xyzzy&
&aaax5,xyzzyaaay5,corbmask(xyzzyaaai5+xyzzyaaal5),rck(:,:,xyzzyaaab5,x&
&yzzyaaab1),maxb*num_ao,maxb,rbgra3(1,xyzzyaaab5),1.d0)
xyzzyaaah5=xyzzyaaah5+xyzzyaaav5
xyzzyaaai5=xyzzyaaai5+xyzzyaaav5
enddo
if(complex_states)then
do xyzzyaaab5=num_real_k_plus_1,num_k
xyzzyaaav5=nband(xyzzyaaab5,xyzzyaaaa1)
corb1(1:xyzzyaaav5)=multi_zdotu_s(xyzzyaaav5,xyzzyaaax5,xyzzyaaay5,cor&
&bmask(xyzzyaaai5+xyzzyaaal5),cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_&
&ao,maxb,cbf(1,xyzzyaaab5),1.d0)
corb2(1:xyzzyaaav5)=multi_zdotu_s(xyzzyaaav5,xyzzyaaax5,xyzzyaaay5,cor&
&bmask(xyzzyaaai5+xyzzyaaal5),cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_&
&ao,maxb,cblap(1,xyzzyaaab5),1.d0)
corb3(1:xyzzyaaav5)=multi_zdotu_s(xyzzyaaav5,xyzzyaaax5,xyzzyaaay5,cor&
&bmask(xyzzyaaai5+xyzzyaaal5),cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra1(1,xyzzyaaab5),1.d0)
corb4(1:xyzzyaaav5)=multi_zdotu_s(xyzzyaaav5,xyzzyaaax5,xyzzyaaay5,cor&
&bmask(xyzzyaaai5+xyzzyaaal5),cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra2(1,xyzzyaaab5),1.d0)
corb5(1:xyzzyaaav5)=multi_zdotu_s(xyzzyaaav5,xyzzyaaax5,xyzzyaaay5,cor&
&bmask(xyzzyaaai5+xyzzyaaal5),cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_&
&ao,maxb,cbgra3(1,xyzzyaaab5),1.d0)
do xyzzyaaaj5=1,xyzzyaaav5
xyzzyaaah5=xyzzyaaah5+1
xyzzyaaai5=xyzzyaaai5+1
if(.not.corbmask(xyzzyaaai5+xyzzyaaal5-1))cycle
orb1(xyzzyaaah5)=2.d0*real(corb1(xyzzyaaaj5),dp)
orb2(xyzzyaaah5)=2.d0*real(corb2(xyzzyaaaj5),dp)
orb3(xyzzyaaah5)=2.d0*real(corb3(xyzzyaaaj5),dp)
orb4(xyzzyaaah5)=2.d0*real(corb4(xyzzyaaaj5),dp)
orb5(xyzzyaaah5)=2.d0*real(corb5(xyzzyaaaj5),dp)
if(xyzzyaaah5+1<=nuc_nele(jspin))then
xyzzyaaah5=xyzzyaaah5+1
orb1(xyzzyaaah5)=2.d0*aimag(corb1(xyzzyaaaj5))
orb2(xyzzyaaah5)=2.d0*aimag(corb2(xyzzyaaaj5))
orb3(xyzzyaaah5)=2.d0*aimag(corb3(xyzzyaaaj5))
orb4(xyzzyaaah5)=2.d0*aimag(corb4(xyzzyaaaj5))
orb5(xyzzyaaah5)=2.d0*aimag(corb5(xyzzyaaaj5))
endif
enddo
enddo
endif
else
do xyzzyaaab5=1,num_real_k
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
xyzzyaaah5=xyzzyaaah5+1
xyzzyaaai5=xyzzyaaai5+1
if(.not.corbmask(xyzzyaaai5+xyzzyaaal5-1))cycle
if(xyzzyaaej5(xyzzyaaah5))then
rbf_s(1:num_ao,xyzzyaaah5)=rbf(1:num_ao,xyzzyaaab5)-rbf_s(1:num_ao,xyz&
&zyaaah5)
rblap_s(1:num_ao,xyzzyaaah5)=rblap(1:num_ao,xyzzyaaab5)-rblap_s(1:num_&
&ao,xyzzyaaah5)
rbgra1_s(1:num_ao,xyzzyaaah5)=rbgra1(1:num_ao,xyzzyaaab5)-rbgra1_s(1:n&
&um_ao,xyzzyaaah5)
rbgra2_s(1:num_ao,xyzzyaaah5)=rbgra2(1:num_ao,xyzzyaaab5)-rbgra2_s(1:n&
&um_ao,xyzzyaaah5)
rbgra3_s(1:num_ao,xyzzyaaah5)=rbgra3(1:num_ao,xyzzyaaab5)-rbgra3_s(1:n&
&um_ao,xyzzyaaah5)
orb1(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbf_s(1,xyzzyaaah5))
orb2(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rblap_s(1,xyzzyaaah5))
orb3(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra1_s(1,xyzzyaaah5))
orb4(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra2_s(1,xyzzyaaah5))
orb5(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra3_s(1,xyzzyaaah5))
orb1(xyzzyaaah5)=orb1(xyzzyaaah5)+exp_poly0(xyzzyaaah5)
orb2(xyzzyaaah5)=orb2(xyzzyaaah5)+exp_poly1(xyzzyaaah5)
orb3(xyzzyaaah5)=orb3(xyzzyaaah5)+exp_poly2(xyzzyaaah5)
orb4(xyzzyaaah5)=orb4(xyzzyaaah5)+exp_poly3(xyzzyaaah5)
orb5(xyzzyaaah5)=orb5(xyzzyaaah5)+exp_poly4(xyzzyaaah5)
else
orb1(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbf(1,xyzzyaaab5))
orb2(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rblap(1,xyzzyaaab5))
orb3(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra1(1,xyzzyaaab5))
orb4(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra2(1,xyzzyaaab5))
orb5(xyzzyaaah5)=ddot_alt(num_ao,rck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*n&
&um_ao,xyzzyaaag5,maxb,rbgra3(1,xyzzyaaab5))
endif
enddo
enddo
if(complex_states)then
do xyzzyaaab5=num_real_k_plus_1,num_k
do xyzzyaaag5=1,nband(xyzzyaaab5,xyzzyaaaa1)
corb1(1)=czero
corb2(1)=czero
corb3(1)=czero
corb4(1)=czero
corb5(1)=czero
xyzzyaaah5=xyzzyaaah5+1
xyzzyaaai5=xyzzyaaai5+1
if(.not.corbmask(xyzzyaaai5+xyzzyaaal5-1))cycle
if(xyzzyaaej5(xyzzyaaah5).and.xyzzyaaej5(xyzzyaaah5+1))then
cbf_s(1:num_ao,xyzzyaaah5)=cbf(1:num_ao,xyzzyaaab5)-cbf_s(1:num_ao,xyz&
&zyaaah5)
cblap_s(1:num_ao,xyzzyaaah5)=cblap(1:num_ao,xyzzyaaab5)-cblap_s(1:num_&
&ao,xyzzyaaah5)
cbgra1_s(1:num_ao,xyzzyaaah5)=cbgra1(1:num_ao,xyzzyaaab5)-cbgra1_s(1:n&
&um_ao,xyzzyaaah5)
cbgra2_s(1:num_ao,xyzzyaaah5)=cbgra2(1:num_ao,xyzzyaaab5)-cbgra2_s(1:n&
&um_ao,xyzzyaaah5)
cbgra3_s(1:num_ao,xyzzyaaah5)=cbgra3(1:num_ao,xyzzyaaab5)-cbgra3_s(1:n&
&um_ao,xyzzyaaah5)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbf_s(1,xyzzyaaah5))
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cblap_s(1,xyzzyaaah5))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra1_s(1,xyzzyaaah5))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra2_s(1,xyzzyaaah5))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra3_s(1,xyzzyaaah5))
orb1(xyzzyaaah5)=2.d0*real(corb1(1),dp)+exp_poly0(xyzzyaaah5)
orb2(xyzzyaaah5)=2.d0*real(corb2(1),dp)+exp_poly1(xyzzyaaah5)
orb3(xyzzyaaah5)=2.d0*real(corb3(1),dp)+exp_poly2(xyzzyaaah5)
orb4(xyzzyaaah5)=2.d0*real(corb4(1),dp)+exp_poly3(xyzzyaaah5)
orb5(xyzzyaaah5)=2.d0*real(corb5(1),dp)+exp_poly4(xyzzyaaah5)
if(xyzzyaaah5+1<=nuc_nele(jspin))then
xyzzyaaah5=xyzzyaaah5+1
orb1(xyzzyaaah5)=2.d0*aimag(corb1(1))+exp_poly0(xyzzyaaah5)
orb2(xyzzyaaah5)=2.d0*aimag(corb2(1))+exp_poly1(xyzzyaaah5)
orb3(xyzzyaaah5)=2.d0*aimag(corb3(1))+exp_poly2(xyzzyaaah5)
orb4(xyzzyaaah5)=2.d0*aimag(corb4(1))+exp_poly3(xyzzyaaah5)
orb5(xyzzyaaah5)=2.d0*aimag(corb5(1))+exp_poly4(xyzzyaaah5)
endif
else
if(xyzzyaaej5(xyzzyaaah5))then
cbf_s(1:num_ao,xyzzyaaah5)=cbf(1:num_ao,xyzzyaaab5)-cbf_s(1:num_ao,xyz&
&zyaaah5)
cblap_s(1:num_ao,xyzzyaaah5)=cblap(1:num_ao,xyzzyaaab5)-cblap_s(1:num_&
&ao,xyzzyaaah5)
cbgra1_s(1:num_ao,xyzzyaaah5)=cbgra1(1:num_ao,xyzzyaaab5)-cbgra1_s(1:n&
&um_ao,xyzzyaaah5)
cbgra2_s(1:num_ao,xyzzyaaah5)=cbgra2(1:num_ao,xyzzyaaab5)-cbgra2_s(1:n&
&um_ao,xyzzyaaah5)
cbgra3_s(1:num_ao,xyzzyaaah5)=cbgra3(1:num_ao,xyzzyaaab5)-cbgra3_s(1:n&
&um_ao,xyzzyaaah5)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbf_s(1,xyzzyaaah5))
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cblap_s(1,xyzzyaaah5))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra1_s(1,xyzzyaaah5))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra2_s(1,xyzzyaaah5))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra3_s(1,xyzzyaaah5))
orb1(xyzzyaaah5)=2.d0*real(corb1(1),dp)+exp_poly0(xyzzyaaah5)
orb2(xyzzyaaah5)=2.d0*real(corb2(1),dp)+exp_poly1(xyzzyaaah5)
orb3(xyzzyaaah5)=2.d0*real(corb3(1),dp)+exp_poly2(xyzzyaaah5)
orb4(xyzzyaaah5)=2.d0*real(corb4(1),dp)+exp_poly3(xyzzyaaah5)
orb5(xyzzyaaah5)=2.d0*real(corb5(1),dp)+exp_poly4(xyzzyaaah5)
else
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbf(1,xyzzyaaab5))
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cblap(1,xyzzyaaab5))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra1(1,xyzzyaaab5))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra2(1,xyzzyaaab5))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra3(1,xyzzyaaab5))
orb1(xyzzyaaah5)=2.d0*real(corb1(1),dp)
orb2(xyzzyaaah5)=2.d0*real(corb2(1),dp)
orb3(xyzzyaaah5)=2.d0*real(corb3(1),dp)
orb4(xyzzyaaah5)=2.d0*real(corb4(1),dp)
orb5(xyzzyaaah5)=2.d0*real(corb5(1),dp)
endif
if(xyzzyaaah5+1<=nuc_nele(jspin))then
xyzzyaaah5=xyzzyaaah5+1
corb1(1)=czero
corb2(1)=czero
corb3(1)=czero
corb4(1)=czero
corb5(1)=czero
if(xyzzyaaej5(xyzzyaaah5))then
cbf_s(1:num_ao,xyzzyaaah5)=cbf(1:num_ao,xyzzyaaab5)-cbf_s(1:num_ao,xyz&
&zyaaah5)
cblap_s(1:num_ao,xyzzyaaah5)=cblap(1:num_ao,xyzzyaaab5)-cblap_s(1:num_&
&ao,xyzzyaaah5)
cbgra1_s(1:num_ao,xyzzyaaah5)=cbgra1(1:num_ao,xyzzyaaab5)-cbgra1_s(1:n&
&um_ao,xyzzyaaah5)
cbgra2_s(1:num_ao,xyzzyaaah5)=cbgra2(1:num_ao,xyzzyaaab5)-cbgra2_s(1:n&
&um_ao,xyzzyaaah5)
cbgra3_s(1:num_ao,xyzzyaaah5)=cbgra3(1:num_ao,xyzzyaaab5)-cbgra3_s(1:n&
&um_ao,xyzzyaaah5)
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbf_s(1,xyzzyaaah5))
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cblap_s(1,xyzzyaaah5))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra1_s(1,xyzzyaaah5))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra2_s(1,xyzzyaaah5))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra3_s(1,xyzzyaaah5))
orb1(xyzzyaaah5)=2.d0*aimag(corb1(1))+exp_poly0(xyzzyaaah5)
orb2(xyzzyaaah5)=2.d0*aimag(corb2(1))+exp_poly1(xyzzyaaah5)
orb3(xyzzyaaah5)=2.d0*aimag(corb3(1))+exp_poly2(xyzzyaaah5)
orb4(xyzzyaaah5)=2.d0*aimag(corb4(1))+exp_poly3(xyzzyaaah5)
orb5(xyzzyaaah5)=2.d0*aimag(corb5(1))+exp_poly4(xyzzyaaah5)
else
corb1(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbf(1,xyzzyaaab5))
corb2(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cblap(1,xyzzyaaab5))
corb3(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra1(1,xyzzyaaab5))
corb4(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra2(1,xyzzyaaab5))
corb5(1)=zdotu_alt(num_ao,cck(:,:,xyzzyaaab5,xyzzyaaab1),maxb*num_ao,x&
&yzzyaaag5,maxb,cbgra3(1,xyzzyaaab5))
orb1(xyzzyaaah5)=2.d0*aimag(corb1(1))
orb2(xyzzyaaah5)=2.d0*aimag(corb2(1))
orb3(xyzzyaaah5)=2.d0*aimag(corb3(1))
orb4(xyzzyaaah5)=2.d0*aimag(corb4(1))
orb5(xyzzyaaah5)=2.d0*aimag(corb5(1))
endif
endif
endif
enddo
enddo
endif
endif
orbval(xyzzyaaak5:xyzzyaaah5+xyzzyaaak5-1,1)=orb1(1:xyzzyaaah5)*rnorm
orblap(xyzzyaaak5:xyzzyaaah5+xyzzyaaak5-1,1)=orb2(1:xyzzyaaah5)*rnorm
orbgrad(1,xyzzyaaak5:xyzzyaaah5+xyzzyaaak5-1,1)=orb3(1:xyzzyaaah5)*rno&
&rm
orbgrad(2,xyzzyaaak5:xyzzyaaah5+xyzzyaaak5-1,1)=orb4(1:xyzzyaaah5)*rno&
&rm
orbgrad(3,xyzzyaaak5:xyzzyaaah5+xyzzyaaak5-1,1)=orb5(1:xyzzyaaah5)*rno&
&rm
if(excite)then
do xyzzyaaaj5=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaaj5))cycle
xyzzyaaab5=virtual_k(xyzzyaaaj5,jspin)
xyzzyaaav5=full2vrt(xyzzyaaaj5,jspin)
if(xyzzyaaab5<=num_real_k)then
psi(xyzzyaaaj5)=sum(rbf(:,xyzzyaaab5)*rck_ex(:,xyzzyaaav5,jspin))
flap(xyzzyaaaj5)=sum(rblap(:,xyzzyaaab5)*rck_ex(:,xyzzyaaav5,jspin))
fgra1(xyzzyaaaj5)=sum(rbgra1(:,xyzzyaaab5)*rck_ex(:,xyzzyaaav5,jspin))
fgra2(xyzzyaaaj5)=sum(rbgra2(:,xyzzyaaab5)*rck_ex(:,xyzzyaaav5,jspin))
fgra3(xyzzyaaaj5)=sum(rbgra3(:,xyzzyaaab5)*rck_ex(:,xyzzyaaav5,jspin))
else
psi(xyzzyaaaj5)=2.d0*sum(real(cbf(:,xyzzyaaab5)*cck_ex(:,xyzzyaaav5,js&
&pin),dp))
flap(xyzzyaaaj5)=2.d0*sum(real(cblap(:,xyzzyaaab5)*cck_ex(:,xyzzyaaav5&
&,jspin),dp))
fgra1(xyzzyaaaj5)=2.d0*sum(real(cbgra1(:,xyzzyaaab5)*cck_ex(:,xyzzyaaa&
&v5,jspin),dp))
fgra2(xyzzyaaaj5)=2.d0*sum(real(cbgra2(:,xyzzyaaab5)*cck_ex(:,xyzzyaaa&
&v5,jspin),dp))
fgra3(xyzzyaaaj5)=2.d0*sum(real(cbgra3(:,xyzzyaaab5)*cck_ex(:,xyzzyaaa&
&v5,jspin),dp))
endif
enddo
do xyzzyaaaj5=1,gauss_ex_norb
if(.not.orbmask(gauss_gs_norb+xyzzyaaaj5))cycle
orbval(gauss_gs_norb+xyzzyaaaj5,1)=psi(xyzzyaaaj5)
orblap(gauss_gs_norb+xyzzyaaaj5,1)=flap(xyzzyaaaj5)
orbgrad(1,gauss_gs_norb+xyzzyaaaj5,1)=fgra1(xyzzyaaaj5)
orbgrad(2,gauss_gs_norb+xyzzyaaaj5,1)=fgra2(xyzzyaaaj5)
orbgrad(3,gauss_gs_norb+xyzzyaaaj5,1)=fgra3(xyzzyaaaj5)
enddo
endif
end subroutine xyzzyaaag1
end module slaarnaaz
