module slaarnacl
use slaarnaag
use dsp
use parallel
use file_utils,   only : open_units,skip
use format_utils, only : wout,i2s,r2s,display_param,write_list_int,wor&
&dwrap
use slaarnaat,    only : cusp_correction
use slaarnabg,     only : atomic_number=>atno,atom_pos=>basis,num_atom&
&s=>nbasis,pamat,pa1,pa2,pa3,which_ion_displaced,ion_displacement,ispe&
&riodic,npcells,periodicity
use slaarnabp,         only : read_mdet_wfn,wf_np,wf_nm,wf_nd,wf_pm,wf&
&_d,modified_mdet,detcoef,mods,mdet_max_mods
use slaarnabt,    only : inverse
use run_control,  only : errstop,errwarn,errwarn_silent,errstop_master&
&,check_alloc
use store,        only : ndet,nemax,nspin,real1_complex2,open_unit,nuc&
&_nele,orb_norm,use_orbmods,complex_wf,detstart,detstop
implicit none
private
public stowfdet_read,stowfdet_setup,sto_orb_eval,read_stowf_params,wri&
&te_stowf_params,setup_stowf_params,finish_stowf_params,get_stowf_para&
&ms,put_stowf_params,get_stowfdet_orbmap,get_stowfdet_orbdesc,get_stow&
&fdet_ndesc
integer,parameter :: xyzzyaaaa1(6)=(/1,4,3,5,7,9/)
integer,parameter :: xyzzyaaab1(6)=(/1,1,2,5,10,17/)
integer,parameter :: xyzzyaaac1(25)=(/0,1,1,1,2,2,2,2,2,3,3,3,3,3,3,3,&
&4,4,4,4,4,4,4,4,4/)
real(dp),parameter :: xyzzyaaad1=746.0d0
real(dp),parameter :: xyzzyaaae1(0:10)=(/1.d0,1.d0,2.d0,6.d0,24.d0,120&
&.d0,720.d0,5040.d0,40320.d0,362990.d0,3629900.d0/)
integer xyzzyaaaf1,xyzzyaaag1,xyzzyaaah1,xyzzyaaai1,xyzzyaaaj1,xyzzyaa&
&ak1(2)
real(dp),allocatable :: xyzzyaaal1(:,:)
integer xyzzyaaam1(2)
integer xyzzyaaan1
integer xyzzyaaao1
integer xyzzyaaap1
integer xyzzyaaaq1
integer,allocatable :: xyzzyaaar1(:)
integer,allocatable :: xyzzyaaas1(:,:)
integer,allocatable :: xyzzyaaat1(:)
integer,allocatable :: xyzzyaaau1(:)
integer,allocatable :: xyzzyaaav1(:)
integer,allocatable :: xyzzyaaaw1(:)
integer,allocatable :: xyzzyaaax1(:)
integer,allocatable :: xyzzyaaay1(:)
integer,allocatable :: xyzzyaaaz1(:)
integer,allocatable :: xyzzyaaba1(:)
integer,allocatable :: xyzzyaabb1(:)
integer,allocatable :: xyzzyaabc1(:)
real(dp),allocatable :: xyzzyaabd1(:)
real(dp),allocatable :: xyzzyaabe1(:,:)
real(dp),allocatable :: xyzzyaabf1(:)
real(dp),allocatable :: xyzzyaabg1(:,:,:)
real(dp),allocatable :: xyzzyaabh1(:)
real(dp),allocatable :: xyzzyaabi1(:,:,:)
real(dp),allocatable :: xyzzyaabj1(:,:)
real(dp),allocatable :: xyzzyaabk1(:,:)
logical xyzzyaabl1,xyzzyaabm1,xyzzyaabn1,xyzzyaabo1,xyzzyaabp1,xyzzyaa&
&bq1
character(80) title,code
integer xyzzyaabr1
character(80) param_title
integer xyzzyaabs1
real(dp),allocatable :: xyzzyaabt1(:)
real(dp),allocatable :: xyzzyaabu1(:)
integer,allocatable :: xyzzyaabv1(:),xyzzyaabw1(:)
integer xyzzyaabx1,xyzzyaaby1
real(dp),allocatable :: xyzzyaabz1(:)
integer,allocatable ::  xyzzyaaca1(:)
integer,allocatable :: xyzzyaacb1(:),xyzzyaacc1(:)
logical xyzzyaacd1,xyzzyaace1
real(dp),allocatable :: xyzzyaacf1(:,:,:,:)
real(dp),allocatable :: xyzzyaacg1(:,:)
integer,parameter :: xyzzyaach1=0,xyzzyaaci1=0
logical,parameter :: xyzzyaacj1=.false.
contains
subroutine stowfdet_read(eionion)
implicit none
real(dp),intent(out) :: eionion
integer xyzzyaaaa2,xyzzyaaab2,xyzzyaaac2,c,xyzzyaaad2,xyzzyaaae2,xyzzy&
&aaaf2,xyzzyaaag2,xyzzyaaah2
logical xyzzyaaai2,xyzzyaaaj2,xyzzyaaak2
character(11) eigcheck
character(20) per_type
character(80) wline
character(6),parameter :: xyzzyaaal2='(8i10)'
character(13),parameter :: xyzzyaaam2='(3(1pe20.13))',xyzzyaaan2='(4(1&
&pe20.13))'
xyzzyaabp1=.false.
if(am_master)then
call open_units(xyzzyaaaa2,xyzzyaaab2)
if(xyzzyaaab2/=0)call errstop('STOWFDET_READ','Unable to find free io &
&unit.')
open(xyzzyaaaa2,file='stowfn.data',status='old',form='formatted',actio&
&n='read',err=1)
read(xyzzyaaaa2,'(a)',err=2,end=3)title
call skip(xyzzyaaaa2,4)
read(xyzzyaaaa2,'(a)',err=2,end=3)code
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,*,err=2,end=3)periodicity
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaai2
call skip(xyzzyaaaa2,1)
xyzzyaabn1=.not.xyzzyaaai2
xyzzyaaaj1=2
if(xyzzyaabn1)xyzzyaaaj1=1
read(xyzzyaaaa2,*,err=2,end=3)eionion
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaaf1
call skip(xyzzyaaaa2,4)
call wout()
call wout('Title : '//trim(title))
call wout()
call wout('Generated by                              :  '//trim(adjust&
&l(code)))
select case(periodicity)
case(0)
per_type='molecule'
case(1)
per_type='polymer'
case(2)
per_type='slab'
case(3)
per_type='solid'
case default
call errstop('STOWFDET_READ','Invalid periodicity of '//trim(i2s(perio&
&dicity))//' in stowfn.data.')
end select
call wout('Periodicity                               :  '//trim(i2s(pe&
&riodicity))//' ('//trim(per_type)//')')
if(isperiodic.neqv.periodicity>0)call errstop('STOWFDET_READ','Periodi&
&city in stowfn.data and PERIODIC input keyword not compatible.')
if(xyzzyaabn1)then
call wout('Spin restricted?                          :  Yes')
else
call wout('Spin restricted?                          :  No')
endif
if(isperiodic)then
call wout('Electrons per cell                        :  '//trim(i2s(xy&
&zzyaaaf1)))
else
call wout('Total number of electrons                 :  '//trim(i2s(xy&
&zzyaaaf1)))
endif
call wout()
read(xyzzyaaaa2,*,err=2,end=3)num_atoms
call skip(xyzzyaaaa2,1)
allocate(atom_pos(3,num_atoms),atomic_number(num_atoms),xyzzyaabd1(num&
&_atoms),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','atom_pos')
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)((atom_pos(xyzzyaaad2,xyzzyaaae&
&2),xyzzyaaad2=1,3),xyzzyaaae2=1,num_atoms)
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,xyzzyaaal2,err=2,end=3)(atomic_number(xyzzyaaad2),xyzz&
&yaaad2=1,num_atoms)
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,xyzzyaaan2,err=2,end=3)(xyzzyaabd1(xyzzyaaad2),xyzzyaa&
&ad2=1,num_atoms)
call skip(xyzzyaaaa2,1)
if(periodicity/=0)then
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)(pa1(xyzzyaaad2),xyzzyaaad2=1,3&
&)
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)(pa2(xyzzyaaad2),xyzzyaaad2=1,3&
&)
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)(pa3(xyzzyaaad2),xyzzyaaad2=1,3&
&)
pamat(1,1:3)=pa1(1:3)
pamat(2,1:3)=pa2(1:3)
pamat(3,1:3)=pa3(1:3)
call skip(xyzzyaaaa2,4)
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaag1
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaah1
call skip(xyzzyaaaa2,1)
xyzzyaaai1=xyzzyaaag1-xyzzyaaah1
allocate(xyzzyaaal1(3,xyzzyaaag1),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','kvec')
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)((xyzzyaaal1(xyzzyaaad2,xyzzyaa&
&ae2),xyzzyaaad2=1,3),xyzzyaaae2=1,xyzzyaaag1)
call skip(xyzzyaaaa2,4)
call wout('K space net information')
call wout()
call wout('No. k points                              :  '//trim(i2s(xy&
&zzyaaag1)))
call wout('No. real k points                         :  '//trim(i2s(xy&
&zzyaaah1)))
call wout('No. complex k points                      :  '//trim(i2s(xy&
&zzyaaai1)))
call wout('k-point coordinates:')
do xyzzyaaae2=1,xyzzyaaag1
if(xyzzyaaae2<10)then
write(wline,'(i1,3x,3(1pe20.13))')xyzzyaaae2,(xyzzyaaal1(xyzzyaaad2,xy&
&zzyaaae2),xyzzyaaad2=1,3)
elseif(xyzzyaaae2>=10.and.xyzzyaaae2<100)then
write(wline,'(i2,2x,3(1pe20.13))')xyzzyaaae2,(xyzzyaaal1(xyzzyaaad2,xy&
&zzyaaae2),xyzzyaaad2=1,3)
elseif(xyzzyaaae2>=100.and.xyzzyaaae2<1000)then
write(wline,'(i3,1x,3(1pe20.13))')xyzzyaaae2,(xyzzyaaal1(xyzzyaaad2,xy&
&zzyaaae2),xyzzyaaad2=1,3)
else
write(wline,'(i4,3(1pe20.13))')xyzzyaaae2,(xyzzyaaal1(xyzzyaaad2,xyzzy&
&aaae2),xyzzyaaad2=1,3)
endif
call wout(wline)
enddo
call wout()
else
xyzzyaaag1=1
xyzzyaaah1=1
xyzzyaaai1=0
allocate(xyzzyaaal1(3,1),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','kvec')
xyzzyaaal1(:,:)=0.d0
pamat(:,:)=0.d0
do xyzzyaaad2=1,3
pamat(xyzzyaaad2,xyzzyaaad2)=500.d0
enddo
pa1(1:3)=pamat(1,1:3)
pa2(1:3)=pamat(2,1:3)
pa3(1:3)=pamat(3,1:3)
call skip(xyzzyaaaa2,3)
endif
if(xyzzyaaah1+2*xyzzyaaai1/=npcells)call errstop('STOWFDET_READ','Numb&
&er of k points incompatible with NPCELL values in input.')
if(isperiodic)then
call wout('Basis set information (numbers per primitive cell)')
else
call wout('Basis set information')
endif
call wout()
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaan1
call skip(xyzzyaaaa2,1)
call wout('Number of STO centres                     :  '//trim(i2s(nu&
&m_atoms)))
if(xyzzyaaan1/=num_atoms)call errstop('STOWFDET_READ','Number of atoms&
& not equal to number of STO centres in stowfn.data.')
allocate(xyzzyaabe1(3,xyzzyaaan1),xyzzyaaar1(xyzzyaaan1+1),xyzzyaaas1(&
&xyzzyaaan1,1),xyzzyaaat1(xyzzyaaan1),xyzzyaaau1(xyzzyaaan1),stat=xyzz&
&yaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','centre_pos')
read(xyzzyaaaa2,xyzzyaaam2,err=2,end=3)((xyzzyaabe1(xyzzyaaad2,xyzzyaa&
&ae2),xyzzyaaad2=1,3),xyzzyaaae2=1,xyzzyaaan1)
call skip(xyzzyaaaa2,1)
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaap1
call skip(xyzzyaaaa2,1)
call wout('Number of shells                          :  '//trim(i2s(xy&
&zzyaaap1)))
read(xyzzyaaaa2,xyzzyaaal2,err=2,end=3)(xyzzyaaar1(xyzzyaaad2),xyzzyaa&
&ad2=1,xyzzyaaan1)
call skip(xyzzyaaaa2,1)
xyzzyaaar1(xyzzyaaan1+1)=xyzzyaaap1+1
if(xyzzyaaar1(1)/=1)call errstop('STOWFDET_READ','First shell on first&
& centre has to be 1.')
call wout('First shell on centre:')
call write_list_int(xyzzyaaan1+1,xyzzyaaar1(:),10,4,1)
xyzzyaaas1(:,1)=xyzzyaaar1(2:)-xyzzyaaar1(:xyzzyaaan1)
call wout('Number of shells on centre:')
call write_list_int(xyzzyaaan1,xyzzyaaas1(:,1),10,4,1)
if(any(xyzzyaaas1(:,1)<1))call errstop('STOWFDET_READ','Sequence of fi&
&rst shells on each centre is not ordered correctly.')
allocate(xyzzyaaav1(xyzzyaaap1),xyzzyaaaw1(xyzzyaaap1),xyzzyaabf1(xyzz&
&yaaap1),xyzzyaaax1(xyzzyaaap1),xyzzyaaay1(xyzzyaaap1),stat=xyzzyaaac2&
&)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','shell_type')
read(xyzzyaaaa2,xyzzyaaal2,err=2,end=3)(xyzzyaaav1(xyzzyaaad2),xyzzyaa&
&ad2=1,xyzzyaaap1)
call skip(xyzzyaaaa2,1)
if(xyzzyaacj1)then
call wout('Type of each shell:')
call write_list_int(xyzzyaaap1,xyzzyaaav1(:),10,4,1)
endif
read(xyzzyaaaa2,xyzzyaaal2,err=2,end=3)(xyzzyaaaw1(xyzzyaaad2),xyzzyaa&
&ad2=1,xyzzyaaap1)
call skip(xyzzyaaaa2,1)
if(xyzzyaacj1)then
call wout('Order of radial prefactor:')
call write_list_int(xyzzyaaap1,xyzzyaaaw1(:),10,4,1)
endif
read(xyzzyaaaa2,xyzzyaaan2,err=2,end=3)(xyzzyaabf1(xyzzyaaad2),xyzzyaa&
&ad2=1,xyzzyaaap1)
call skip(xyzzyaaaa2,1)
if(xyzzyaacj1)then
call wout('Zeta:')
do xyzzyaaad2=1,xyzzyaaap1,6
call wout('',xyzzyaabf1(xyzzyaaad2:xyzzyaaad2+5),rfmt='(es12.4)')
enddo
endif
read(xyzzyaaaa2,*,err=2,end=3)xyzzyaaaq1
call skip(xyzzyaaaa2,1)
call wout('Number of basis fns                       :  '//trim(i2s(xy&
&zzyaaaq1)))
xyzzyaaay1(:)=xyzzyaaaa1(xyzzyaaav1(:))
if(xyzzyaaaq1/=sum(xyzzyaaay1(:)))then
call wout('Computed number of basis fns              :  '//trim(i2s(su&
&m(xyzzyaaay1(:)))))
call errstop('STOWFDET_READ','Number of specified atomic orbitals inco&
&nsistent.')
endif
read(xyzzyaaaa2,*,err=2,end=3)(xyzzyaaam1(xyzzyaaad2),xyzzyaaad2=1,xyz&
&zyaaaj1)
if(xyzzyaaaj1==1)xyzzyaaam1(2)=xyzzyaaam1(1)
if(sum(xyzzyaaam1(:))<1.or.sum(xyzzyaaam1(:))>2*xyzzyaaaq1)call errsto&
&p('STOWFDET_READ','Number of molecular orbitals out of bounds.')
if(any(xyzzyaaav1(:)<1).or.any(abs(xyzzyaaav1(:))>6))call errstop('STO&
&WFDET_READ','Invalid shell type specified in basis (only s,sp,p,d,f,g&
& allowed')
call skip(xyzzyaaaa2,3)
xyzzyaabl1=any(wf_nd(:,:)>0).or.any(wf_np(:,:)>0).or.any(wf_nm(:,:)>0)
if(.not.modified_mdet)call read_mdet_wfn(xyzzyaaaa2)
do
read(xyzzyaaaa2,*,iostat=xyzzyaaab2)eigcheck
if(xyzzyaaab2/=0)call errstop('STOWFDET_READ','Problem finding eigenve&
&ctor coeffs.')
if(eigcheck=='EIGENVECTOR'.or.eigcheck=='ORBITAL')exit
enddo
call skip(xyzzyaaaa2,1)
xyzzyaaaj2=any(wf_nd(:,:)>0).or.any(wf_np(:,:)>0).or.any(wf_nm(:,:)>0)
xyzzyaaak2=.not.xyzzyaabl1.and.xyzzyaaaj2
xyzzyaabl1=xyzzyaabl1.or.xyzzyaaaj2
allocate(xyzzyaabg1(maxval(xyzzyaaam1),xyzzyaaaq1,xyzzyaaaj1),stat=xyz&
&zyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','coeff')
xyzzyaabg1=0.d0
do xyzzyaaaf2=1,xyzzyaaaj1
if(xyzzyaaam1(xyzzyaaaf2)>0)read(xyzzyaaaa2,xyzzyaaan2,err=2,end=3)((x&
&yzzyaabg1(xyzzyaaad2,xyzzyaaae2,xyzzyaaaf2),xyzzyaaae2=1,xyzzyaaaq1),&
&xyzzyaaad2=1,xyzzyaaam1(xyzzyaaaf2))
enddo
call skip(xyzzyaaaa2,1)
close(xyzzyaaaa2)
open_unit(xyzzyaaaa2)=.false.
endif
call mpi_bcast(xyzzyaaak2,1,mpi_logical,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting rebroadcast_data in stowfdet_read')
if(xyzzyaaak2)then
call mpi_bcast(ndet,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting ndet in stowfdet_read')
call mpi_bcast(detstart,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting detstart in stowfdet_read')
call mpi_bcast(detstop,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting detstop in stowfdet_read')
if(am_slave)then
deallocate(detcoef,wf_np,wf_nm,wf_nd)
allocate(detcoef(ndet),wf_np(ndet,2),wf_nm(ndet,2),wf_nd(ndet,2))
detcoef=1.d0
wf_np=0
wf_nm=0
wf_nd=0
endif
call mpi_bcast(detcoef,ndet,mpi_double_precision,0,mpi_comm_world,ierr&
&or)
call checkmpi(ierror,'Broadcasting detcoef in stowfdet_read')
call mpi_bcast(mods,1,mpi_logical,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting mods in stowfdet_read')
if(am_slave)then
allocate(wf_pm(4,mdet_max_mods,ndet,2),wf_d(4,mdet_max_mods,ndet,2))
wf_pm=0
wf_d=0
endif
call mpi_bcast(wf_nd,ndet*2,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting wf_nd in stowfdet_read')
call mpi_bcast(wf_np,ndet*2,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting wf_np in stowfdet_read')
call mpi_bcast(wf_nm,ndet*2,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting wf_nm in stowfdet_read')
call mpi_bcast(wf_pm,8*mdet_max_mods*ndet,mpi_integer,0,mpi_comm_world&
&,ierror)
call checkmpi(ierror,'Broadcasting wf_pm in stowfdet_read')
call mpi_bcast(wf_d,8*mdet_max_mods*ndet,mpi_integer,0,mpi_comm_world,&
&ierror)
call checkmpi(ierror,'Broadcasting wf_d in stowfdet_read')
endif
call mpi_bcast(periodicity,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting periodicity in stowfdet_read')
call mpi_bcast(xyzzyaabn1,1,mpi_logical,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting spin_restricted in stowfdet_read')
call mpi_bcast(xyzzyaaaj1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_spins in stowfdet_read')
call mpi_bcast(eionion,1,mpi_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting eionion in stowfdet_read')
call mpi_bcast(xyzzyaaaf1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_electrons in stowfdet_read')
call mpi_bcast(num_atoms,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_atoms in stowfdet_read')
call mpi_bcast(pa1,3,mpi_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting pa1 in stowfdet_read')
call mpi_bcast(pa2,3,mpi_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting pa2 in stowfdet_read')
call mpi_bcast(pa3,3,mpi_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting pa3 in stowfdet_read')
call mpi_bcast(pamat,9,mpi_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting pamat in stowfdet_read')
call mpi_bcast(xyzzyaaag1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_k in stowfdet_read')
call mpi_bcast(xyzzyaaah1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_real_k in stowfdet_read')
call mpi_bcast(xyzzyaaai1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_complex_k in stowfdet_read')
call mpi_bcast(xyzzyaaan1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_centres in stowfdet_read')
call mpi_bcast(xyzzyaaap1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_shells in stowfdet_read')
call mpi_bcast(xyzzyaaaq1,1,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_atorbs in stowfdet_read')
call mpi_bcast(xyzzyaaam1,2,mpi_integer,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting num_atorbs in stowfdet_read')
if(am_slave)then
xyzzyaaai1=xyzzyaaag1-xyzzyaaah1
allocate(atom_pos(3,num_atoms),atomic_number(num_atoms),xyzzyaabd1(num&
&_atoms),xyzzyaaal1(3,xyzzyaaag1),xyzzyaabe1(3,xyzzyaaan1),xyzzyaaar1(&
&xyzzyaaan1+1),xyzzyaaas1(xyzzyaaan1,1),xyzzyaaat1(xyzzyaaan1),xyzzyaa&
&au1(xyzzyaaan1),xyzzyaaav1(xyzzyaaap1),xyzzyaaaw1(xyzzyaaap1),xyzzyaa&
&bf1(xyzzyaaap1),xyzzyaaax1(xyzzyaaap1),xyzzyaaay1(xyzzyaaap1),xyzzyaa&
&bg1(maxval(xyzzyaaam1),xyzzyaaaq1,xyzzyaaaj1),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','atom_pos')
endif
call mpi_bcast(atom_pos,num_atoms*3,mpi_double_precision,0,mpi_comm_wo&
&rld,ierror)
call checkmpi(ierror,'Broadcasting atom_pos in stowfdet_read')
call mpi_bcast(atomic_number,num_atoms,mpi_integer,0,mpi_comm_world,ie&
&rror)
call checkmpi(ierror,'Broadcasting atomic_number in stowfdet_read')
call mpi_bcast(xyzzyaabd1,num_atoms,mpi_double_precision,0,mpi_comm_wo&
&rld,ierror)
call checkmpi(ierror,'Broadcasting valence_charge in stowfdet_read')
call mpi_bcast(xyzzyaaal1,3*xyzzyaaag1,mpi_double_precision,0,mpi_comm&
&_world,ierror)
call checkmpi(ierror,'Broadcasting kvec in stowfdet_read')
call mpi_bcast(xyzzyaabe1,xyzzyaaan1*3,mpi_double_precision,0,mpi_comm&
&_world,ierror)
call checkmpi(ierror,'Broadcasting centre_pos in stowfdet_read')
call mpi_bcast(xyzzyaaar1,xyzzyaaan1+1,mpi_integer,0,mpi_comm_world,ie&
&rror)
call checkmpi(ierror,'Broadcasting first_shell_on_centre in stowfdet_r&
&ead')
xyzzyaaas1(:,1)=xyzzyaaar1(2:)-xyzzyaaar1(:xyzzyaaan1)
call mpi_bcast(xyzzyaaav1,xyzzyaaap1,mpi_integer,0,mpi_comm_world,ierr&
&or)
call checkmpi(ierror,'Broadcasting shell_type in stowfdet_read')
call mpi_bcast(xyzzyaaaw1,xyzzyaaap1,mpi_integer,0,mpi_comm_world,ierr&
&or)
call checkmpi(ierror,'Broadcasting order_r_in_shell in stowfdet_read')
call mpi_bcast(xyzzyaabf1,xyzzyaaap1,mpi_double_precision,0,mpi_comm_w&
&orld,ierror)
call checkmpi(ierror,'Broadcasting zeta in stowfdet_read')
call mpi_bcast(xyzzyaabg1,maxval(xyzzyaaam1)*xyzzyaaaq1*xyzzyaaaj1,mpi&
&_double_precision,0,mpi_comm_world,ierror)
call checkmpi(ierror,'Broadcasting coeff in stowfdet_read')
allocate(xyzzyaaba1(xyzzyaaaq1),xyzzyaabb1(xyzzyaaaq1),xyzzyaabc1(xyzz&
&yaaaq1),xyzzyaabh1(xyzzyaaaq1),xyzzyaabi1(maxval(xyzzyaaam1),xyzzyaaa&
&q1,xyzzyaaaj1),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','centre_of_atorb')
if(cusp_correction)then
allocate(xyzzyaaaz1(xyzzyaaan1),xyzzyaabj1(xyzzyaaan1,xyzzyaaaq1),xyzz&
&yaabk1(xyzzyaaan1,xyzzyaaaq1),stat=xyzzyaaac2)
call check_alloc(xyzzyaaac2,'STOWFDET_READ','cusp_fixed_atorb')
endif
do c=1,xyzzyaaan1
xyzzyaaat1(c)=maxval(xyzzyaaaw1(xyzzyaaar1(c):xyzzyaaar1(c+1)-1))
xyzzyaaau1(c)=maxval(xyzzyaaav1(xyzzyaaar1(c):xyzzyaaar1(c+1)-1))
enddo
xyzzyaaao1=max(2,maxval(xyzzyaaat1(:)))
xyzzyaaax1(:)=xyzzyaaab1(xyzzyaaav1(:))
xyzzyaaay1(:)=xyzzyaaaa1(xyzzyaaav1(:))
xyzzyaaae2=1
c=1
do xyzzyaaag2=1,xyzzyaaap1
if(xyzzyaaag2>=xyzzyaaar1(c+1))c=c+1
xyzzyaaba1(xyzzyaaae2:xyzzyaaae2+xyzzyaaay1(xyzzyaaag2)-1)=c
xyzzyaabb1(xyzzyaaae2:xyzzyaaae2+xyzzyaaay1(xyzzyaaag2)-1)=xyzzyaaag2
xyzzyaabc1(xyzzyaaae2:xyzzyaaae2+xyzzyaaay1(xyzzyaaag2)-1)=xyzzyaaaw1(&
&xyzzyaaag2)
xyzzyaaae2=xyzzyaaae2+xyzzyaaay1(xyzzyaaag2)
enddo
if(am_master.and.xyzzyaacj1)then
call wout('centre_of_atorb  :')
call write_list_int(xyzzyaaaq1,xyzzyaaba1(:),10,4,1)
call wout('shell_of_atorb   :')
call write_list_int(xyzzyaaaq1,xyzzyaabb1(:),10,4,1)
call wout('order_r_of_atorb :')
call write_list_int(xyzzyaaaq1,xyzzyaabc1(:),10,4,1)
call wout()
endif
if(cusp_correction)then
xyzzyaaaz1(:)=-1
do xyzzyaaah2=1,xyzzyaaaq1
if(xyzzyaaav1(xyzzyaabb1(xyzzyaaah2))==1)then
if(xyzzyaabc1(xyzzyaaah2)==0)then
c=xyzzyaaba1(xyzzyaaah2)
if(xyzzyaaaz1(c)==-1)then
xyzzyaaaz1(c)=xyzzyaaah2
elseif(xyzzyaabf1(xyzzyaabb1(xyzzyaaah2))>xyzzyaabf1(xyzzyaabb1(xyzzya&
&aaz1(c))))then
xyzzyaaaz1(c)=xyzzyaaah2
endif
endif
endif
enddo
do c=1,xyzzyaaan1
if(xyzzyaaaz1(c)==-1)then
call errstop_master('STOWFDET_READ','Found no orbital on centre '//tri&
&m(i2s(c))//' that could be used to enforce cusp constraint.')
elseif(xyzzyaabf1(xyzzyaabb1(xyzzyaaaz1(c)))<=xyzzyaabd1(c))then
call errstop_master('STOWFDET_READ','Largest zeta on centre #'//trim(i&
&2s(c))//' needs to be larger than Z to enforce cusp constraint.')
elseif(xyzzyaabf1(xyzzyaabb1(xyzzyaaaz1(c)))<xyzzyaabd1(c)+1.d0)then
call errwarn('STOWFDET_READ','Largest zeta on centre #'//trim(i2s(c))/&
&/' is smaller than Z+1. Enforcing the constraint may have long-ranged&
& effects on the wave function.')
endif
enddo
endif
if(am_master.and.xyzzyaacj1)then
call wout('orbitals fixed by cusp constraint:')
call write_list_int(xyzzyaaaq1,xyzzyaaaz1(:),10,4,1)
endif
eionion=eionion*dble(num_atoms)
if(use_orbmods)call read_stowf_params
return
1 call errstop('STOWFN_READ','Cannot open stowfn.data.')
2 call errstop('STOWFN_READ','Problem reading stowfn.data.')
3 call errstop('STOWFN_READ','Premature EOF reading stowfn.data.')
end subroutine stowfdet_read
subroutine stowfdet_setup
implicit none
integer xyzzyaaaa3
xyzzyaabq1=.true.
if(am_master)then
call wout('STO data setup')
call wout('==============')
endif
call xyzzyaack1
if(cusp_correction)then
if(xyzzyaabq1)call xyzzyaacm1(verbose=xyzzyaacj1)
call xyzzyaacn1(verbose=xyzzyaacj1)
endif
xyzzyaaak1(1:2)=(nuc_nele(1:2)+wf_nm(1,1:2)-wf_np(1,1:2))
xyzzyaabm1=(xyzzyaaak1(1)/=xyzzyaaak1(2))
xyzzyaabo1=(.not.xyzzyaabn1.or.xyzzyaabm1)
do xyzzyaaaa3=2,ndet
if(nuc_nele(1)+wf_nm(xyzzyaaaa3,1)-wf_np(xyzzyaaaa3,1)/=xyzzyaaak1(1).&
&or.nuc_nele(2)+wf_nm(xyzzyaaaa3,2)-wf_np(xyzzyaaaa3,2)/=xyzzyaaak1(2)&
&)then
call errstop('STOWFDET_SETUP','All same spin dets must have same numbe&
&r of electrons.')
endif
enddo
xyzzyaaaa3=xyzzyaaaf1*npcells
xyzzyaaaa3=xyzzyaaaa3-wf_nm(1,1)+wf_np(1,1)-wf_nm(1,2)+wf_np(1,2)
if(xyzzyaaaa3/=(nuc_nele(1)+nuc_nele(2)))then
if(am_master)then
call wout()
call wordwrap('Number of up/down electrons plus specified excitations &
&not compatible with stowfn.data.')
call wout()
call wout('Perhaps you have wrong values of NEU and NED in the input f&
&ile?')
call wout()
call wout('npcells : '//trim(i2s(npcells)))
call wout('num_electrons*npcells-excitations : '//trim(i2s(xyzzyaaaa3)&
&))
call wout('neu : '//trim(i2s(nuc_nele(1)))//' ned : '//trim(i2s(nuc_ne&
&le(2))))
call wout()
endif
call errstop_master('STOWFDET_SETUP','Stopping.')
endif
if(am_master)then
call wout('STO data setup complete.')
call wout()
endif
xyzzyaabp1=.true.
end subroutine stowfdet_setup
subroutine xyzzyaack1
implicit none
integer xyzzyaaaa4,xyzzyaaab4,xyzzyaaac4,xyzzyaaad4,xyzzyaaae4,xyzzyaa&
&af4,xyzzyaaag4,xyzzyaaah4
real(dp) xyzzyaaai4(25),xyzzyaaaj4,xyzzyaaak4(xyzzyaaaq1),xyzzyaaal4(x&
&yzzyaaan1,xyzzyaaan1)
real(dp),allocatable :: xyzzyaaam4(:,:),xyzzyaaan4(:,:,:),xyzzyaaao4(:&
&,:)
logical xyzzyaaap4
xyzzyaaai4(1)=0.5d0*sqrt(1.d0/pi)
xyzzyaaai4(2)=0.5d0*sqrt(3.d0/pi)
xyzzyaaai4(3)=0.5d0*sqrt(3.d0/pi)
xyzzyaaai4(4)=0.5d0*sqrt(3.d0/pi)
xyzzyaaai4(5)=0.5d0*sqrt(15.d0/pi)
xyzzyaaai4(6)=0.5d0*sqrt(15.d0/pi)
xyzzyaaai4(7)=0.5d0*sqrt(15.d0/pi)
xyzzyaaai4(8)=0.25d0*sqrt(5.d0/pi)
xyzzyaaai4(9)=0.25d0*sqrt(15.d0/pi)
xyzzyaaai4(10)=0.25d0*sqrt(7.d0/pi)
xyzzyaaai4(11)=0.25d0*sqrt(17.5d0/pi)
xyzzyaaai4(12)=0.25d0*sqrt(17.5d0/pi)
xyzzyaaai4(13)=0.25d0*sqrt(105.d0/pi)
xyzzyaaai4(14)=0.5d0*sqrt(105.d0/pi)
xyzzyaaai4(15)=0.25d0*sqrt(10.5d0/pi)
xyzzyaaai4(16)=0.25d0*sqrt(10.5d0/pi)
xyzzyaaai4(17)=0.1875d0*sqrt(1.d0/pi)
xyzzyaaai4(18)=0.75d0*sqrt(2.5d0/pi)
xyzzyaaai4(19)=0.75d0*sqrt(2.5d0/pi)
xyzzyaaai4(20)=0.375d0*sqrt(5.d0/pi)
xyzzyaaai4(21)=0.75d0*sqrt(5.d0/pi)
xyzzyaaai4(22)=0.75d0*sqrt(17.5d0/pi)
xyzzyaaai4(23)=0.75d0*sqrt(17.5d0/pi)
xyzzyaaai4(24)=0.1875d0*sqrt(35.d0/pi)
xyzzyaaai4(25)=0.75d0*sqrt(35.d0/pi)
xyzzyaaag4=maxval(xyzzyaaam1)
allocate(xyzzyaaam4(xyzzyaaag4,real1_complex2),xyzzyaaan4(3,xyzzyaaag4&
&,real1_complex2),xyzzyaaao4(xyzzyaaag4,real1_complex2),stat=xyzzyaaah&
&4)
call check_alloc(xyzzyaaah4,'STOWFDET_SETUP_ZETA','valt,gradt,lapt')
xyzzyaaad4=0
do xyzzyaaaa4=1,xyzzyaaan1
do xyzzyaaab4=xyzzyaaar1(xyzzyaaaa4),xyzzyaaar1(xyzzyaaaa4+1)-1
do xyzzyaaac4=xyzzyaaax1(xyzzyaaab4),xyzzyaaax1(xyzzyaaab4)+xyzzyaaay1&
&(xyzzyaaab4)-1
xyzzyaaad4=xyzzyaaad4+1
xyzzyaaae4=xyzzyaaac1(xyzzyaaac4)+xyzzyaaaw1(xyzzyaaab4)+1
xyzzyaabh1(xyzzyaaad4)=xyzzyaaai4(xyzzyaaac4)*(2.d0*xyzzyaabf1(xyzzyaa&
&ab4))**xyzzyaaae4*sqrt(2.d0*xyzzyaabf1(xyzzyaaab4)/xyzzyaaae1(2*xyzzy&
&aaae4))
enddo
enddo
enddo
xyzzyaaaj4=0.d0
do xyzzyaaaf4=2,nemax
xyzzyaaaj4=xyzzyaaaj4+log(dble(xyzzyaaaf4))
enddo
xyzzyaaaj4=exp(-xyzzyaaaj4/(2.d0*dble(nemax)))
xyzzyaaaj4=xyzzyaaaj4*orb_norm
do xyzzyaaaf4=1,xyzzyaaaq1
xyzzyaabi1(:,xyzzyaaaf4,:)=xyzzyaabg1(:,xyzzyaaaf4,:)*xyzzyaabh1(xyzzy&
&aaaf4)
enddo
if(cusp_correction)then
xyzzyaabj1=0.d0
do xyzzyaaaa4=1,xyzzyaaan1
call xyzzyaacl1(xyzzyaabe1(:,xyzzyaaaa4),xyzzyaaak4)
do xyzzyaaad4=1,xyzzyaaaq1
if(xyzzyaaba1(xyzzyaaad4)==xyzzyaaaa4)then
if(xyzzyaaav1(xyzzyaabb1(xyzzyaaad4))==1)then
if(xyzzyaabc1(xyzzyaaad4)==0)then
xyzzyaabj1(xyzzyaaaa4,xyzzyaaad4)=xyzzyaabh1(xyzzyaaad4)*(xyzzyaabd1(x&
&yzzyaaaa4)-xyzzyaabf1(xyzzyaabb1(xyzzyaaad4)))
elseif(xyzzyaabc1(xyzzyaaad4)==1)then
xyzzyaabj1(xyzzyaaaa4,xyzzyaaad4)=xyzzyaabh1(xyzzyaaad4)
endif
endif
else
xyzzyaabj1(xyzzyaaaa4,xyzzyaaad4)=xyzzyaabd1(xyzzyaaaa4)*xyzzyaaak4(xy&
&zzyaaad4)
endif
enddo
if(am_master.and.xyzzyaacj1)then
call wout('atorb_value vector for centre '//trim(i2s(xyzzyaaaa4))//' c&
&omputed as:')
call wout('',xyzzyaaak4)
call wout()
call wout('Cusp constraint vector for centre '//trim(i2s(xyzzyaaaa4))/&
&/' computed as:')
call wout('',xyzzyaabj1(xyzzyaaaa4,:))
call wout()
endif
enddo
xyzzyaabk1=xyzzyaabj1
xyzzyaabk1(:,xyzzyaaaz1(:))=0.d0
xyzzyaaal4=xyzzyaabj1(:,xyzzyaaaz1(:))
xyzzyaaal4=inverse(xyzzyaaan1,xyzzyaaan1,xyzzyaaal4(1,1),xyzzyaaap4)
xyzzyaabk1=-matmul(xyzzyaaal4,xyzzyaabk1)
endif
deallocate(xyzzyaaam4,xyzzyaaan4,xyzzyaaao4)
end subroutine xyzzyaack1
subroutine xyzzyaacl1(rvec,atorb_value)
implicit none
real(dp),intent(in) :: rvec(3)
real(dp),intent(inout) :: atorb_value(xyzzyaaaq1)
integer xyzzyaaaa5,xyzzyaaab5,xyzzyaaac5,xyzzyaaad5,xyzzyaaae5,xyzzyaa&
&af5,xyzzyaaag5,xyzzyaaah5,xyzzyaaai5,xyzzyaaaj5
real(dp) xyzzyaaak5,xyzzyaaal5,xyzzyaaam5,xyzzyaaan5,xyzzyaaao5,xyzzya&
&aap5,xyzzyaaaq5,xyzzyaaar5,xyzzyaaas5,xyzzyaaat5,xyzzyaaau5,xyzzyaaav&
&5,xyzzyaaaw5,xyzzyaaax5,xyzzyaaay5,xyzzyaaaz5,xyzzyaaba5,xyzzyaabb5,x&
&yzzyaabc5,xyzzyaabd5,xyzzyaabe5,xyzzyaabf5(-3:xyzzyaaao1),xyzzyaabg5(&
&25),xyzzyaabh5(9),xyzzyaabi5(9)
atorb_value(:)=0.d0
xyzzyaaah5=0
do xyzzyaaaf5=1,xyzzyaaan1
xyzzyaaak5=rvec(1)-xyzzyaabe1(1,xyzzyaaaf5)
xyzzyaaal5=rvec(2)-xyzzyaabe1(2,xyzzyaaaf5)
xyzzyaaam5=rvec(3)-xyzzyaabe1(3,xyzzyaaaf5)
if(which_ion_displaced==xyzzyaaaf5)then
xyzzyaaak5=xyzzyaaak5-ion_displacement(1)
xyzzyaaal5=xyzzyaaal5-ion_displacement(2)
xyzzyaaam5=xyzzyaaal5-ion_displacement(3)
endif
xyzzyaaan5=xyzzyaaak5*xyzzyaaak5
xyzzyaaao5=xyzzyaaal5*xyzzyaaal5
xyzzyaaap5=xyzzyaaam5*xyzzyaaam5
xyzzyaabf5(2)=xyzzyaaan5+xyzzyaaao5+xyzzyaaap5
xyzzyaabf5(1)=sqrt(xyzzyaabf5(2))
do xyzzyaaaa5=3,xyzzyaaat1(xyzzyaaaf5)
xyzzyaabf5(xyzzyaaaa5)=xyzzyaabf5(xyzzyaaaa5-1)*xyzzyaabf5(1)
enddo
xyzzyaabg5(1)=1.d0
xyzzyaabg5(2)=xyzzyaaak5
xyzzyaabg5(3)=xyzzyaaal5
xyzzyaabg5(4)=xyzzyaaam5
if(xyzzyaaau1(xyzzyaaaf5)>=4)then
xyzzyaaat5=xyzzyaaak5*xyzzyaaal5
xyzzyaaau5=xyzzyaaal5*xyzzyaaam5
xyzzyaaav5=xyzzyaaam5*xyzzyaaak5
xyzzyaabg5(5)=xyzzyaaat5
xyzzyaabg5(6)=xyzzyaaau5
xyzzyaabg5(7)=xyzzyaaav5
xyzzyaabg5(8)=(3*xyzzyaaap5-xyzzyaabf5(2))
xyzzyaabg5(9)=(xyzzyaaan5-xyzzyaaao5)
if(xyzzyaaau1(xyzzyaaaf5)>=5)then
xyzzyaaaw5=xyzzyaaan5-3*xyzzyaaao5
xyzzyaaax5=3*xyzzyaaan5-xyzzyaaao5
xyzzyaaaz5=5*xyzzyaaap5
xyzzyaabe5=xyzzyaaaz5-xyzzyaabf5(2)
xyzzyaabg5(10)=(xyzzyaaaz5-3*xyzzyaabf5(2))*xyzzyaaam5
xyzzyaabg5(11)=xyzzyaabe5*xyzzyaaak5
xyzzyaabg5(12)=xyzzyaabe5*xyzzyaaal5
xyzzyaabg5(13)=(xyzzyaaan5-xyzzyaaao5)*xyzzyaaam5
xyzzyaabg5(14)=xyzzyaaat5*xyzzyaaam5
xyzzyaabg5(15)=xyzzyaaaw5*xyzzyaaak5
xyzzyaabg5(16)=xyzzyaaax5*xyzzyaaal5
if(xyzzyaaau1(xyzzyaaaf5)>=6)then
xyzzyaaay5=xyzzyaaan5-xyzzyaaao5
xyzzyaaba5=7*xyzzyaaap5
xyzzyaabb5=3*xyzzyaabf5(2)
xyzzyaabc5=xyzzyaaba5-xyzzyaabf5(2)
xyzzyaabd5=xyzzyaaba5-xyzzyaabb5
xyzzyaabg5(17)=xyzzyaaaz5*(xyzzyaabd5)-(xyzzyaaaz5-xyzzyaabf5(2))*xyzz&
&yaabb5
xyzzyaabg5(18)=xyzzyaaav5*(xyzzyaabd5)
xyzzyaabg5(19)=xyzzyaaau5*(xyzzyaabd5)
xyzzyaabg5(20)=(xyzzyaaay5)*(xyzzyaabc5)
xyzzyaabg5(21)=xyzzyaaat5*(xyzzyaabc5)
xyzzyaabg5(22)=xyzzyaaav5*(xyzzyaaaw5)
xyzzyaabg5(23)=xyzzyaaau5*(xyzzyaaax5)
xyzzyaabg5(24)=xyzzyaaan5*(xyzzyaaaw5)-xyzzyaaao5*(xyzzyaaax5)
xyzzyaabg5(25)=xyzzyaaat5*(xyzzyaaay5)
endif
endif
endif
xyzzyaaas5=0.d0
xyzzyaaaj5=0
do xyzzyaaag5=xyzzyaaar1(xyzzyaaaf5),xyzzyaaar1(xyzzyaaaf5+1)-1
xyzzyaaaq5=xyzzyaabf1(xyzzyaaag5)*xyzzyaabf5(1)
if(xyzzyaaaq5>xyzzyaaad1)then
xyzzyaaah5=xyzzyaaah5+xyzzyaaay1(xyzzyaaag5)
cycle
endif
if(xyzzyaabf1(xyzzyaaag5)/=xyzzyaaas5)then
xyzzyaaar5=exp(-xyzzyaaaq5)
endif
if(xyzzyaaaj5/=xyzzyaaav1(xyzzyaaag5).or.xyzzyaabf1(xyzzyaaag5)/=xyzzy&
&aaas5)then
xyzzyaaad5=xyzzyaaax1(xyzzyaaag5)
xyzzyaaai5=xyzzyaaay1(xyzzyaaag5)
xyzzyaaae5=xyzzyaaad5+xyzzyaaai5-1
xyzzyaabh5(1:xyzzyaaai5)=xyzzyaabg5(xyzzyaaad5:xyzzyaaae5)*xyzzyaaar5
endif
xyzzyaaas5=xyzzyaabf1(xyzzyaaag5)
xyzzyaaaj5=xyzzyaaav1(xyzzyaaag5)
xyzzyaaac5=xyzzyaaaw1(xyzzyaaag5)
if(xyzzyaaac5==0)then
do xyzzyaaab5=1,xyzzyaaai5
xyzzyaaah5=xyzzyaaah5+1
atorb_value(xyzzyaaah5)=xyzzyaabh1(xyzzyaaah5)*xyzzyaabh5(xyzzyaaab5)
enddo
else
xyzzyaabi5(:xyzzyaaai5)=xyzzyaabf5(xyzzyaaac5)*xyzzyaabh5(:xyzzyaaai5)
do xyzzyaaab5=1,xyzzyaaai5
xyzzyaaah5=xyzzyaaah5+1
atorb_value(xyzzyaaah5)=xyzzyaabh1(xyzzyaaah5)*xyzzyaabi5(xyzzyaaab5)
enddo
endif
enddo
enddo
end subroutine xyzzyaacl1
subroutine xyzzyaacm1(verbose)
logical,intent(in),optional :: verbose
integer xyzzyaaaa6,xyzzyaaab6,xyzzyaaac6
real(dp) xyzzyaaad6
logical xyzzyaaae6
character(80) tmpr
xyzzyaaae6=.false.
if(present(verbose))xyzzyaaae6=verbose
if(am_master)then
do xyzzyaaaa6=1,xyzzyaaan1
do xyzzyaaac6=1,xyzzyaaaj1
do xyzzyaaab6=1,xyzzyaaam1(xyzzyaaac6)
xyzzyaaad6=abs(sum(xyzzyaabj1(xyzzyaaaa6,:)*xyzzyaabg1(xyzzyaaab6,:,xy&
&zzyaaac6)))
if(xyzzyaaad6>1.d-8)then
tmpr=r2s(xyzzyaaad6,'(es12.4)')
call errwarn_silent('STOWFDET_CUSP_CHECK','Cusp constraint for centre=&
&'//trim(i2s(xyzzyaaaa6))//', molorb='//trim(i2s(xyzzyaaab6))//',spin=&
&'//trim(i2s(xyzzyaaac6))//' violated by '//trim(tmpr))
elseif(xyzzyaaae6)then
tmpr=r2s(xyzzyaaad6,'(es12.4)')
call wout('Cusp constraint for centre='//trim(i2s(xyzzyaaaa6))//', mol&
&orb='//trim(i2s(xyzzyaaab6))//', spin='//trim(i2s(xyzzyaaac6))//' cor&
&rect, difference='//trim(tmpr))
endif
enddo
enddo
enddo
endif
end subroutine xyzzyaacm1
subroutine xyzzyaacn1(verbose)
logical,intent(in),optional :: verbose
integer xyzzyaaaa7,xyzzyaaab7,xyzzyaaac7
logical xyzzyaaad7
xyzzyaaad7=.false.
if(present(verbose))xyzzyaaad7=verbose
do xyzzyaaab7=1,xyzzyaaaj1
do xyzzyaaaa7=1,xyzzyaaam1(xyzzyaaab7)
if(am_master.and.xyzzyaaad7)then
call wout('spin='//trim(i2s(xyzzyaaab7))//' MO#'//trim(i2s(xyzzyaaaa7)&
&))
call wout('  uncorrected: ',xyzzyaabg1(xyzzyaaaa7,xyzzyaaaz1(:),xyzzya&
&aab7))
endif
xyzzyaabg1(xyzzyaaaa7,xyzzyaaaz1(:),xyzzyaaab7)=matmul(xyzzyaabk1,xyzz&
&yaabg1(xyzzyaaaa7,:,xyzzyaaab7))
if(am_master.and.xyzzyaaad7)then
call wout('  corrected: ',xyzzyaabg1(xyzzyaaaa7,xyzzyaaaz1(:),xyzzyaaa&
&b7))
endif
enddo
enddo
call xyzzyaacm1(verbose)
do xyzzyaaac7=1,xyzzyaaaq1
xyzzyaabi1(:,xyzzyaaac7,:)=xyzzyaabg1(:,xyzzyaaac7,:)*xyzzyaabh1(xyzzy&
&aaac7)
enddo
end subroutine xyzzyaacn1
subroutine sto_orb_eval(rvec,jspin,norb,orbmask,val,fsd,orbval,orbgrad&
&,orblap,orbsderivs)
implicit none
integer,intent(in) :: jspin,norb
real(dp),intent(in) :: rvec(3)
real(dp),intent(inout) :: orbval(norb,real1_complex2),orbgrad(3,norb,r&
&eal1_complex2),orblap(norb,real1_complex2)
real(dp),intent(inout),optional :: orbsderivs(6,norb,real1_complex2)
logical,intent(in) :: val,fsd,orbmask(norb)
integer xyzzyaaaa8,xyzzyaaab8,xyzzyaaac8,xyzzyaaad8,xyzzyaaae8,xyzzyaa&
&af8,xyzzyaaag8,xyzzyaaah8,xyzzyaaai8,xyzzyaaaj8,xyzzyaaak8,xyzzyaaal8
real(dp) xyzzyaaam8,xyzzyaaan8,xyzzyaaao8,xyzzyaaap8,xyzzyaaaq8,xyzzya&
&aar8,xyzzyaaas8,xyzzyaaat8,xyzzyaaau8,xyzzyaaav8,xyzzyaaaw8,xyzzyaaax&
&8,xyzzyaaay8,xyzzyaaaz8,xyzzyaaba8,xyzzyaabb8,xyzzyaabc8,xyzzyaabd8,x&
&yzzyaabe8,xyzzyaabf8,xyzzyaabg8,xyzzyaabh8,xyzzyaabi8,xyzzyaabj8,xyzz&
&yaabk8(-3:xyzzyaaao1),xyzzyaabl8(25),xyzzyaabm8(3,25),xyzzyaabn8(6,25&
&),xyzzyaabo8(9),xyzzyaabp8(3,9),xyzzyaabq8(9),xyzzyaabr8(6,9),xyzzyaa&
&bs8(9),xyzzyaabt8(3,9),xyzzyaabu8(9),xyzzyaabv8(6,9)
xyzzyaaaj8=xyzzyaaak1(jspin)
xyzzyaaak8=jspin
if(.not.xyzzyaabo1)xyzzyaaak8=1
if(val)then
orbval(1:xyzzyaaaj8,:)=0.d0
endif
if(fsd)then
orbgrad(:,1:xyzzyaaaj8,:)=0.d0
orblap(1:xyzzyaaaj8,:)=0.d0
if(present(orbsderivs))orbsderivs(:,1:xyzzyaaaj8,:)=0.d0
endif
xyzzyaaah8=0
do xyzzyaaaf8=1,xyzzyaaan1
xyzzyaaam8=rvec(1)-xyzzyaabe1(1,xyzzyaaaf8)
xyzzyaaan8=rvec(2)-xyzzyaabe1(2,xyzzyaaaf8)
xyzzyaaao8=rvec(3)-xyzzyaabe1(3,xyzzyaaaf8)
if(which_ion_displaced==xyzzyaaaf8)then
xyzzyaaam8=xyzzyaaam8-ion_displacement(1)
xyzzyaaan8=xyzzyaaan8-ion_displacement(2)
xyzzyaaao8=xyzzyaaan8-ion_displacement(3)
endif
xyzzyaaap8=xyzzyaaam8*xyzzyaaam8
xyzzyaaaq8=xyzzyaaan8*xyzzyaaan8
xyzzyaaar8=xyzzyaaao8*xyzzyaaao8
xyzzyaabk8(2)=xyzzyaaap8+xyzzyaaaq8+xyzzyaaar8
xyzzyaabk8(1)=sqrt(xyzzyaabk8(2))
do xyzzyaaaa8=3,xyzzyaaat1(xyzzyaaaf8)
xyzzyaabk8(xyzzyaaaa8)=xyzzyaabk8(xyzzyaaaa8-1)*xyzzyaabk8(1)
enddo
if(fsd)then
xyzzyaabk8(0)=1.d0
if(xyzzyaabk8(1)==0.d0)then
xyzzyaabk8(-1)=0.d0
else
xyzzyaabk8(-1)=1.d0/xyzzyaabk8(1)
endif
xyzzyaaay8=xyzzyaaam8*xyzzyaabk8(-1)
xyzzyaaaz8=xyzzyaaan8*xyzzyaabk8(-1)
xyzzyaaba8=xyzzyaaao8*xyzzyaabk8(-1)
xyzzyaabk8(-2)=xyzzyaabk8(-1)*xyzzyaabk8(-1)
xyzzyaabk8(-3)=xyzzyaabk8(-2)*xyzzyaabk8(-1)
endif
xyzzyaabl8(1)=1.d0
xyzzyaabl8(2)=xyzzyaaam8
xyzzyaabl8(3)=xyzzyaaan8
xyzzyaabl8(4)=xyzzyaaao8
if(fsd)then
xyzzyaabm8(:,1)=(/ 0.d0,0.d0,0.d0 /)
xyzzyaabm8(:,2)=(/ 1.d0,0.d0,0.d0 /)
xyzzyaabm8(:,3)=(/ 0.d0,1.d0,0.d0 /)
xyzzyaabm8(:,4)=(/ 0.d0,0.d0,1.d0 /)
if(present(orbsderivs))then
xyzzyaabn8(:,1)=(/ 0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 /)
xyzzyaabn8(:,2)=(/ 0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 /)
xyzzyaabn8(:,3)=(/ 0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 /)
xyzzyaabn8(:,4)=(/ 0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 /)
endif
endif
if(xyzzyaaau1(xyzzyaaaf8)>=4)then
xyzzyaaav8=xyzzyaaam8*xyzzyaaan8
xyzzyaaaw8=xyzzyaaan8*xyzzyaaao8
xyzzyaaax8=xyzzyaaao8*xyzzyaaam8
xyzzyaabl8(5)=xyzzyaaav8
xyzzyaabl8(6)=xyzzyaaaw8
xyzzyaabl8(7)=xyzzyaaax8
xyzzyaabl8(8)=(3*xyzzyaaar8-xyzzyaabk8(2))
xyzzyaabl8(9)=(xyzzyaaap8-xyzzyaaaq8)
if(fsd)then
xyzzyaabm8(:,5)=(/xyzzyaaan8,xyzzyaaam8,0.d0/)
xyzzyaabm8(:,6)=(/0.d0,xyzzyaaao8,xyzzyaaan8/)
xyzzyaabm8(:,7)=(/xyzzyaaao8,0.d0,xyzzyaaam8/)
xyzzyaabm8(:,8)=(/-2*xyzzyaaam8,-2*xyzzyaaan8,4*xyzzyaaao8/)
xyzzyaabm8(:,9)=(/2*xyzzyaaam8,-2*xyzzyaaan8,0.d0/)
if(present(orbsderivs))then
xyzzyaabn8(:,5)=(/ 0.d0,0.d0,0.d0,1.d0,0.d0,0.d0 /)
xyzzyaabn8(:,6)=(/ 0.d0,0.d0,0.d0,0.d0,0.d0,1.d0 /)
xyzzyaabn8(:,7)=(/ 0.d0,0.d0,0.d0,0.d0,1.d0,0.d0 /)
xyzzyaabn8(:,8)=(/ -2.d0,-2.d0,4.d0,0.d0,0.d0,0.d0 /)
xyzzyaabn8(:,9)=(/ 2.d0,-2.d0,0.d0,0.d0,0.d0,0.d0 /)
endif
endif
if(xyzzyaaau1(xyzzyaaaf8)>=5)then
xyzzyaabb8=xyzzyaaap8-3*xyzzyaaaq8
xyzzyaabc8=3*xyzzyaaap8-xyzzyaaaq8
xyzzyaabe8=5*xyzzyaaar8
xyzzyaabj8=xyzzyaabe8-xyzzyaabk8(2)
xyzzyaabl8(10)=(xyzzyaabe8-3*xyzzyaabk8(2))*xyzzyaaao8
xyzzyaabl8(11)=xyzzyaabj8*xyzzyaaam8
xyzzyaabl8(12)=xyzzyaabj8*xyzzyaaan8
xyzzyaabl8(13)=(xyzzyaaap8-xyzzyaaaq8)*xyzzyaaao8
xyzzyaabl8(14)=xyzzyaaav8*xyzzyaaao8
xyzzyaabl8(15)=xyzzyaabb8*xyzzyaaam8
xyzzyaabl8(16)=xyzzyaabc8*xyzzyaaan8
if(fsd)then
xyzzyaabm8(:,10)=(/-6*xyzzyaaax8        ,-6*xyzzyaaaw8       ,6*xyzzya&
&aar8-3*(xyzzyaaap8+xyzzyaaaq8)/)
xyzzyaabm8(:,11)=(/ 4*xyzzyaaar8-xyzzyaaaq8-3*xyzzyaaap8,-2*xyzzyaaav8&
&       ,8*xyzzyaaax8/)
xyzzyaabm8(:,12)=(/-2*xyzzyaaav8        ,4*xyzzyaaar8-xyzzyaaap8-3*xyz&
&zyaaaq8,8*xyzzyaaaw8/)
xyzzyaabm8(:,13)=(/ 2*xyzzyaaax8        ,-2*xyzzyaaaw8       ,xyzzyaaa&
&p8-xyzzyaaaq8/)
xyzzyaabm8(:,14)=(/ xyzzyaaaw8          ,xyzzyaaax8          ,xyzzyaaa&
&v8/)
xyzzyaabm8(:,15)=(/3*xyzzyaaap8-3*xyzzyaaaq8    ,-6*xyzzyaaav8       ,&
&0.d0/)
xyzzyaabm8(:,16)=(/6*xyzzyaaav8         ,3*xyzzyaaap8-3*xyzzyaaaq8   ,&
&0.d0/)
if(present(orbsderivs))then
xyzzyaabn8(:,10)=(/ -6*xyzzyaaao8,-6*xyzzyaaao8,12*xyzzyaaao8,0.d0,-6*&
&xyzzyaaam8,-6*xyzzyaaan8 /)
xyzzyaabn8(:,11)=(/ -6*xyzzyaaam8,-2*xyzzyaaam8, 8*xyzzyaaam8,-2*xyzzy&
&aaan8, 8*xyzzyaaao8,0.d0 /)
xyzzyaabn8(:,12)=(/ -2*xyzzyaaan8,-6*xyzzyaaan8, 8*xyzzyaaan8,-2*xyzzy&
&aaam8,0.d0, 8*xyzzyaaao8 /)
xyzzyaabn8(:,13)=(/  2*xyzzyaaao8,-2*xyzzyaaao8,0.d0,0.d0, 2*xyzzyaaam&
&8,-2*xyzzyaaan8 /)
xyzzyaabn8(:,14)=(/ 0.d0,0.d0,0.d0,   xyzzyaaao8,   xyzzyaaan8,   xyzz&
&yaaam8 /)
xyzzyaabn8(:,15)=(/  6*xyzzyaaam8,-6*xyzzyaaam8,0.d0,-6*xyzzyaaan8,0.d&
&0,0.d0 /)
xyzzyaabn8(:,16)=(/  6*xyzzyaaan8,-6*xyzzyaaan8,0.d0, 6*xyzzyaaam8,0.d&
&0,0.d0 /)
endif
endif
if(xyzzyaaau1(xyzzyaaaf8)>=6)then
xyzzyaabd8=xyzzyaaap8-xyzzyaaaq8
xyzzyaabf8=7*xyzzyaaar8
xyzzyaabg8=3*xyzzyaabk8(2)
xyzzyaabh8=xyzzyaabf8-xyzzyaabk8(2)
xyzzyaabi8=xyzzyaabf8-xyzzyaabg8
xyzzyaabl8(17)=xyzzyaabe8*(xyzzyaabi8)-(xyzzyaabe8-xyzzyaabk8(2))*xyzz&
&yaabg8
xyzzyaabl8(18)=xyzzyaaax8*(xyzzyaabi8)
xyzzyaabl8(19)=xyzzyaaaw8*(xyzzyaabi8)
xyzzyaabl8(20)=(xyzzyaabd8)*(xyzzyaabh8)
xyzzyaabl8(21)=xyzzyaaav8*(xyzzyaabh8)
xyzzyaabl8(22)=xyzzyaaax8*(xyzzyaabb8)
xyzzyaabl8(23)=xyzzyaaaw8*(xyzzyaabc8)
xyzzyaabl8(24)=xyzzyaaap8*(xyzzyaabb8)-xyzzyaaaq8*(xyzzyaabc8)
xyzzyaabl8(25)=xyzzyaaav8*(xyzzyaabd8)
if(fsd)then
call errstop('STO_ORB_EVAL','Gradient and Laplacian of g orbitals not &
&yet implemented.')
endif
endif
endif
endif
xyzzyaaau8=0.d0
xyzzyaaal8=0
do xyzzyaaag8=xyzzyaaar1(xyzzyaaaf8),xyzzyaaar1(xyzzyaaaf8+1)-1
xyzzyaaas8=xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(1)
if(xyzzyaaas8>xyzzyaaad1)then
xyzzyaaah8=xyzzyaaah8+xyzzyaaay1(xyzzyaaag8)
cycle
endif
if(xyzzyaabf1(xyzzyaaag8)/=xyzzyaaau8)then
xyzzyaaat8=exp(-xyzzyaaas8)
endif
if(xyzzyaaal8/=xyzzyaaav1(xyzzyaaag8).or.xyzzyaabf1(xyzzyaaag8)/=xyzzy&
&aaau8)then
xyzzyaaad8=xyzzyaaax1(xyzzyaaag8)
xyzzyaaai8=xyzzyaaay1(xyzzyaaag8)
xyzzyaaae8=xyzzyaaad8+xyzzyaaai8-1
xyzzyaabo8(1:xyzzyaaai8)=xyzzyaabl8(xyzzyaaad8:xyzzyaaae8)*xyzzyaaat8
if(fsd)then
xyzzyaabp8(1,1:xyzzyaaai8)=(xyzzyaabm8(1,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaaay8*xyzzyaabl8(xyzzyaaad8:xyzzyaaae8))*xyzzya&
&aat8
xyzzyaabp8(2,1:xyzzyaaai8)=(xyzzyaabm8(2,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaaaz8*xyzzyaabl8(xyzzyaaad8:xyzzyaaae8))*xyzzya&
&aat8
xyzzyaabp8(3,1:xyzzyaaai8)=(xyzzyaabm8(3,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaaba8*xyzzyaabl8(xyzzyaaad8:xyzzyaaae8))*xyzzya&
&aat8
xyzzyaabq8(1:xyzzyaaai8)=(-2*xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)*(xy&
&zzyaaam8*xyzzyaabm8(1,xyzzyaaad8:xyzzyaaae8)+xyzzyaaan8*xyzzyaabm8(2,&
&xyzzyaaad8:xyzzyaaae8)+xyzzyaaao8*xyzzyaabm8(3,xyzzyaaad8:xyzzyaaae8)&
&+xyzzyaabl8(xyzzyaaad8:xyzzyaaae8))+xyzzyaabf1(xyzzyaaag8)**2*xyzzyaa&
&bl8(xyzzyaaad8:xyzzyaaae8))*xyzzyaaat8
endif
if(present(orbsderivs))then
xyzzyaabr8(1,1:xyzzyaaai8)=(xyzzyaabn8(1,xyzzyaaad8:xyzzyaaae8)-2*xyzz&
&yaaam8*xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)*xyzzyaabm8(1,xyzzyaaad8:&
&xyzzyaaae8)+xyzzyaabl8(xyzzyaaad8:xyzzyaaae8)*((xyzzyaabf1(xyzzyaaag8&
&)*xyzzyaaam8*xyzzyaabk8(-1))**2-xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)&
&*(1-xyzzyaaam8**2*xyzzyaabk8(-2))))*xyzzyaaat8
xyzzyaabr8(2,1:xyzzyaaai8)=(xyzzyaabn8(2,xyzzyaaad8:xyzzyaaae8)-2*xyzz&
&yaaan8*xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)*xyzzyaabm8(2,xyzzyaaad8:&
&xyzzyaaae8)+xyzzyaabl8(xyzzyaaad8:xyzzyaaae8)*((xyzzyaabf1(xyzzyaaag8&
&)*xyzzyaaan8*xyzzyaabk8(-1))**2-xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)&
&*(1-xyzzyaaan8**2*xyzzyaabk8(-2))))*xyzzyaaat8
xyzzyaabr8(3,1:xyzzyaaai8)=(xyzzyaabn8(3,xyzzyaaad8:xyzzyaaae8)-2*xyzz&
&yaaao8*xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)*xyzzyaabm8(3,xyzzyaaad8:&
&xyzzyaaae8)+xyzzyaabl8(xyzzyaaad8:xyzzyaaae8)*((xyzzyaabf1(xyzzyaaag8&
&)*xyzzyaaao8*xyzzyaabk8(-1))**2-xyzzyaabf1(xyzzyaaag8)*xyzzyaabk8(-1)&
&*(1-xyzzyaaao8**2*xyzzyaabk8(-2))))*xyzzyaaat8
xyzzyaabr8(4,1:xyzzyaaai8)=(xyzzyaabn8(4,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaabk8(-1)*(xyzzyaaan8*xyzzyaabm8(1,xyzzyaaad8:x&
&yzzyaaae8)+xyzzyaaam8*xyzzyaabm8(2,xyzzyaaad8:xyzzyaaae8))+xyzzyaabl8&
&(xyzzyaaad8:xyzzyaaae8)*(xyzzyaabf1(xyzzyaaag8)**2+xyzzyaabf1(xyzzyaa&
&ag8)*xyzzyaabk8(-1))*xyzzyaaam8*xyzzyaaan8*xyzzyaabk8(-2))*xyzzyaaat8
xyzzyaabr8(5,1:xyzzyaaai8)=(xyzzyaabn8(5,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaabk8(-1)*(xyzzyaaao8*xyzzyaabm8(1,xyzzyaaad8:x&
&yzzyaaae8)+xyzzyaaam8*xyzzyaabm8(3,xyzzyaaad8:xyzzyaaae8))+xyzzyaabl8&
&(xyzzyaaad8:xyzzyaaae8)*(xyzzyaabf1(xyzzyaaag8)**2+xyzzyaabf1(xyzzyaa&
&ag8)*xyzzyaabk8(-1))*xyzzyaaam8*xyzzyaaao8*xyzzyaabk8(-2))*xyzzyaaat8
xyzzyaabr8(6,1:xyzzyaaai8)=(xyzzyaabn8(6,xyzzyaaad8:xyzzyaaae8)-xyzzya&
&abf1(xyzzyaaag8)*xyzzyaabk8(-1)*(xyzzyaaan8*xyzzyaabm8(3,xyzzyaaad8:x&
&yzzyaaae8)+xyzzyaaao8*xyzzyaabm8(2,xyzzyaaad8:xyzzyaaae8))+xyzzyaabl8&
&(xyzzyaaad8:xyzzyaaae8)*(xyzzyaabf1(xyzzyaaag8)**2+xyzzyaabf1(xyzzyaa&
&ag8)*xyzzyaabk8(-1))*xyzzyaaan8*xyzzyaaao8*xyzzyaabk8(-2))*xyzzyaaat8
endif
endif
xyzzyaaau8=xyzzyaabf1(xyzzyaaag8)
xyzzyaaal8=xyzzyaaav1(xyzzyaaag8)
xyzzyaaac8=xyzzyaaaw1(xyzzyaaag8)
if(xyzzyaaac8==0)then
do xyzzyaaab8=1,xyzzyaaai8
xyzzyaaah8=xyzzyaaah8+1
if(val)then
orbval(1:xyzzyaaaj8,1)=orbval(1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzyaaaj8,&
&xyzzyaaah8,xyzzyaaak8)*xyzzyaabo8(xyzzyaaab8)
endif
if(fsd)then
orbgrad(1,1:xyzzyaaaj8,1)=orbgrad(1,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabp8(1,xyzzyaaab8)
orbgrad(2,1:xyzzyaaaj8,1)=orbgrad(2,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabp8(2,xyzzyaaab8)
orbgrad(3,1:xyzzyaaaj8,1)=orbgrad(3,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabp8(3,xyzzyaaab8)
orblap(1:xyzzyaaaj8,1)=orblap(1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzyaaaj8,&
&xyzzyaaah8,xyzzyaaak8)*xyzzyaabq8(xyzzyaaab8)
if(present(orbsderivs))then
orbsderivs(1,1:xyzzyaaaj8,1)=orbsderivs(1,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(1,xyzzyaaab8)
orbsderivs(2,1:xyzzyaaaj8,1)=orbsderivs(2,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(2,xyzzyaaab8)
orbsderivs(3,1:xyzzyaaaj8,1)=orbsderivs(3,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(3,xyzzyaaab8)
orbsderivs(4,1:xyzzyaaaj8,1)=orbsderivs(4,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(4,xyzzyaaab8)
orbsderivs(5,1:xyzzyaaaj8,1)=orbsderivs(5,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(5,xyzzyaaab8)
orbsderivs(6,1:xyzzyaaaj8,1)=orbsderivs(6,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabr8(6,xyzzyaaab8)
endif
endif
enddo
else
if(val)then
xyzzyaabs8(:xyzzyaaai8)=xyzzyaabk8(xyzzyaaac8)*xyzzyaabo8(:xyzzyaaai8)
endif
if(fsd)then
xyzzyaabt8(1,:xyzzyaaai8)=(xyzzyaaac8*xyzzyaaam8*xyzzyaabk8(xyzzyaaac8&
&-2)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabp8(1,:xyzz&
&yaaai8))
xyzzyaabt8(2,:xyzzyaaai8)=(xyzzyaaac8*xyzzyaaan8*xyzzyaabk8(xyzzyaaac8&
&-2)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabp8(2,:xyzz&
&yaaai8))
xyzzyaabt8(3,:xyzzyaaai8)=(xyzzyaaac8*xyzzyaaao8*xyzzyaabk8(xyzzyaaac8&
&-2)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabp8(3,:xyzz&
&yaaai8))
xyzzyaabu8(:xyzzyaaai8)=(xyzzyaaac8*(xyzzyaaac8+1)*xyzzyaabk8(xyzzyaaa&
&c8-2)*xyzzyaabo8(:xyzzyaaai8)+2*xyzzyaaac8*xyzzyaabk8(xyzzyaaac8-2)*(&
&xyzzyaaam8*xyzzyaabp8(1,:xyzzyaaai8)+xyzzyaaan8*xyzzyaabp8(2,:xyzzyaa&
&ai8)+xyzzyaaao8*xyzzyaabp8(3,:xyzzyaaai8))+xyzzyaabk8(xyzzyaaac8)*xyz&
&zyaabq8(:xyzzyaaai8))
if(present(orbsderivs))then
xyzzyaabv8(1,:xyzzyaaai8)=(xyzzyaaac8*(xyzzyaaac8-1)*xyzzyaaam8**2+(xy&
&zzyaabk8(2)-xyzzyaaam8**2)*xyzzyaaac8)*xyzzyaabk8(xyzzyaaac8-4)*xyzzy&
&aabo8(:xyzzyaaai8)+2*xyzzyaaac8*xyzzyaaam8*xyzzyaabk8(xyzzyaaac8-2)*x&
&yzzyaabp8(1,:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(1,:xyzzyaa&
&ai8)
xyzzyaabv8(2,:xyzzyaaai8)=(xyzzyaaac8*(xyzzyaaac8-1)*xyzzyaaan8**2+(xy&
&zzyaabk8(2)-xyzzyaaan8**2)*xyzzyaaac8)*xyzzyaabk8(xyzzyaaac8-4)*xyzzy&
&aabo8(:xyzzyaaai8)+2*xyzzyaaac8*xyzzyaaan8*xyzzyaabk8(xyzzyaaac8-2)*x&
&yzzyaabp8(2,:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(2,:xyzzyaa&
&ai8)
xyzzyaabv8(3,:xyzzyaaai8)=(xyzzyaaac8*(xyzzyaaac8-1)*xyzzyaaao8**2+(xy&
&zzyaabk8(2)-xyzzyaaao8**2)*xyzzyaaac8)*xyzzyaabk8(xyzzyaaac8-4)*xyzzy&
&aabo8(:xyzzyaaai8)+2*xyzzyaaac8*xyzzyaaao8*xyzzyaabk8(xyzzyaaac8-2)*x&
&yzzyaabp8(3,:xyzzyaaai8)+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(3,:xyzzyaa&
&ai8)
xyzzyaabv8(4,:xyzzyaaai8)=xyzzyaaac8*(xyzzyaaac8-2)*xyzzyaaam8*xyzzyaa&
&an8*xyzzyaabk8(xyzzyaaac8-4)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaaac8*xyzzy&
&aabk8(xyzzyaaac8-2)*(xyzzyaaam8*xyzzyaabp8(2,:xyzzyaaai8)+xyzzyaaan8*&
&xyzzyaabp8(1,:xyzzyaaai8))+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(4,:xyzzy&
&aaai8)
xyzzyaabv8(5,:xyzzyaaai8)=xyzzyaaac8*(xyzzyaaac8-2)*xyzzyaaam8*xyzzyaa&
&ao8*xyzzyaabk8(xyzzyaaac8-4)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaaac8*xyzzy&
&aabk8(xyzzyaaac8-2)*(xyzzyaaam8*xyzzyaabp8(3,:xyzzyaaai8)+xyzzyaaao8*&
&xyzzyaabp8(1,:xyzzyaaai8))+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(5,:xyzzy&
&aaai8)
xyzzyaabv8(6,:xyzzyaaai8)=xyzzyaaac8*(xyzzyaaac8-2)*xyzzyaaan8*xyzzyaa&
&ao8*xyzzyaabk8(xyzzyaaac8-4)*xyzzyaabo8(:xyzzyaaai8)+xyzzyaaac8*xyzzy&
&aabk8(xyzzyaaac8-2)*(xyzzyaaan8*xyzzyaabp8(3,:xyzzyaaai8)+xyzzyaaao8*&
&xyzzyaabp8(2,:xyzzyaaai8))+xyzzyaabk8(xyzzyaaac8)*xyzzyaabr8(6,:xyzzy&
&aaai8)
endif
endif
do xyzzyaaab8=1,xyzzyaaai8
xyzzyaaah8=xyzzyaaah8+1
if(val)then
orbval(1:xyzzyaaaj8,1)=orbval(1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzyaaaj8,&
&xyzzyaaah8,xyzzyaaak8)*xyzzyaabs8(xyzzyaaab8)
endif
if(fsd)then
orbgrad(1,1:xyzzyaaaj8,1)=orbgrad(1,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabt8(1,xyzzyaaab8)
orbgrad(2,1:xyzzyaaaj8,1)=orbgrad(2,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabt8(2,xyzzyaaab8)
orbgrad(3,1:xyzzyaaaj8,1)=orbgrad(3,1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzy&
&aaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabt8(3,xyzzyaaab8)
orblap(1:xyzzyaaaj8,1)=orblap(1:xyzzyaaaj8,1)+xyzzyaabi1(1:xyzzyaaaj8,&
&xyzzyaaah8,xyzzyaaak8)*xyzzyaabu8(xyzzyaaab8)
if(present(orbsderivs))then
orbsderivs(1,1:xyzzyaaaj8,1)=orbsderivs(1,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(1,xyzzyaaab8)
orbsderivs(2,1:xyzzyaaaj8,1)=orbsderivs(2,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(2,xyzzyaaab8)
orbsderivs(3,1:xyzzyaaaj8,1)=orbsderivs(3,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(3,xyzzyaaab8)
orbsderivs(4,1:xyzzyaaaj8,1)=orbsderivs(4,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(4,xyzzyaaab8)
orbsderivs(5,1:xyzzyaaaj8,1)=orbsderivs(5,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(5,xyzzyaaab8)
orbsderivs(6,1:xyzzyaaaj8,1)=orbsderivs(6,1:xyzzyaaaj8,1)+xyzzyaabi1(1&
&:xyzzyaaaj8,xyzzyaaah8,xyzzyaaak8)*xyzzyaabv8(6,xyzzyaaab8)
endif
endif
enddo
endif
enddo
enddo
if(complex_wf)then
if(val)orbval(:,2)=0.d0
if(fsd)then
orbgrad(:,:,2)=0.d0
orblap(:,2)=0.d0
if(present(orbsderivs))orbsderivs(:,:,2)=0.d0
endif
endif
end subroutine sto_orb_eval
subroutine read_stowf_params
implicit none
integer xyzzyaaaa9,xyzzyaaab9,xyzzyaaac9,xyzzyaaad9,xyzzyaaae9,xyzzyaa&
&af9,xyzzyaaag9,xyzzyaaah9,xyzzyaaai9,xyzzyaaaj9
character(80) char_80
xyzzyaacd1=.false.
xyzzyaace1=.false.
call open_units(xyzzyaabr1,xyzzyaaaa9)
if(xyzzyaaaa9/=0)call errstop('READ_STOWF_PARAMS','Cannot find free IO&
& unit.')
open(unit=xyzzyaabr1,file='correlation.data',status='old',iostat=xyzzy&
&aaaa9)
if(xyzzyaaaa9/=0)call errstop('READ_STOWF_PARAMS','Problem opening cor&
&relation.data.')
if(am_master)then
call wout('Modified STOWF orbitals')
call wout('=======================')
call wout('Reading STOWF orbital information from correlation.data fil&
&e.')
call wout()
endif
do
read(xyzzyaabr1,'(a)',iostat=xyzzyaaaa9)char_80
if(xyzzyaaaa9>0.and.am_master)call errstop('READ_STOWF_PARAMS','Proble&
&m reading correlation.data. Please check this file.')
if(xyzzyaaaa9<0.and.am_master)call errstop('READ_STOWF_PARAMS','Could &
&not find "START MOLORBMODS" in correlation.data.')
if(trim(adjustl(char_80))=='START MOLORBMODS')exit
enddo
read(xyzzyaabr1,*,err=10,end=10)
read(xyzzyaabr1,'(a)',err=10,end=10)param_title
if(am_master)call wout('Title: '//trim(adjustl(param_title)))
mainloop: do
read(xyzzyaabr1,'(a)',err=10,end=10)char_80
if(trim(adjustl(char_80))=='START MO COEFFICIENTS')then
if(am_master)then
if(xyzzyaacd1)call errstop('READ_STOWF_PARAMS','Only one MO COEFFICIEN&
&TS term allowed.')
call wout()
call wout()
call wout(' Molecular orbital coefficients:')
call wout()
endif
xyzzyaacd1=.true.
if(cusp_correction)then
xyzzyaabg1(:,xyzzyaaaz1(:),:)=0.d0
endif
xyzzyaaai9=sum(xyzzyaaam1(1:xyzzyaaaj1))*xyzzyaaaq1*1
allocate(xyzzyaabz1(xyzzyaaai9),stat=xyzzyaaaj9)
call check_alloc(xyzzyaaaj9,'READ_STOWF_PARAMS','rcktemp')
xyzzyaaad9=1
do xyzzyaaaf9=1,xyzzyaaaj1
do xyzzyaaae9=1,xyzzyaaam1(xyzzyaaaf9)
xyzzyaabz1(xyzzyaaad9:xyzzyaaad9+xyzzyaaaq1-1)=xyzzyaabg1(xyzzyaaae9,1&
&:xyzzyaaaq1,xyzzyaaaf9)
xyzzyaaad9=xyzzyaaad9+xyzzyaaaq1
enddo
enddo
call xyzzyaacv1(xyzzyaabz1,xyzzyaabx1)
if(am_master)then
call wout('Number of inequivalent MO coefficients   : '//trim(i2s(xyzz&
&yaabx1)))
endif
allocate(xyzzyaabt1(xyzzyaabx1),xyzzyaabv1(xyzzyaabx1),xyzzyaaca1(xyzz&
&yaaai9),stat=xyzzyaaaj9)
call check_alloc(xyzzyaaaj9,'READ_STOWF_PARAMS','indexrcktemp')
xyzzyaabt1=0.d0
xyzzyaaca1=0
call xyzzyaacu1(xyzzyaabz1,xyzzyaabx1,xyzzyaabt1,xyzzyaaca1)
xyzzyaabv1(:)=1
read(xyzzyaabr1,*,err=10,end=10)
read_params_mocoeff: do xyzzyaaab9=1,xyzzyaabx1
read(xyzzyaabr1,*,iostat=xyzzyaaaa9)xyzzyaabt1(xyzzyaaab9),xyzzyaabv1(&
&xyzzyaaab9)
if(xyzzyaaaa9/=0.and.xyzzyaaab9==1)then
backspace xyzzyaabr1
exit read_params_mocoeff
elseif(xyzzyaaaa9/=0)then
if(am_master)then
call wout()
call wout(' A total of '//trim(i2s(xyzzyaabx1))//' coefficients is exp&
&ected.')
call errstop('READ_STOWF_PARAMS','Not enough MO coefficients are suppl&
&ied.')
endif
endif
if(am_master.and.xyzzyaabv1(xyzzyaaab9)/=0.and.xyzzyaabv1(xyzzyaaab9)/&
&=1)call errstop('READ_STOWF_PARAMS','Optimizable flag should be 0 or &
&1.')
if(am_master)call display_param(xyzzyaabt1(xyzzyaaab9),xyzzyaabv1(xyzz&
&yaaab9),'moc_'//trim(i2s(xyzzyaaab9)))
xyzzyaabq1=.false.
enddo read_params_mocoeff
if(am_master)then
if(xyzzyaaaa9/=0)then
call wout(' No optimized coefficients supplied. Use original values.')
call wout()
do xyzzyaaab9=1,xyzzyaabx1
call display_param(xyzzyaabt1(xyzzyaaab9),xyzzyaabv1(xyzzyaaab9),'moc_&
&'//trim(i2s(xyzzyaaab9)))
enddo
endif
xyzzyaaah9=count(xyzzyaabv1>0)
call wout('  No. of free params    :  '//trim(i2s(xyzzyaaah9)))
call wout()
endif
xyzzyaaag9=0
xyzzyaaac9=1
do xyzzyaaab9=1,xyzzyaabx1
if(xyzzyaabv1(xyzzyaaab9)==0)xyzzyaaag9=xyzzyaaag9+1
if(abs(xyzzyaabt1(xyzzyaaab9))>abs(xyzzyaabt1(xyzzyaaac9)))xyzzyaaac9=&
&xyzzyaaab9
enddo
if(xyzzyaaag9==0)then
xyzzyaabv1(xyzzyaaac9)=0
if(am_master)then
call wout()
call wordwrap(' All MO coefficients are set as optimizable, so the lar&
&gest coefficient (moc_'//trim(i2s(xyzzyaaac9))//') will be kept fixed&
&.')
call wout()
endif
endif
read(xyzzyaabr1,'(a)',iostat=xyzzyaaaa9)char_80
if(am_master.and.xyzzyaaaa9/=0)call errstop('READ_STOWF_PARAMS','Strin&
&g "END MO COEFFICIENTS" not found.')
if(trim(adjustl(char_80))/='END MO COEFFICIENTS')call errstop('READ_ST&
&OWF_PARAMS','String "END MO COEFFICIENTS" not found.')
elseif(trim(adjustl(char_80))=='START STO EXPONENTS')then
if(am_master)then
if(xyzzyaace1)call errstop('READ_STOWF_PARAMS','Only one STO EXPONENTS&
& term allowed.')
call wout()
call wout(' STO exponents:')
call wout()
endif
xyzzyaace1=.true.
xyzzyaaby1=xyzzyaaap1
allocate(xyzzyaabu1(xyzzyaaby1),xyzzyaabw1(xyzzyaaby1),stat=xyzzyaaaj9&
&)
call check_alloc(xyzzyaaaj9,'READ_STOWF_PARAMS','opt_exponent,...')
xyzzyaabw1(:)=1
read(xyzzyaabr1,*,err=10,end=10)
read_params_exponent: do xyzzyaaab9=1,xyzzyaaby1
read(xyzzyaabr1,*,iostat=xyzzyaaaa9)xyzzyaabu1(xyzzyaaab9),xyzzyaabw1(&
&xyzzyaaab9)
if(xyzzyaaaa9/=0.and.xyzzyaaab9==1)then
backspace xyzzyaabr1
xyzzyaabu1(:)=xyzzyaabf1(:)
exit read_params_exponent
elseif(xyzzyaaaa9/=0)then
if(am_master)then
call wout()
call wout(' A total of '//trim(i2s(xyzzyaaby1))//' exponents are expec&
&ted.')
call errstop('READ_STOWF_PARAMS','Not enough exponent parameters are s&
&upplied.')
endif
endif
if(am_master.and.xyzzyaabw1(xyzzyaaab9)/=0.and.xyzzyaabw1(xyzzyaaab9)/&
&=1)call errstop('READ_STOWF_PARAMS','Optimizable flag should be 0 or &
&1.')
if(am_master)call display_param(xyzzyaabu1(xyzzyaaab9),xyzzyaabw1(xyzz&
&yaaab9),'expo_'//trim(i2s(xyzzyaaab9)))
xyzzyaabq1=.false.
enddo read_params_exponent
if(am_master)then
if(xyzzyaaaa9/=0)then
call wout(' No exponent parameters supplied. Use original values.')
call wout()
do xyzzyaaab9=1,xyzzyaaby1
call display_param(xyzzyaabu1(xyzzyaaab9),xyzzyaabw1(xyzzyaaab9),'expo&
&_'//trim(i2s(xyzzyaaab9)))
enddo
endif
xyzzyaaah9=count(xyzzyaabw1>0)
call wout('  No. of free params     :  '//trim(i2s(xyzzyaaah9)))
call wout()
endif
read(xyzzyaabr1,'(a)',iostat=xyzzyaaaa9)char_80
if(am_master.and.xyzzyaaaa9/=0)call errstop('READ_STOWF_PARAMS','Strin&
&g "END STO EXPONENTS" not found.')
if(trim(adjustl(char_80))/='END STO EXPONENTS')call errstop('READ_STOW&
&F_PARAMS','String "END STO EXPONENTS" not found.')
elseif(trim(adjustl(char_80))=='END MOLORBMODS')then
exit mainloop
elseif(trim(adjustl(char_80))/="")then
if(am_master)call errstop('READ_STOWF_PARAMS','Expecting e.g. "START M&
&O COEFFICIENTS" in correlation.data.')
endif
enddo mainloop
do
read(xyzzyaabr1,'(a)',iostat=xyzzyaaaa9)char_80
if(xyzzyaaaa9<0)exit
if(xyzzyaaaa9>0)call errstop('READ_STOWF_PARAMS','Problem reading corr&
&elation.data. Please check this file.')
if(trim(adjustl(char_80))=='START MOLORBMODS')call errstop('READ_STOWF&
&_PARAMS','There seems to be more than one set of  optimized molecular&
& orbital coefficients in correlation.data.')
enddo
close(xyzzyaabr1)
call xyzzyaacs1
return
10 call errstop('READ_STOWF_PARAMS','Problem reading optimized molecul&
&ar orbital coefficients in correlation.data. Please check this file.'&
&)
end subroutine read_stowf_params
subroutine write_stowf_params(correlation_name)
implicit none
character(20),intent(in) :: correlation_name
integer xyzzyaaaa10,xyzzyaaab10
logical xyzzyaaac10
if(.not.am_master)return
inquire(file=trim(correlation_name),exist=xyzzyaaac10)
if(xyzzyaaac10)then
open(unit=xyzzyaabr1,file=trim(correlation_name),status='old',position&
&='append',iostat=xyzzyaaaa10)
else
open(unit=xyzzyaabr1,file=trim(correlation_name),status='replace',iost&
&at=xyzzyaaaa10)
endif
if(xyzzyaaaa10/=0)call errstop('WRITE_STOWF_PARAMS','Problem opening '&
&//trim(correlation_name)//'.')
write(xyzzyaabr1,*)'START MOLORBMODS'
write(xyzzyaabr1,*)'Title'
write(xyzzyaabr1,*)trim(param_title)
if(xyzzyaacd1)then
write(xyzzyaabr1,*)'START MO COEFFICIENTS'
write(xyzzyaabr1,*)'Parameter values  ;  Optimizable (0=NO; 1=YES)'
do xyzzyaaab10=1,xyzzyaabx1
write(xyzzyaabr1,*)xyzzyaabt1(xyzzyaaab10),xyzzyaabv1(xyzzyaaab10),'      !&
& moc_',trim(i2s(xyzzyaaab10))
enddo
write(xyzzyaabr1,*)'END MO COEFFICIENTS'
endif
if(xyzzyaace1)then
write(xyzzyaabr1,*)'START STO EXPONENTS'
write(xyzzyaabr1,*)'Parameter values           ;  Optimizable (0=NO; 1&
&=YES)'
do xyzzyaaab10=1,xyzzyaaby1
write(xyzzyaabr1,*)xyzzyaabu1(xyzzyaaab10),xyzzyaabw1(xyzzyaaab10),'      !&
& expo_',trim(i2s(xyzzyaaab10))
enddo
write(xyzzyaabr1,*)'END STO EXPONENTS'
endif
write(xyzzyaabr1,*)'END MOLORBMODS'
close(xyzzyaabr1)
end subroutine write_stowf_params
subroutine setup_stowf_params(nparam)
implicit none
integer,intent(out) :: nparam
integer xyzzyaaaa11
nparam=0
if(xyzzyaacd1)then
do xyzzyaaaa11=1,xyzzyaabx1
if(xyzzyaabv1(xyzzyaaaa11)==1)nparam=nparam+1
enddo
endif
if(xyzzyaace1)then
do xyzzyaaaa11=1,xyzzyaaby1
if(xyzzyaabw1(xyzzyaaaa11)==1)nparam=nparam+1
enddo
endif
xyzzyaabs1=nparam
call xyzzyaaco1
end subroutine setup_stowf_params
subroutine finish_stowf_params
implicit none
call xyzzyaacp1
end subroutine finish_stowf_params
subroutine xyzzyaaco1
implicit none
integer xyzzyaaaa13
allocate(xyzzyaacf1(maxval(xyzzyaaam1),xyzzyaaaq1,xyzzyaaaj1,0:xyzzyaa&
&bs1),xyzzyaacg1(xyzzyaaap1,0:xyzzyaabs1),stat=xyzzyaaaa13)
call check_alloc(xyzzyaaaa13,'SETUP_STOWF_PBUFFER','1')
end subroutine xyzzyaaco1
subroutine xyzzyaacp1
implicit none
deallocate(xyzzyaacf1,xyzzyaacg1)
end subroutine xyzzyaacp1
subroutine get_stowf_params(params,has_lolim,lolim,has_hilim,hilim,is_&
&shallow,is_redundant,is_linear,is_loglinear,has_aderiv,affect_map,lab&
&el)
implicit none
real(dp),intent(inout) :: params(xyzzyaabs1),lolim(xyzzyaabs1),hilim(x&
&yzzyaabs1)
logical,intent(inout) :: has_lolim(xyzzyaabs1),has_hilim(xyzzyaabs1),i&
&s_shallow(xyzzyaabs1),is_redundant(xyzzyaabs1),is_linear(xyzzyaabs1),&
&is_loglinear(xyzzyaabs1),has_aderiv(xyzzyaabs1),affect_map(xyzzyaabs1&
&,xyzzyaabs1)
character(2),intent(inout) :: label(xyzzyaabs1)
integer xyzzyaaaa15,xyzzyaaab15
real(dp) xyzzyaaac15
has_lolim=.false.
lolim=0.d0
has_hilim=.false.
hilim=0.d0
is_shallow=.false.
is_redundant=.false.
is_linear=.false.
is_loglinear=.false.
has_aderiv=.false.
affect_map=.false.
do xyzzyaaaa15=1,xyzzyaabs1
affect_map(xyzzyaaaa15,xyzzyaaaa15)=.true.
enddo
label='OP'
xyzzyaaac15=1.1d-8
xyzzyaaaa15=0
if(xyzzyaacd1)then
do xyzzyaaab15=1,xyzzyaabx1
if(xyzzyaabv1(xyzzyaaab15)==1)then
xyzzyaaaa15=xyzzyaaaa15+1
params(xyzzyaaaa15)=xyzzyaabt1(xyzzyaaab15)
endif
enddo
endif
if(xyzzyaace1)then
do xyzzyaaab15=1,xyzzyaaby1
if(xyzzyaabw1(xyzzyaaab15)==1)then
xyzzyaaaa15=xyzzyaaaa15+1
params(xyzzyaaaa15)=xyzzyaabu1(xyzzyaaab15)
has_lolim(xyzzyaaaa15)=.true.
lolim(xyzzyaaaa15)=xyzzyaaac15
endif
enddo
endif
end subroutine get_stowf_params
subroutine put_stowf_params(params,ignore,iparam_buffer,prestore,bad_p&
&arams)
implicit none
integer,intent(in) :: iparam_buffer
real(dp),intent(inout) :: params(xyzzyaabs1)
logical,intent(in) :: ignore(xyzzyaabs1),prestore
logical,intent(out) :: bad_params
integer xyzzyaaaa16,xyzzyaaab16
bad_params=.false.
if(prestore)then
call xyzzyaacr1(iparam_buffer)
return
endif
xyzzyaaab16=0
if(xyzzyaacd1)then
do xyzzyaaaa16=1,xyzzyaabx1
if(xyzzyaabv1(xyzzyaaaa16)==1)then
xyzzyaaab16=xyzzyaaab16+1
if(.not.ignore(xyzzyaaab16))xyzzyaabt1(xyzzyaaaa16)=params(xyzzyaaab16&
&)
endif
enddo
endif
if(xyzzyaace1)then
do xyzzyaaaa16=1,xyzzyaaby1
if(xyzzyaabw1(xyzzyaaaa16)==1)then
xyzzyaaab16=xyzzyaaab16+1
if(.not.ignore(xyzzyaaab16))xyzzyaabu1(xyzzyaaaa16)=params(xyzzyaaab16&
&)
endif
enddo
endif
call xyzzyaacs1
call xyzzyaacq1(iparam_buffer)
end subroutine put_stowf_params
subroutine xyzzyaacq1(indx)
implicit none
integer,intent(in) :: indx
xyzzyaacf1(:,:,:,indx)=xyzzyaabi1(:,:,:)
xyzzyaacg1(:,indx)=xyzzyaabf1(:)
end subroutine xyzzyaacq1
subroutine xyzzyaacr1(indx)
implicit none
integer,intent(in) :: indx
xyzzyaabi1(:,:,:)=xyzzyaacf1(:,:,:,indx)
xyzzyaabf1(:)=xyzzyaacg1(:,indx)
end subroutine xyzzyaacr1
subroutine xyzzyaacs1
implicit none
integer xyzzyaaaa19,xyzzyaaab19,xyzzyaaac19
if(xyzzyaacd1)then
call xyzzyaact1(xyzzyaabt1,xyzzyaaca1,xyzzyaabz1)
xyzzyaaab19=1
do xyzzyaaac19=1,xyzzyaaaj1
do xyzzyaaaa19=1,xyzzyaaam1(xyzzyaaac19)
xyzzyaabg1(xyzzyaaaa19,1:xyzzyaaaq1,xyzzyaaac19)=xyzzyaabz1(xyzzyaaab1&
&9:xyzzyaaab19+xyzzyaaaq1-1)
xyzzyaaab19=xyzzyaaab19+xyzzyaaaq1
enddo
enddo
endif
if(xyzzyaace1)then
xyzzyaabf1(:)=abs(xyzzyaabu1(:))
if(xyzzyaabp1)call xyzzyaack1
endif
if((xyzzyaacd1.or.xyzzyaace1).and.xyzzyaabp1.and.cusp_correction)call &
&xyzzyaacn1
end subroutine xyzzyaacs1
subroutine xyzzyaact1(ineqarr,indexarr,arr)
implicit none
integer,intent(in) :: indexarr(:)
real(dp),intent(out) :: arr(:)
real(dp),intent(in) :: ineqarr(:)
integer xyzzyaaaa20,xyzzyaaab20
xyzzyaaab20=size(arr)
arr=0.d0
do xyzzyaaaa20=1,xyzzyaaab20
if(indexarr(xyzzyaaaa20)==0)then
arr(xyzzyaaaa20)=0.d0
elseif(indexarr(xyzzyaaaa20)<0)then
arr(xyzzyaaaa20)=-1.d0*ineqarr(-indexarr(xyzzyaaaa20))
else
arr(xyzzyaaaa20)=ineqarr(indexarr(xyzzyaaaa20))
endif
enddo
end subroutine xyzzyaact1
subroutine xyzzyaacu1(arr,numineq,ineqarr,indexarr)
implicit none
integer,intent(in) :: numineq
integer,intent(inout) :: indexarr(:)
real(dp),intent(in) :: arr(:)
real(dp),intent(inout) :: ineqarr(numineq)
integer xyzzyaaaa21,xyzzyaaab21,xyzzyaaac21,xyzzyaaad21
real(dp) xyzzyaaae21
real(dp) :: xyzzyaaaf21=1d-5
xyzzyaaad21=size(arr)
indexarr(:)=0
ineqarr(:)=0.d0
xyzzyaaac21=0
do xyzzyaaaa21=1,xyzzyaaad21
if(indexarr(xyzzyaaaa21)==0.and.arr(xyzzyaaaa21)/=0.d0)then
xyzzyaaac21=xyzzyaaac21+1
do xyzzyaaab21=xyzzyaaaa21,xyzzyaaad21
if(xyzzyaacb1(xyzzyaaaa21)==xyzzyaacb1(xyzzyaaab21).and.xyzzyaacc1(xyz&
&zyaaaa21)==xyzzyaacc1(xyzzyaaab21))then
xyzzyaaae21=abs((abs(arr(xyzzyaaaa21))-abs(arr(xyzzyaaab21)))/abs(arr(&
&xyzzyaaaa21)))
if(xyzzyaaae21<xyzzyaaaf21)then
if((arr(xyzzyaaaa21)>0.d0.and.arr(xyzzyaaab21)>0.d0).or.(arr(xyzzyaaaa&
&21)<0.d0.and.arr(xyzzyaaab21)<0.d0))then
indexarr(xyzzyaaab21)=xyzzyaaac21
else
indexarr(xyzzyaaab21)=-xyzzyaaac21
endif
ineqarr(xyzzyaaac21)=arr(xyzzyaaaa21)
endif
endif
enddo
endif
enddo
end subroutine xyzzyaacu1
subroutine xyzzyaacv1(arr,num)
implicit none
integer,intent(out) :: num
real(dp),intent(in) ::  arr(:)
integer xyzzyaaaa22,xyzzyaaab22,xyzzyaaac22,xyzzyaaad22,xyzzyaaae22
integer,allocatable :: xyzzyaaaf22(:)
real(dp) xyzzyaaag22
real(dp) :: xyzzyaaah22=1.d-5
real(dp),allocatable :: xyzzyaaai22(:)
xyzzyaaad22=size(arr)
allocate(xyzzyaaaf22(xyzzyaaad22),xyzzyaaai22(xyzzyaaad22),xyzzyaacb1(&
&xyzzyaaad22),xyzzyaacc1(xyzzyaaad22), stat=xyzzyaaae22)
call check_alloc(xyzzyaaae22,'NUMINEQUIV','')
num=0
xyzzyaaaf22=0
xyzzyaaac22=0
xyzzyaaai22(:)=arr(:)
xyzzyaacb1=0
xyzzyaacc1=0
do xyzzyaaaa22=1,xyzzyaaad22
do xyzzyaaab22=xyzzyaaaa22,xyzzyaaad22
if(xyzzyaaai22(xyzzyaaaa22)/=0.d0)then
if(xyzzyaacb1(xyzzyaaaa22)==xyzzyaacb1(xyzzyaaab22).and.xyzzyaacc1(xyz&
&zyaaaa22)==xyzzyaacc1(xyzzyaaab22))then
xyzzyaaag22=abs((abs(xyzzyaaai22(xyzzyaaaa22))-abs(xyzzyaaai22(xyzzyaa&
&ab22)))/abs(xyzzyaaai22(xyzzyaaaa22)))
if(xyzzyaaag22<xyzzyaaah22)then
if(xyzzyaaaa22/=xyzzyaaab22)xyzzyaaai22(xyzzyaaab22)=0.d0
xyzzyaaac22=xyzzyaaac22+1
endif
endif
endif
enddo
xyzzyaaaf22(xyzzyaaaa22)=xyzzyaaac22
xyzzyaaac22=0
enddo
do xyzzyaaaa22=1,xyzzyaaad22
if(xyzzyaaaf22(xyzzyaaaa22)/=0)num=num+1
enddo
deallocate(xyzzyaaaf22,xyzzyaaai22)
end subroutine xyzzyaacv1
subroutine get_stowfdet_orbmap(row_offset,norb,orbmap)
implicit none
integer,intent(inout) :: row_offset(nspin),norb,orbmap(nemax,nspin,nde&
&t)
integer xyzzyaaaa23,xyzzyaaab23,xyzzyaaac23
do xyzzyaaaa23=1,nspin
do xyzzyaaab23=1,nuc_nele(xyzzyaaaa23)
do xyzzyaaac23=1,ndet
orbmap(row_offset(xyzzyaaaa23)+xyzzyaaab23,xyzzyaaaa23,xyzzyaaac23)=no&
&rb+xyzzyaaab23
enddo
enddo
row_offset(xyzzyaaaa23)=row_offset(xyzzyaaaa23)+nuc_nele(xyzzyaaaa23)
enddo
norb=norb+maxval(xyzzyaaam1)
end subroutine get_stowfdet_orbmap
subroutine get_stowfdet_ndesc(ndesc_int,ndesc_dp)
implicit none
integer,intent(inout) :: ndesc_int,ndesc_dp
ndesc_int=xyzzyaach1
ndesc_dp=xyzzyaaci1
end subroutine get_stowfdet_ndesc
subroutine get_stowfdet_orbdesc(norb,ndesc_int,ndesc_dp,orbdesc_int,or&
&bdesc_dp)
implicit none
integer,intent(in) :: norb,ndesc_int,ndesc_dp
integer,intent(inout) :: orbdesc_int(ndesc_int,norb)
real(dp),intent(inout) :: orbdesc_dp(ndesc_dp,norb)
end subroutine get_stowfdet_orbdesc
end module slaarnacl
